### ISSUE TITLE
Generate less output when not actually installing anything

### ISSUE THREAD

**Issue by technicalpickles** [Homebrew/homebrew-bundle#100]
I'm looking to add a `Brewfile` to a project, and run `brew bundle` when [bootstrapping it](http://githubengineering.com/scripts-to-rule-them-all/).

If I have a pretty simple `Brewfile` like:

```ruby
brew 'nagios'
```

And I run `brew bundle` multiple times, I always get this output, even when nagios is already installed:

```
$ brew bundle
Succeeded in installing nagios

Success: 1 Fail: 0
```

I could imagine there being a flag like `--quiet` which only outputs if something was actually installed. Or, maybe having a `--check` option which is used for scripting, so you can do something like this: https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap#L10-L13

**Comment by josh** [comment]
:+1: 

> [Rule of Silence: When a program has nothing surprising to say, it should say nothing.](http://www.linfo.org/rule_of_silence.html)

**Comment by mikemcquaid** [comment]
:+1:

**Comment by voanhduy1512** [comment]
@mikemcquaid do you need a hand :happy:

**Comment by mikemcquaid** [comment]
@voanhduy1512 That would be great!
