### ISSUE TITLE
Global Brewfile would be better placed somewhere under ~/.config or ~/.local as per XDG

### ISSUE THREAD

**Issue by tko** [Homebrew/homebrew-bundle#1002]
The global Brewfile is somewhat inconveniently placed as ~/.Brewfile (macos) with no configuration or environment variables allowing to change its location. This is doubly inconvenient given the additional generation of .Brewfile.lock.json in the home folder.

Instead of adding to polluting the home folder with gazillion other dotfiles with no structure it would be better to place the files in a subfolder as per XDG.

The Brewfile should almost certainly be used as `~/.config/homebrew-bundle/Brewfile` but I'm uncertain of whether the lockfile should be better treated as configuration or data.

ref: [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by jacobbednarz** [comment]
You can toggle where the file is dumped to and read from using `--file` of you'd like it somewhere else.

**Comment by MikeMcQuaid** [comment]
macOS does not follow the XDG. homebrew-bundle was originally macOS only. We cannot change the default location without breaking all existing users.

**Comment by tko** [comment]
Operating systems don't follow the XDG, applications do. Many applications can look up configuration files from multiple locations in order of preference, using the first one that's found. Changing default location with a fallback to previous shouldn't break anything.

I wouldn't necessarily object to using `~/Library/Application Support` like macos apps are meant to but for terminal apps I think XDG is more appropriate.

**Comment by MikeMcQuaid** [comment]
> Changing default location with a fallback to previous shouldn't break anything.

We'll review a PR to fallback to XDG locations if the necessary variables are set.
