### ISSUE TITLE
brew bundle dump key not found

### ISSUE THREAD

**Issue by pdebruic** [Homebrew/homebrew-bundle#1020]
`brew bundle dump`

gives 
```
Error: key not found: "jeffreywildman/virt-manager/osinfo-db"
Did you mean?  "jeffreywildman/virt-manager/osinfo-db-tools"
```

**Comment by MikeMcQuaid** [comment]
@pdebruic please provide some more debugging information i.e. `brew config` output, `brew doctor` output, `brew bundle dump --debug` output, `brew bundle` output and `brew list --full-name` and the contents of your `Brewfile`.
