### ISSUE TITLE
End of install error: Error: No such image: whalebrew/whalesay

### ISSUE THREAD

**Issue by abarring-pinc** [Homebrew/homebrew-bundle#1024]
Started receiving this error at the end of a brew bundle install. Reporting this bug as requested

```
Error: No such image: whalebrew/whalesay
Error: undefined method `chomp' for nil:NilClass
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:130:in `block in whalebrew_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:128:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:128:in `each_with_object'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:128:in `whalebrew_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:52:in `block in lock'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:36:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/locker.rb:36:in `lock'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:64:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

Let me know if there are deeper debugging settings for more logging to help out.

**Comment by colindean** [comment]
Please provide the contents of the Brewfile that you're using.

**Comment by colindean** [comment]
While you're at it, gather the `brew config` output and `brew doctor` output and put them in a gist and link it here, please.

**Comment by abarring-pinc** [comment]
Brewfile: https://gist.github.com/abarring-pinc/511cf8e475346ee82a75cece1b27c430
brew output: https://gist.github.com/abarring-pinc/9133e6cc7734951f476162e56b8705bc

Thanks!

**Comment by colindean** [comment]
Are you able to successfully execute `docker pull whalebrew/whalesay`? [`whalebrew/whalesay`](https://hub.docker.com/r/whalebrew/whalesay) definitely still exists. Maybe it was a transient error. Have you tried again?

I'll look into the other failure there.

**Comment by colindean** [comment]
WAIT. Before you do that:

What do you see when you run `docker image inspect whalebrew/whalesay --format '{{ index .RepoDigests 0 }}'`?

https://github.com/Homebrew/homebrew-bundle/blob/e11704f58688da7e9d0192d08ff2b31c252a2f6b/lib/bundle/locker.rb#L127-L132

It looks we've got an assumption of the data format output by that command, but it outputs something we didn't expect when it fails. I'll look into making that safer while we figure out what your system is outputting that isn't what we expect out of Docker, esp if whalesay is installed (and if it isn't, why does `whalebrew list` include it but it's not pulled/otherwise available).

**Comment by abarring-pinc** [comment]
```
$ docker image inspect whalebrew/wget --format '{{ index .RepoDigests 0 }}'
whalebrew/wget@sha256:dff6b84c2e317d4c1a6a81c55e6f91d46b73dc19713f53d06cf3a3b19b0c7815
```
