### ISSUE TITLE
A way to force bundle not to skip formulas without bottles

### ISSUE THREAD

**Issue by thomasbreydo** [Homebrew/homebrew-bundle#1028]
From what I understand, #972 causes the following behavior on Apple Silicon:

``` txt
$ cat Brewfile
brew "go"
...

$ brew bundle
Skipping go (no bottle for Apple Silicon)
...
```

I totally understand the reason,

> "Otherwise, a working Brewfile on Intel is likely to break on Apple Silicon."

But, for my use case, I would rather `brew bundle` try to install `go`, and exit if it fails to build from source. This is because I ensure that every formula in my Brewfile can be built from source (e.g. `brew install go` works).

**Perhaps you could add a flag like `--no-skip` or `--no-skip-unbottled` that forces `brew bundle` not to skip formulas without bottles?**

(Sorry if I missed anything--this is my first issue. BTW, I think this is would resolve #984.)

**Comment by MikeMcQuaid** [comment]
> But, for my use case, I would rather `brew bundle` try to install `go`, and exit if it fails to build from source. This is because I ensure that every formula in my Brewfile can be built from source (e.g. `brew install go` works).

Out of interest: there is a bottle for Apple Silicon for Go.

> Warning: Your Homebrew's prefix is not /opt/homebrew.

Aha, this is probably it. This behaviour does not really make much sense if you're outside of the default prefix.

**Comment by thomasbreydo** [comment]
Thank you!
