### ISSUE TITLE
Support for Homebrew formulae aliases using brew bundle cleanup

### ISSUE THREAD

**Issue by adamliter** [Homebrew/homebrew-bundle#103]
In my Brewfile, I have `brew 'gpg'`, which is a Homebrew alias for `gnupg`. However, when I run `brew bundle cleanup`, it says that `gnupg` will be removed.

Would there be a way to support the aliases that are defined in [`/homebrew/Library/Aliases`](https://github.com/Homebrew/homebrew/tree/master/Library/Aliases) so that this doesn't happen when running `brew bundle cleanup`?

**Comment by mikemcquaid** [comment]
Interesting. Without being too difficult might I ask why you don't put `brew 'gnupg'` in your `Brewfile`? I'm tempted to handle this case by erroring out if you use an alias as otherwise it'll add a pretty large performance overhead on every other `Brewfile` not using aliases. CC @xu-cheng for thoughts.

**Comment by xu-cheng** [comment]
Personally, I think `brew cleanup` should only be run against the Brewfile created by `brew dump`. Running against DIY Brewfile, IMO, is potentially dangerous.

**Comment by mikemcquaid** [comment]
> Personally, I think brew bundle cleanup should only be run against the Brewfile created by brew bundle dump. Running against DIY Brewfile, IMO, is potentially dangerous.

:+1:

**Comment by adamliter** [comment]
I created the Brewfile myself because I had some stuff installed on my machine that I didn't necessarily want anymore. I only used `gpg` instead of `gnupg` because that is how I remember installing it. It's easy enough for me to just change it to `gnupg`, so that's fine, but it does seem a bit odd to me that sanctioned Homebrew aliases wouldn't be supported.

I'm not sure that I entirely understand why running `brew bundle cleanup` against a handmade Brewfile would be dangerous, but you all know this program better than me, so I'm happy to defer to you all if you don't want to support Homebrew aliases in the `cleanup` functionality.

**Comment by mikemcquaid** [comment]
> I'm not sure that I entirely understand why running brew bundle cleanup against a handmade Brewfile would be dangerous, but you all know this program better than me, so I'm happy to defer to you all if you don't want to support Homebrew aliases in the cleanup functionality.

I guess it's mainly that if you end up typoing something then you may end up removing software you don't intend too. Maybe "dangerous" is too strong, I dunno.

> I created the Brewfile myself because I had some stuff installed on my machine that I didn't necessarily want anymore. I only used gpg instead of gnupg because that is how I remember installing it. It's easy enough for me to just change it to gnupg, so that's fine, but it does seem a bit odd to me that sanctioned Homebrew aliases wouldn't be supported.

Cool. I'll probably just make it error out if I can't work out something smarter.

**Comment by mikemcquaid** [comment]
Fixed by #116.
