### ISSUE TITLE
I've set HOMEBREW_BUNDLE_FILE but still get "Error: No Brewfile found"

### ISSUE THREAD

**Issue by tadasajon** [Homebrew/homebrew-bundle#1030]
I would like to store my `Brewfile` in my `$HOME/.config/` directory so, following this issue -- https://github.com/Homebrew/homebrew-bundle/issues/721 -- I've set a `$HOMEBREW_BUNDLE_FILE` environment variable.  But when I try to run `brew bundle install` it tells me that it can't find my Brewfile.  What am I doing wrong?

<img width="540" alt="Screen Shot 2021-11-30 at 12 13 18 PM" src="https://user-images.githubusercontent.com/86680401/144096645-c5b42544-c0f4-4b20-b7ac-bcfd460dd78c.png">

**Comment by MikeMcQuaid** [comment]
Did you `export` it?

**Comment by tadasajon** [comment]
> Did you export it?

Thanks -- that was my problem.

For anyone else coming across this issue: my `$HOME/.zshrc` file now has
```zsh
export HOMEBREW_BUNDLE_FILE="$HOME/.config/Brewfile"
```
instead of just
```zsh
HOMEBREW_BUNDLE_FILE="$HOME/.config/Brewfile"
```
