### ISSUE TITLE
Feature request: allow "gem" subcommand

### ISSUE THREAD

**Issue by bretmogilefsky** [Homebrew/homebrew-bundle#104]
I use [brew-gem](https://github.com/sportngin/brew-gem) to manage my installed Ruby gems with homebrew, but when I put `gem install somegemname` on a line in a Brewfile, I get `Error: Invalid Brewfile.`

Can you make these two great tastes taste great together?

**Comment by mikemcquaid** [comment]
What's the advantage of `brew-gem` over a `Gemfile`? I'm hesitant to support this given that `Gemfile`s do a much better job here.

**Comment by bretmogilefsky** [comment]
My understanding is that by using brew-gem, gems are installed in the Cellar and are much more self-contained than they would be if installed via gem directly. I would regard supporting brew-gem in a Brewfile as analogous to supporting homebrew-cask.

**Comment by mikemcquaid** [comment]
I think we'll pass on this as out-of-scope, sorry!
