### ISSUE TITLE
Support `head: true` as an option in the DSL

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#1042]
The `Brewfile` concept is great, and I use it always.

One thing I keep hitting is that certain OSS softwares are so actively maintained, and they also ask users to test the unreleased version. For such cases, I would like to request an option to be supported from the `Brewfile`. For eg:
`brew 'colima', head: true`

This should perform the same as: `brew install --head colima`

Is it possible to support this?

**Comment by jacobbednarz** [comment]
I’m away from my installation at the moment but could you try `args: { head: true }` and see if it works?

**Comment by vraravam** [comment]
Thanks for the quick response @jacobbednarz . But, no luck. It just resulted in a usage / help output and the `brew bundle` command exited with an error.

**Comment by gromgit** [comment]
Did you try the other alternative? As @jacobbednarz said, `args: { head: true }` is for casks.
```
brew 'colima', args: ["head"]
```

**Comment by vraravam** [comment]
Thanks - I didn't notice the differentiation between forumulae vs casks when I tried it. This works now!
```ruby
brew 'colima', args: ['head']
```

This is what `colima version` returns:
```bash
colima version HEAD-5090a0a
git commit: 5090a0aee5e6da0fa7adf23d577cc9edcda5630a
```

Thanks a lot @jacobbednarz + @gromgit . Btw, 2 points that come to mind:
1. This isn't documented anywhere that I could find
2. Can these be made consistent?

Thanks for the quick help!

**Comment by gromgit** [comment]
> 1\. This isn't documented anywhere that I could find

See the examples in [the **Usage** section of the bundle README](https://github.com/Homebrew/homebrew-bundle#usage).

> 2\. Can these be made consistent?

Not sure what you mean here.

**Comment by vraravam** [comment]
> > 1. This isn't documented anywhere that I could find
> 
> See the examples in [the **Usage** section of the bundle README](https://github.com/Homebrew/homebrew-bundle#usage).
> 
I was searching for `head` - and couldn't find it in there. After the above conversation, I can find a parallel with `with-rmtp`, but it was not evident at first glance.

> > 2. Can these be made consistent?
> 
> Not sure what you mean here.

I meant the difference in syntax between whether its a `cask` or not.

**Comment by jacobbednarz** [comment]
1. we don’t (and cannot) document every flag as most of them are formula dependent. I don’t really see a reason to add a HEAD install example here given the approach is already documented. 

2. unlikely at the moment, it would be a breaking change for users and IIRC, the parameter/flag handling differ between brew and cask so it needed to be different. would need to check the internals to see if it’s viable.
