### ISSUE TITLE
`brew bundle check` gives opaque error message when using an alias

### ISSUE THREAD

**Issue by andrewmwhite** [Homebrew/homebrew-bundle#105]
Running `brew bundle check` with `brew 'zmq'` in my Brewfile results in: 

    brew bundle can't satisfy your Brewfile's dependencies.
    Install missing dependencies with `brew bundle install`.

Running `brew bundle install` succeeds with no errors, but the error message still shows when running `check`. Replacing 'zmq' with 'zeromq' in the `Brewfile` fixes the problem.

Took me a few minutes to figure out what the problem was, so if supporting aliases isn't an easy fix, I'd suggest a more specific error message when one is included in a Brewfile.

**Comment by dunn** [comment]
There's some related discussion in #103.

**Comment by mikemcquaid** [comment]
Fixed by #116.
