### ISSUE TITLE
brew bundle uninstall <Brewfile>?

### ISSUE THREAD

**Issue by apiri** [Homebrew/homebrew-bundle#1050]
Not an issue, but a possible feature request.

I would like to accomplish "per environment" bundle Brewfiles that I may be working on at a given time; a unique set of dependencies for working with each language ecosystem. If these are not in use, I'd like to use that same Brewfile to remove these dependencies with the primary intent of avoiding updates for packages not in use on my system.  

Based on what's provided, I can only think of using the global Brewfile as my base state and performing a `brew bundle cleanup --global`. However, this would not work for a state composed of several "ecosystem" Brewfiles (A & B). 

Is there a way to accomplish this I am overlooking? Is this a misuse of bundles? I do realize there are challenges such as a package existing in more than one ecosystem (A & B) and removing one ecosystem (B) such that the remaining ecosystem state (A) is now "broken"/incomplete.

My initial thought was making a utility to do this akin to how docker-compose works for multiple compose files, merging them to establish a "current" global file, which would allow me to tap into `brew bundle --cleanup`.

This would roughly use the sequence of:

```shell
# Starting state has Base, Java, Rust, PHP

build-global base.Brewfile java.Brewfile rust.Brewfile
brew bundle --cleanup --global

# Unique PHP environment dependencies removed
```

**Comment by jacobbednarz** [comment]
while not "natively" supported, this already works as the `Brewfile` is just Ruby. 

check out https://github.com/jacobbednarz/j/blob/main/config/homebrew/Brewfile#L255 for an example. 

personally, i wouldn't be doing what you're trying to do with Homebrew due to the global nature of the installatioons. a tool like containers or VMs are a much better fit for this type of work.

**Comment by apiri** [comment]
Thanks for the pointer, @jacobbednarz! This will allow me to concoct what I'm looking for.  The word environment may portray a different situation but VMs are heavier than needs for this use.
