### ISSUE TITLE
Execute own shell commands

### ISSUE THREAD

**Issue by thedustin** [Homebrew/homebrew-bundle#1051]
Hey, 

I'm just wondering if there is a way to execute your own shell commands in the Brewfile. I would like to use it to install some php extensions during the installation of the bundle:

```ruby
brew "php@7.4", link: true
system "/usr/local/opt/php@7.4/bin/pecl install mongodb"
```

Using `system` executes the command immediate and not after installing php, and I didn't found any fitting entries in the [DSL](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/dsl.rb), or in the documentation/readme.

Thank you for your help.

**Comment by MikeMcQuaid** [comment]
There's no support in the DSL for this, sorry, and no plans to add it.

**Comment by SMillerDev** [comment]
You might be interested in https://github.com/shivammathur/homebrew-extensions as an alternative to your PECL approach though (since PECL is deprecated)

**Comment by danielbayley** [comment]
@thedustin You could drop in an `at_exit` block… Something like:
~~~ rb
brew "php@7.4", link: true
at_exit do
  system "/usr/local/opt/php@7.4/bin/pecl install mongodb"
end
~~~
