### ISSUE TITLE
Other plugins?

### ISSUE THREAD

**Issue by ameeno** [Homebrew/homebrew-bundle#1052]
Is it possible to add more plugins?

Such as ASDF or Pip?

I mean bundle is great if I install everything via homebrew. But for dev stuff, there are better tools like nvm, asdf and others.

COuld it be possible to write custom plugins for a bundle to keep track of?

**Comment by SMillerDev** [comment]
Yes it is, go ahead.

**Comment by MikeMcQuaid** [comment]
I'd likely be resistant to other plugins being added which don't have wide usage.
