### ISSUE TITLE
Should we commit Brewfile.lock.json to git?

### ISSUE THREAD

**Issue by larsblumberg** [Homebrew/homebrew-bundle#1057]
Hi!

We use a Brewfile for our project to install required build dependencies. Committing the Brewfile.lock.json could help every developer to use the same tool version, good. I however noticed that the lock file contains my personal system settings at the end:

```
  ...
  "system": {
    "linux": {
      "Pop!_OS 21.04 (hirsute)": {
        "HOMEBREW_VERSION": "3.3.14",
        "HOMEBREW_PREFIX": "/home/linuxbrew/.linuxbrew",
        "Homebrew/linuxbrew-core": "12ebed8de2f5b632324197381f4bd28d8bf56c62",
        "GCC": "10.3.0"
      }
    }
  }
```

Why is this? Will the lock file still work on other systems? Will other systems simply add their configuration to the `"system"` section?

**Comment by MikeMcQuaid** [comment]
> Committing the Brewfile.lock.json could help every developer to use the same tool version, good.

No, not really, unfortunately. It will can you identify when they aren't, though, and it's only read on failures.

> Why is this?

None of these seem specific to your machine.



> Will the lock file still work on other systems?

In terms of "detecting variations of configuration on failure": yes.

> Will other systems simply add their configuration to the `"system"` section?

I think so but cannot remember the exact implementation.

**Comment by larsblumberg** [comment]
Thanks for your answers. Unfortunately I'm not able to conclude in what situations we will benefit from keeping the lock file in a git repo.
