### ISSUE TITLE
Argument for specifying dump location

### ISSUE THREAD

**Issue by DestroyerXyz** [Homebrew/homebrew-bundle#1061]
An argument for specifying where to dump the Brewfile. Maybe the existing `--file` flag.

**Comment by DestroyerXyz** [comment]
Oh, I got a little confused. Turns out it doesn't work if you only give it the folder path, you have to include the file name. It also doesn't autocomplete paths after typing the `--file` argument.

**Comment by jacobbednarz** [comment]
Yep, you need to pass the full file path you wish to use.
