### ISSUE TITLE
Add support for --force-auto-update flag for taps

### ISSUE THREAD

**Issue by wburningham** [Homebrew/homebrew-bundle#1063]
I could just be missing documentation, but I couldn't see a way to run 
```
brew tap --force-auto-update user/tap-repo https://user@bitbucket.org/user/homebrew-tap-repo.git
```

using a Brewfile. Does a way exist or does the feature need to be added?

**Comment by MikeMcQuaid** [comment]
No, we don't support this. I'd want to see more than one person need it before we add a dedicated DSL for it but we could consider allowing arbitrary `args:` like we do with at least Casks.

**Comment by wburningham** [comment]
I think the arbitrary args support would be sufficient. That would also allow a brew bundle dump to preserve the force-auto-update value that is stored in git.
