### ISSUE TITLE
Whalebrew support requires docker to be running

### ISSUE THREAD

**Issue by vishvish** [Homebrew/homebrew-bundle#1070]
There's a little paradox here - using Whalebrew in a brewfile requires docker to be running - but this is also installed with the brewfile. I'm not sure how to get around this issue with the tools as supplied, as I cannot find a mechanism to install AND start/open a cask.

Happy to come up with a solution or PR if this method doesn't really exist, but I would like to know if anyone has figured out a clean, idempotent method to do this.

**Comment by jacobbednarz** [comment]
the need for Docker as a part of the install seems new since I last did a full install; I would add it as a dependency at https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/whalebrew.rb
