### ISSUE TITLE
'brew bundle' stuck on packages with licenses.

### ISSUE THREAD

**Issue by jkachmar** [Homebrew/homebrew-bundle#1074]
This is (effectively) a dupe of https://github.com/Homebrew/homebrew-bundle/issues/604.

---

Given the following `Brewfile`:
```
tap "microsoft/mssql-release", "https://github.com/microsoft/homebrew-mssql-release"
brew "mssql-tools"
```
...`brew bundle install` hangs indefinitely until it's killed, at which point it displays captured shell output prompting the user to accept or reject the EULA.

As pointed out in https://github.com/Homebrew/homebrew-bundle/issues/604#issuecomment-571151056, one needs to not only provide `ACCEPT_EULA=y`, but also `HOMEBREW_NO_ENV_FILTERING=1` to the environment for this to succeed.

**However** when one does this, `brew bundle` prints the following error several times:
```
Warning: HOMEBREW_NO_ENV_FILTERING is undocumented, deprecated and will be removed in a future Homebrew release (because it breaks many things)!
```
...which implies that there should either be a better way of providing environment variables to specific brews **or** the `microsoft/mssql-release` tap should be updated appropriately so that it may be installed with `brew bundle` in a compatible fashion.

**Comment by MikeMcQuaid** [comment]
> This is (effectively) a dupe of #604.

Please don't knowingly create dupes.

> the `microsoft/mssql-release` tap should be updated appropriately so that it may be installed with `brew bundle` in a compatible fashion.

Yes, as I said last time.

**Comment by jkachmar** [comment]
I would have commented on that issue were the discussion not locked.

In the future, what's the right way to go about requesting clarification on issues like this if the project would prefer that people not open potential duplicates and there is no clear avenue for continuing the old discussion?

**Comment by jkachmar** [comment]
There is a semi-active discussion about this on the MSSQL tap repository, for anyone else who finds themselves here and is uninformed (as I was).

cf. https://github.com/microsoft/homebrew-mssql-release/pull/26
