### ISSUE TITLE
brew bundle cleanup doesn't recognize fully spelled out brews

### ISSUE THREAD

**Issue by vruyr** [Homebrew/homebrew-bundle#1075]
When the Brewfile contains a line like `brew "homebrew/core/git"` instead of `brew "git"`, `brew bundle cleanup` suggests uninstalling it instead of recognizing that those are the same.

**Comment by MikeMcQuaid** [comment]
This format isn't supported for homebrew/core. Use `brew bundle dump` to see the supported format.
