### ISSUE TITLE
Support mas cleanup

### ISSUE THREAD

**Issue by jeromebaum** [Homebrew/homebrew-bundle#1077]
According to the [nix-darwin documentation](https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.masApps), `brew bundle` cannot currently clean up `mas` applications. Is this a design choice or a technical challenge? If a technical challenge, could you explain a bit more about what's tricky & whether you'd be open to a patch to fix this?

**Comment by MikeMcQuaid** [comment]
I think this was probably just never implemented. It's possible it doesn't work but we're definitely open to a PR to attempt implementation.

**Comment by issyl0** [comment]
This is not possible. Unless we want to try to fix `mas`. But by the looks of its README and the issues that I linked above, Apple has been slowly cutting off the APIs that `mas` uses and `mas cleanup` is going the same way. Shame, as I enjoyed working on that branch until I realised it was non-functional.

**Comment by jeromebaum** [comment]
I'm going to watch the relevant `mas` issues and open another issue if/when this gets fixed in `mas`. It does look like there is some hope - apparently there is a supported way to do this, though it is some effort.

Thanks for looking into it!

**Comment by issyl0** [comment]
@jeromebaum Thanks, sounds good. If you find it's fixed then please do ping here (or another issue), I did quite a bit of work here and I'd like to ship it the underlying behaviour is ever is fixed!
