### ISSUE TITLE
Add support for arbitrary args to tap

### ISSUE THREAD

**Issue by yacn** [Homebrew/homebrew-bundle#1079]
Related to https://github.com/Homebrew/homebrew-bundle/issues/1063, I need to specify `--force-auto-update` for a tap in my `Brewfile`, so either DSL for that option or arbitrary `args:` support like for casks is needed.

**Comment by marquiswang** [comment]
We decided to implement #1063 rather than arbitrary args, since it seems like there is no other argument to `brew tap` that would be used in a `Brewfile` right now. See conversation in #1084.
