### ISSUE TITLE
`brew bundle check` doesn't handle aliases when checking services

### ISSUE THREAD

**Issue by Tschrock** [Homebrew/homebrew-bundle#1081]
```rb
# Brewfile
brew 'postgres', restart_service: true
```

```
$ brew bundle install --verbose
Skipping install of postgres formula. It is already installed.
Using postgres
Restarting postgres service.
==> Successfully restarted `postgresql` (label: homebrew.mxcl.postgresql)
Homebrew Bundle complete! 1 Brewfile dependency now installed.
```

```
$ brew bundle check --verbose
brew bundle can't satisfy your Brewfile's dependencies.
→ Service postgres needs to be started.
Satisfy missing dependencies with `brew bundle install`.
```

```
$ brew services
Name       Status  User     File
postgresql started tschrock ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
```

Looks like it thinks the service is named `postgres`, when it's actually `postgresql`.
Changing 'postgres' to 'postgresql' in the Brewfile allows the check to pass.

**Comment by colindean** [comment]
What happens if you change `postgres` to `postgresql` in your Brewfile? The latter is the name of [the formula](https://formulae.brew.sh/formula/postgresql), not the former.

**Comment by Tschrock** [comment]
> What happens if you change `postgres` to `postgresql` in your Brewfile? The latter is the name of [the formula](https://formulae.brew.sh/formula/postgresql), not the former.

@colindean I mentioned that at the end:
> Changing 'postgres' to 'postgresql' in the Brewfile allows the check to pass.

Looking at the formula, you can see that `postgres` is an alias for `postgresql`. Using the canonical formula name in my Brewfile does work (that's what I'm doing currently). Since other parts of `bundle` seem to support aliases, I think it would be a good idea to support them here too.

**Comment by MikeMcQuaid** [comment]
`brew bundle` doesn't really support aliases at all, I'd recommend not using them in this way.

**Comment by MikeMcQuaid** [comment]
If you really, really want to still do so: we'll review a PR to adjust behaviour.
