### ISSUE TITLE
Feature request: brew bundle status

### ISSUE THREAD

**Issue by marquiswang** [Homebrew/homebrew-bundle#1085]
Could also be part of `brew bundle check --verbose`, but I'd like to be able to take a Brewfile and easily see whether the items in the Brewfile are missing, outdated, or up-to-date.

I would imagine it to look like:

```
$ brew bundle status --file path/to/Brewfile

Installed:
brew "git"
brew "subversion"
brew "python@3.9"

Outdated:
brew "the_silver_searcher"
brew "wget"
cask "docker"

Missing:
cask "iterm2"
```

I would also include 

```
# --porcelain: Give the output in an easy-to-parse format for scripts, akin to git status --porcelain
$ brew bundle status --porcelain --file path/to/Brewfile 

I brew "git"
I brew "subversion"
I brew "python@3.9"
O brew "the_silver_searcher"
O brew "wget"
O cask "docker"
M cask "iterm2"
```

**Comment by jacobbednarz** [comment]
for the purpose of checking whether the bundle is up to date, I use `check`

```
brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
```

I personally don't see any value in individual dependencies but rather as a whole (like above).

**Comment by colindean** [comment]
I agree with @jacobbednarz. I could be convinced otherwise.

I think without bounds could be adding some logging in the implementations of `Bundle::Checker::Base#installed_and_up_to_date?` e.g.

https://github.com/Homebrew/homebrew-bundle/blob/7664fe9b4f19181adf3aca634e3b66340a375b5d/lib/bundle/brew_checker.rb#L9-L11

That could have a log output. Additionally, the method(s) that method calls could return a state in `[:not_installed, :installed_and_updated, :installed_and_outdated]` and that gets output in the log line.

Adding the logging would be really low hanging fruit while additionally modifying the output would be more work, esp. adding and changing tests.

**Comment by MikeMcQuaid** [comment]
This feels like it would be better solved by `brew bundle check --verbose`.

Can you detail what your script using e.g. `--porcelain` might want to do? I'd see a `brew bundle check --json` or something to be useful for that.

**Comment by marquiswang** [comment]
```brew bundle check --json``` would also work fine for me. `porcelain` is inspired from `git`, which is formatted to be easy to parse with just `grep` and `cut`, but I see that `--json` is a bit more consistent with what we do elsewhere in Homebrew.

The use case for me is that I'm trying to build sets of recommended formulas/casks for developers at my organization, with different sets of recommendations depending on role. I think `brew bundle` is a great way to organize this. However, since these are just recommendations, it would be really nice to "diff" a bundle against what is already installed on your system and see what new stuff it will install.

**Comment by MikeMcQuaid** [comment]
> However, since these are just recommendations, it would be really nice to "diff" a bundle against what is already installed on your system and see what new stuff it will install.

Cool, that sounds desirable for `brew bundle check --verbose` to handle. Can you elaborate on what of the current output you find lacking?

**Comment by marquiswang** [comment]
```
$ brew bundle check --verbose --file /tmp/Brewfile
The Brewfile's dependencies are satisfied.

$ brew bundle check --verbose --file /tmp/Brewfile
brew bundle can't satisfy your Brewfile's dependencies.
→ Tap foo/bar needs to be tapped.
→ Cask abc needs to be installed or updated.
→ Formula xyz needs to be installed or updated.
```

I guess it would be sufficient for me to differentiate between "needs to be installed" and "needs to be updated".

For my purposes, I wish `--verbose` would also print out the things that *are* installed and up-to-date, but I can get that by just reading the Brewfile myself.

I also think it would be fairly reasonable change to list the missing items always in `brew bundle check`, and change `--verbose` to list the installed ones as well.

**Comment by MikeMcQuaid** [comment]
> I guess it would be sufficient for me to differentiate between "needs to be installed" and "needs to be updated".

Yeh, that seems like a valid thing to add 👍🏻 

> For my purposes, I wish `--verbose` would also print out the things that _are_ installed and up-to-date, but I can get that by just reading the Brewfile myself.

Or something like `--installed` could output them all too? I could even see an argument that maybe `--verbose` should just do this by default.

> I also think it would be fairly reasonable change to list the missing items always in `brew bundle check`, 

Nope, we intentionally don't output what's missing there so we can fail fast as soon as we find anything that's missing.

> and change `--verbose` to list the installed ones as well.

Yup!

**Comment by marquiswang** [comment]
I would propose this:

```
$ brew bundle check --verbose --file /tmp/Brewfile
brew bundle can't satisfy your Brewfile's dependencies.
→ Tap foo/bar needs to be tapped.
→ Cask abc needs to be installed.
→ Formula foo is installed.
→ Formula xyz needs to be updated.
```

Changes are:
* Outdated casks/formulas/mas/whalebrews say "needs to be updated"
* Missing casks/formulas/mas/whalebrews say "needs to be installed"
* Installed items say "is installed" instead of "needs to be installed/updated".
* No change to taps.

**Comment by MikeMcQuaid** [comment]
> * Outdated casks/formulas/mas/whalebrews say "needs to be updated"
> * Missing casks/formulas/mas/whalebrews say "needs to be installed"

👍🏻 unconditionally.

> * Installed items say "is installed" instead of "needs to be installed/updated".

Think we may want an `--installed` flag for this. @Homebrew/bundle any thoughts?

**Comment by jacobbednarz** [comment]
> Think we may want an --installed flag for this. https://github.com/orgs/Homebrew/teams/bundle any thoughts?

👍 sounds reasonable to me

**Comment by MikeMcQuaid** [comment]
@jacobbednarz To flip it round: do you think it's needed to have it instead of changing the default `--verbose` output? @colindean any thoughts?

**Comment by jacobbednarz** [comment]
i can see both flags being used but each with their trade offs. `--installed` is specific to this use case and allows to change without breaking a bunch of other things. `--verbose` could also be used but as @colindean mentioned, it can be _very_ long.

**Comment by MikeMcQuaid** [comment]
@marquiswang How about a PR to add just needs to be upgraded/installed and, if desired, a separate PR to add a `--installed` or `--all` or similar?
