### ISSUE TITLE
Feature request: Package version support (brew 3.4)

### ISSUE THREAD

**Issue by brandonrwin** [Homebrew/homebrew-bundle#1087]
It appears that getting/installing a specific packages version is maybe, somewhat indirectly, possible now? 

https://stackoverflow.com/a/66458452

The commands being:

>     brew extract --version=<version> <package> homebrew/cask
>     brew install <package>@<version>

**Comment by jacobbednarz** [comment]
this has been possible for a while, however, it's not intended to be a daily use thing nor do we support it. check out https://github.com/Homebrew/homebrew-bundle/issues/547#issuecomment-525443604 for some more discussion on the topic.
