### ISSUE TITLE
Having trouble with migrating Homebrew to M1 Mac using brew bundle

### ISSUE THREAD

**Issue by waldzwoelf** [Homebrew/homebrew-bundle#1088]
I recently got a new M1 MacBook. I set up the new one using a Time Machine Backup, so all my files and applications are present on the new one.
* I used the default installation method to install Homebrew to the default location for M1 machines in /opt/homebrew/bin. 
* Homebrew told me to use `brew bundle dump` and `brew bundle` to migrate everything from my old Homebrew setup to the new ARM Homebrew setup
* I ran `brew bundle dump` using the Intel version of Homebrew in /usr/local/bin/brew to generate a Brewfile with all my formulas and casks
* I used `brew bundle` using /opt/homebrew/bin/brew to install everything listed in the Brewfile
* Installation fails for every Cask that already has an App installed at */Applications/...*

I know, I have the Applications installed and can use them, but the new ARM Homebrew installation doesn't know that. I want to be able to upgrade and manage ~all my~ as many formulas and casks as possible using the ARM brew command. Running `brew list` with both versions shows, that there are a lot of casks missing in the new ARM Homebrew setup.
The only applications that were installed, are the ones I previously deleted (by deleting the .app file) but didn't remove using Homebrew. (--> still listed in the Brewfile, but successfully installing since there is no App at */Applications/...* yet)

## Installation failing

<img width="1543" alt="brew bundle install " src="https://user-images.githubusercontent.com/68006737/167379076-b5bb4ea4-271f-45f3-8a81-2c5fe2055a43.png">

<img width="1543" alt="bundle fail 1" src="https://user-images.githubusercontent.com/68006737/167379151-c446f492-b171-4319-a654-c1b9233b20fd.png">

### ARM Brew
<img width="1543" alt="arm brew list" src="https://user-images.githubusercontent.com/68006737/167379747-3ba8efe8-9abb-46f2-bd39-2e14e5701af4.png">

### Intel Brew
<img width="1543" alt="intel brew list" src="https://user-images.githubusercontent.com/68006737/167379835-44cfe9af-6174-4181-8b43-4a820d34853f.png">

Is this the wrong approach?
Do I need to un-install **all** my .app files first and run `brew bundle` again?
What am I missing ?
Thanks in advance.

**Comment by jacobbednarz** [comment]
using a time machine backup here may have introduced issues as they are not compatible across intel and Apple silicone. ideally, you should take the Brewfile (however you want to get that), drop it onto the new machine and then `brew bundle` from there for it to setup fresh. note: not all Homebrew packages have ARM variants so some may be missing. 

fwiw, I don't recommend ever restoring from a backup using Homebrew. it is much safer to install fresh on each machine to ensure the packages are installed correctly.

**Comment by waldzwoelf** [comment]
Thanks! 
I ended up running 
`/usr/local/bin/brew list --casks | xargs /opt/homebrew/bin/brew install --cask --force`
Which seems to have solved my problem so far 👍🏼
