### ISSUE TITLE
`brew bundle cleanup` doesn't actually clean anything up

### ISSUE THREAD

**Issue by CraigCottingham** [Homebrew/homebrew-bundle#1099]
macOS 12.4 on a MacBook Pro (16", 2021)
Homebrew 3.5.3
Homebrew/homebrew-core (git revision a0f71b75170; last commit 2022-07-04)

Running the command in the directory containing a `Brewfile`.

```
% brew bundle cleanup
Would uninstall formulae:
isl                 mpfr                libmpc              zstd                gcc                 sl
Would `brew cleanup`:
Would remove (empty directory): /opt/homebrew/etc/openssl@1.1/private
Would remove (empty directory): /opt/homebrew/etc/openssl@1.1/certs
```

As far as I can see, nothing in the system changes -- nothing is deleted.

**Comment by SMillerDev** [comment]
It's in the manpage, you need to use `--force` to actually clean.
