### ISSUE TITLE
"Snort" source link out of date

### ISSUE THREAD

**Issue by avalon-it** [Homebrew/homebrew-bundle#110]
Mac$ brew install snort
==> Downloading https://www.snort.org/downloads/snort/snort-2.9.7.3.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "snort"
Download failed: https://www.snort.org/downloads/snort/snort-2.9.7.3.tar.gz

The new path is:
https://www.snort.org/downloads/snort/snort-2.9.7.6.tar.gz

Can I customize the install process with new version number?

Regards

**Comment by DomT4** [comment]
> Can I customize the install process with new version number?

Afraid not. I've updated the upstream link though at Homebrew so `brew install snort` will succeed now.
