### ISSUE TITLE
Error: Unknown command: bundle

### ISSUE THREAD

**Issue by bklebe** [Homebrew/homebrew-bundle#1108]
I'm getting `Error: Unknown command: bundle` when trying to run `brew bundle` for the first time. Here's my `brew config` output:

```shell
% brew bundle
Error: Unknown command: bundle
% brew config       
HOMEBREW_VERSION: 3.5.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: f041a59af9daddc7c7afe8537e3858103f8f9ab9
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: be9206e2166e8ad7c4cf052ecab02ce2b1445a65
Core tap last commit: 46 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.37.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
```

**Comment by SMillerDev** [comment]
use `brew tap homebrew/bundle`

**Comment by bklebe** [comment]
Thank you!

**Comment by bklebe** [comment]
I may have done so, yes. I was cleaning up my unused taps a few weeks ago and didn't remember tapping it, so I probably assumed it wasn't needed. I didn't really understand that taps contained "core" Homebrew functionality, or I would have been more careful. I thought they were just for pulling packages from 3rd party repos. I don't explicitly remember untapping `homebrew/bundle` but it seems like the most likely explanation.

**Comment by colindean** [comment]
Thank you for that information!

**Comment by bklebe** [comment]
Happy to help! Thanks for working on Homebrew.
