### ISSUE TITLE
Brew Inability to Support Specific Versions and Consistent Installation Prefix Across Architectures and Platforms

### ISSUE THREAD

**Issue by cpolizzi** [Homebrew/homebrew-bundle#1110]
This fact that it is incapable of doing so is just yet another reason why brew is not a proper package manager at all. The answer here is not `brew-tap` with a specific set of commands and version references. The proper answer is **require formula / cask / bottle developers / submitters to properly version submissions and enforce governance of such.** Sure, `brew-tap` works (mostly) but results in a complete recompile. It is possible to perform compilations that are relative to needed dynamic libraries. It is also possible to create the necessary symbolic links where needed in the brew installation itself.

The problem can easily be solved through actual standardization, requirements and adherence to said requirements via quality checks. As a Homebrew user this type of governance is clearly missing. The projects' intended "behavior" is incorrect.

Considering the advent of the Apple silicon, the projects' "behavior" is also incorrect. The brew install location should always be the same, regardless of the "advice" of the steering committee. Do we see this problem with actual, real and solid package managers such as *dnf*, *yum*, *apt*, etc? No, we do not. This rationale is the same for adherence to proper package versioning.

Has this project ever considered the complexity of those that need to support Homebrew environments across thousands of developers within a single organization regarding versioning and host architecture? In my experience this is a resounding "no" as I have to make far too many accommodations for something in these respects that could easily be solved by your "project".

From your own https://github.com/Homebrew/brew/issues/9130 from the main brew project:
> Homebrew does not support installing specific versions of a library, only the most recent one, so there is no good mechanism for storing installed versions in a .lock file.
> 
> If your software needs specific versions then perhaps you'll want to look at using [Vagrant](https://vagrantup.com/) to better match your development and production environments.

This rationale is, among many others, why Homebrew is not an actual "missing package manager", from the core projects' main mantra is a joke, available at https://brew.sh/
> The Missing Package Manager for macOS (or Linux)

Sorry, but Linux has no "missing" package manager, regardless of distribution. At that point it is merely a function of "do I have root access" via any mechanism or not to install packages? Even then, for the majority of times, it is possible in an assortment of distributions to install new packages without root access of any kind; this is, however, dependent upon the specific Linux distribution package manager itself. Feeble-minded macOS is utterly missing any semblance of a package manager. In this, we can agree. But we cannot agree in the "brew" project highly opinionated statements and rationalizations for macOS when it comes to installation prefixes and again the utter lack of proper versioning.

And there have been numerous requests for this project to actually bring a consolidated and uniform installation prefix. Countless others have had to workaround due to this lack of clear and present lack of foresight and indeed willingness of the project to adapt and change to the community needs over time.

This fact that it is incapable of doing so is just yet another reason why brew is not a proper package manager at all. The answer here is not `brew-tap` with a specific set of commands and version references. The proper answer is **require formula / cask / bottle developers / submitters to properly version submissions and enforce governance of such.** 

The problem can easily be solved through actual standardization, requirements and adherence to said requirements via quality checks. As a Homebrew user this type of governance is clearly missing. The projects' intended "behavior" when framed in more recent years is incorrect.

Considering the advent of the Apple silicon, the projects' "behavior" is also incorrect. The brew install location should always be the same, regardless of the "advice" of the steering committee. Do we see this problem with actual, real and solid package managers such as *dnf*, *yum*, *apt*, etc? No, we do not. This rationale is the same for adherence to proper package versioning.

Has this project ever considered the complexity of those that need to support Homebrew environments across thousands of developers within a single organization regarding versioning and host architecture? In my experience this is a resounding "no" as I have to make far too many accommodations for something in these respects that could easily be solved by your "project".

From your own https://github.com/Homebrew/brew/issues/9130 from the main brew project:
> Homebrew does not support installing specific versions of a library, only the most recent one, so there is no good mechanism for storing installed versions in a .lock file.
> 
> If your software needs specific versions then perhaps you'll want to look at using [Vagrant](https://vagrantup.com/) to better match your development and production environments.

This rationale is, among many others, why Homebrew is not an actual "missing package manager", from the core projects' main mantra at https://brew.sh/
> The Missing Package Manager for macOS (or Linux)

Sorry, but Linux has no "missing" package manager.

And yes, it is entirely possible to create a Homebrew distribution that is 100% relocatable regardless of the core project approach. I do suggest that when you build packages that you reference Apple Developer documentation regarding the behavior of **dyld**.

**Comment by jacobbednarz** [comment]
Thanks for the issue but other than you dunking on the project, I don't see anything actionable here for maintainers since you've already mentioned multiple times that we intentionally don't support versioning of formulae.

If Homebrew doesn't suit your environment needs, you're welcome to use something else that you see fits.
