### ISSUE TITLE
brew bundle dump not including mas applications

### ISSUE THREAD

**Issue by kelbyers** [Homebrew/homebrew-bundle#1112]
When I run `brew bundle dump`, it is not including any App store applications, even though there are several that are listed using the `mas list` command.

```
➜ brew bundle dump --file=- | grep '^mas'
Running `brew update --auto-update`...

✘1 ➜ mas list
520993579   pwSafe                         (4.17)
409183694   Keynote                        (12.1)
408981434   iMovie                         (10.3.3)
1482920575  DuckDuckGo Privacy for Safari  (1.5.0)
414568915   Key Codes                      (2.2.1)
409201541   Pages                          (12.1)
1233965871  ScreenBrush                    (1.7.8)
1352778147  Bitwarden                      (2022.5.1)
937984704   Amphetamine                    (5.2.2)
409203825   Numbers                        (12.1)
1494210770  Tomato 2                       (2.3)

➜ PATH=/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin brew doctor
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
I cannot reproduce this I'm afraid. We're just calling `mas list` inside `brew bundle` so you'll need to figure out what's going on there.

**Comment by kelbyers** [comment]
Well, I tried several times. When I ran it again today, brew autoupdated and now the mas items are included.

**Comment by Rabter1** [comment]
I had the exact same issue right now. 
The mas installations where missing in the dump. 
but `mas list` was returning everything just fine.

I restarted the terminal and now it is working again. 
Not sure what caused the issue.
I am using the env **HOMEBREW_BUNDLE_FILE**

**Comment by roelfie** [comment]
Exact same issue here. I have a daily script, that exports all my installed Brew formulae/casks/mas (and commits the changes to GitHub). 

The command i'm executing is `brew bundle dump --force`. 

As you can see in [this commit history](https://github.com/roelfie/dotfiles/commits/main/Brewfile) about 50% of the times it is missing the mas applications. None of these commits were really needed, as the mas applications installed on my machine did not change. Brew bundle just didn't detect them 50% of the time.

Cool that you're calling `mas list` inside `brew bundle` but something's definitely not working properly there.

**Comment by MikeMcQuaid** [comment]
> Cool that you're calling `mas list` inside `brew bundle` but something's definitely not working properly there.

Until this has reproduction steps: there's nothing we can do here.

**Comment by Rabter1** [comment]
> Until this has reproduction steps: there's nothing we can do here.

@MikeMcQuaid 
Does my steps to reproduction not work for you?  (described [here](https://github.com/Homebrew/homebrew-bundle/issues/1112#issuecomment-1210557035))

**Comment by MikeMcQuaid** [comment]
@Rabter1 Nope.

**Comment by Rabter1** [comment]
I just tried to reproduce the error again with my method and indeed it does not work for me every time anymore.
#### But i noticed the following:
I am new to brew: But my understanding is, that if you didn't run a brew command for a while, brew automatically runs some updates before executing the command you actually typed.
(Most likely brew update)
I noticed, that the mas list is missing, in case brew is automatically updating before executing the `brew bundle dump` command. 

This is not confirmed and i don't know how to reproduce this behaviour except waiting a day until running the command again.
Can someone force this behaviour and confirm if this is causing the bug?

**Comment by roelfie** [comment]
This is the script I'm executing it from. I do indeed first run "brew update -q" (and some more brew stuff) : https://github.com/roelfie/dotfiles/blob/803a26512784046983e55983a6e5ab25ee25fae2/bookkeeper/bookkeeper.zsh#L93

And way down in the same script you will find a "brew bundle dump --force".

**Comment by Rabter1** [comment]
### I was able to reproduce today like this:

I first run `HOMEBREW_NO_AUTO_UPDATE=1 brew bundle dump --describe -f`
This command **included** the mas list
Right after that, i did run the same command but without the `NO_AUTO_UPDATE` flag. 
Like this: `brew bundle dump --describe -f`
Brew did update before executing the bundle command and **the mas list was missing**

Sadly it is only possible to reproduce, if this is the first brew command of the day and brew is actually updating i guess.

**Comment by MikeMcQuaid** [comment]
> I first run `HOMEBREW_NO_AUTO_UPDATE=1 brew bundle dump --describe -f`
> This command **included** the mas list
> Right after that, i did run the same command but without the `NO_AUTO_UPDATE` flag.
> Like this: `brew bundle dump --describe -f`
> Brew did update before executing the bundle command and **the mas list was missing**

I was able to reproduce this now, thanks for the instructions 👍🏻
