### ISSUE TITLE
brew bundle vs brew cask install: Apps on and off the App Store

### ISSUE THREAD

**Issue by kevinSuttle** [Homebrew/homebrew-bundle#112]
Steps to reproduce:

1. Install an app that is available both in the official App Store, and by the developer (preferably from the App Store for the purposes of this bug) 
2. Install homebrew-bundle
3. Install homebrew-cask
4. Create a Brewfile and list the app you chose in step 1. e.g. Skitch.

### Example
```bash
$ brew cask install skitch
Warning: A Cask for skitch is already installed. Add the "--force" option to force re-install.
```

**Brewfile**
`cask 'skitch'`

```bash
$ brew bundle
Succeeded in installing skitch
Success: 1 Fail: 0
```

**Comment by kevinSuttle** [comment]
Hm. I noticed that in the case of Skitch, the .app is linked to the `~/Applications` directory, so it wouldn't be overwriting the version installed to `/Applications`, anyway. Perhaps that's how homebrew-bundle is designed? Instead of overwriting, it just links to the $HOME directory?

**Comment by kevinSuttle** [comment]
Ah, yes, homebrew-cask symlinks into ~/Applications by default. 
`--appdir=/Applications` flag is needed to override.

**Comment by mikemcquaid** [comment]
Yep, that's a cask default we can't really tweak, sorry!

**Comment by muescha** [comment]
> we can't really tweak

but there are some solutions:

# 1) environment variable
you can set the appdir in an environment variable and then run brew bundle:

```ruby
# Specify your defaults in this environment variable
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/etc/Caskroom"
```

see [usage of options](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options) 


# 2) bundle dsl
but is not this command of `homebrew bundle` just for overriding the cask options?

```ruby
cask_args appdir: '/Applications'
```

**Comment by mikemcquaid** [comment]
@muescha Yep, those are both options you can use but Homebrew Bundle can't pick one automatically. Thanks!

**Comment by kevinSuttle** [comment]
Why can't the environment variable default to `/Applications`?

**Comment by mikemcquaid** [comment]
@kevinSuttle We defer to Cask's default/configuration here.
