### ISSUE TITLE
macOS gatekeeper quarantine

### ISSUE THREAD

**Issue by iamtodor** [Homebrew/homebrew-bundle#1128]
Hello,
This is a follow-up issue to https://github.com/Homebrew/homebrew-bundle/issues/474 

Could you please keep it open until the possible solution will be implemented?

**Comment by SMillerDev** [comment]
If you'll be implementing it we can keep a pull request open. If you won't be implementing it then I see no value in keeping an issue for it.

**Comment by iamtodor** [comment]
@SMillerDev, you don't see a reason to keep this issue open to be transparent about feature requests? To track that people would like to have it? That's why you simply close it as `completed`?

**Comment by iamtodor** [comment]
@SMillerDev the same way this https://github.com/Homebrew/homebrew-bundle/issues/1062 issue with feature request is being tracked

**Comment by SMillerDev** [comment]
That's because someone is working on that feature request with a pull request. It's really simple: only feature requests that someone works on stay open.

**Comment by iamtodor** [comment]
@SMillerDev personally, I'm not a pro in ruby or bash scripting, however, I think it would be nice to keep the feature request open for two reasons:
- you can check how much the community is waiting for the feature to be implemented
- your potential experienced contributors who just opened this repo for themselves could find the issues that are waiting to be implemented

These are the reasons I found reasonable in the open-source community so far. For instance, airbyte tracks a lot of issues https://github.com/airbytehq/airbyte/issues and labels them in order to categorize it.

How does it sound to you? Does it make sense?

**Comment by SMillerDev** [comment]
> you can check how much the community is waiting for the feature to be implemented

We can check that by the amount of pull requests made for it

> your potential experienced contributors who just opened this repo for themselves could find the issues that are waiting to be implemented

In the roughly 5 years I've been maintainer of Homebrew I've never seen this happen. People fix issues they find annoying, not issues they find in the issue list.

> For instance, airbyte tracks a lot of issues (2800+) https://github.com/airbytehq/airbyte/issues and labels them in order to categorize it.

That's good for them, but Homebrew's policy is that feature requests should be made as pull requests.

**Comment by iamtodor** [comment]
@SMillerDev got you, thank you the clarification and sorry for bothering then :)
