### ISSUE TITLE
bug: Error: 416: unexpected token at '"libpng'

### ISSUE THREAD

**Issue by treeshateorcs** [Homebrew/homebrew-bundle#1139]
1. install homebrew per the instruction on brew.sh (bash -c... etc)
2. add `export HOMEBREW_INSTALL_FROM_API=1` to .zprofile
3. uninstall homebrew (`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"`)
4. sudo rm -rf /opt/homebrew
5. install homebrew 
6. cd Documents (where the Brewfile is located) && brew bundle install
7. in the middle of the process remember that there are unneeded (after setting HOMEBREW_INSTALL_FROM_API) taps in the list
8. remove from the top of Brewfile 
```
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
```
9. none of the taps left (actually i think i left out /bundle and /cask-fonts, not sure)
10. uninstall brew && install brew
11. cd Documents && brew bundle install

```
==> Tapping homebrew/bundle
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 6844, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 6844 (delta 20), reused 32 (delta 12), pack-reused 6797
Receiving objects: 100% (6844/6844), 1.60 MiB | 333.00 KiB/s, done.
Resolving deltas: 100% (3986/3986), done.
Tapped 1 command (98 files, 2.0MB).
Using homebrew/bundle
Tapping homebrew/cask-fonts
Error: 416: unexpected token at '"libpng'
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/opt/homebrew/Library/Homebrew/api/formula.rb:38:in `all_formulae'
/opt/homebrew/Library/Homebrew/formulary.rb:678:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Homebrew/formula.rb:1917:in `[]'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:43:in `formulae_by_full_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/skipper.rb:12:in `skip?'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:37:in `block in install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by jacobbednarz** [comment]
i'm really struggling to follow your reproduction. can you re-word it to clarify the points a little more? on first glance, this looks more to be related to a local issue (install/cleanup failure) as opposed to one with bundle itself.

**Comment by treeshateorcs** [comment]
i've made some corrections. what points would you like me to clarify further?

there is a message that says

```
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
```

so i followed the link and reported this bug 🙂

**Comment by jacobbednarz** [comment]
i'm not following:

- why you are installing and uninstalling brew multiple times; and 
- why you are interrupting the bundle process. 

this seems like a recipe for problems. I would recommend that you start with a clean install, remove any bundle files that you have previously created and start again to reproduce with a minimal test case. 

the error reporting is shown if for any reason the tool hits unhandled exceptions (including if the user gets it into a weird state). 

fwiw, installing from the API for all the formula you mentioned works fine for me so i'm leaning even further into this being a local issue.

**Comment by MikeMcQuaid** [comment]
> this seems like a recipe for problems. I would recommend that you start with a clean install, remove any bundle files that you have previously created and start again to reproduce with a minimal test case.

> fwiw, installing from the API for all the formula you mentioned works fine for me so i'm leaning even further into this being a local issue.

Agreed.
