### ISSUE TITLE
How to specify in Brewfile that homebrew should first update itself and any currently installed packages?

### ISSUE THREAD

**Issue by jeffwidman** [Homebrew/homebrew-bundle#114]
I'm converting my `Brewfile` from the [old format](https://github.com/Homebrew/homebrew/issues/32952). 

At the top of my old `Brewfile`, I had:
```
update # Sync the git repo
upgrade # Upgrade already-installed formulae
```

and at the bottom I had:
```
cleanup # Remove outdated versions from the cellar
```

How do I handle these tasks in the new `Brewfile` format?

**Comment by mikemcquaid** [comment]
`update` and `cleanup` need run manually but `upgrade` is run by default for everything inside the `Brewfile`.

**Comment by jeffwidman** [comment]
Thanks!
