### ISSUE TITLE
Feature request: rename "Brewfile.lock.json" to something else

### ISSUE THREAD

**Issue by hlung** [Homebrew/homebrew-bundle#1145]
From https://github.com/Homebrew/homebrew-bundle/pull/552 , it seems that the lock file, by design, doesn't work like a lock file in other dependency management tools where it helps _lock_ installed versions for other machines, but rather just holds "logs" of which versions were installed successfully. 

While I understand the good intentions behind it (to not lock some dependency to some version forever) and the technical limitations, I think it still causes lots of confusions for new comers.

As said, should we rename it to something else other than "Brewfile.lock.json" to avoid confusion? Something like "Brewfile.logs.json".

PS. I'm new here and not sure if there's some feature request format here. Let me know and I can update.

**Comment by jacobbednarz** [comment]
thanks for the suggestion however, this _is_ a type of lock file so I wouldn't want to change it solely based on that. I think the mistake people are making is assuming all lock files are the same and dictate the restraints of an installed package (as you outlined) whereas there other types that exist too.

I could entertain renaming this functionality to be a "state" file instead but I don't feel strongly enough about this. 

@colindean @MikeMcQuaid thoughts?

**Comment by hlung** [comment]
Interesting. I'd be interested in learning more on the history of lock files haha.

**Comment by MikeMcQuaid** [comment]
> As said, should we rename it to something else other than "Brewfile.lock.json" to avoid confusion? Something like "Brewfile.logs.json".

Sorry, no, don't want to break backwards compatibility here.

**Comment by hlung** [comment]
@MikeMcQuaid It doesn't have to break backward compatibility. The program can look for "Brewfile.logs.json" first and fall back to "Brewfile.lock.json".

@jacobbednarz I'm curious. is there any other tools that treat lock file like in homebrew? I only work with Gemfile.lock and Podfile.lock and they seems to help restraint versions.

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid It doesn't have to break backward compatibility. The program can look for "Brewfile.logs.json" first and fall back to "Brewfile.lock.json".

Sure, it could, I just don't see the benefits being compelling enough to warrant it.

> I only work with Gemfile.lock and Podfile.lock and they seems to help restraint versions.

These tools work completely differently to Homebrew to the extent that they are not worth comparing in this way.

**Comment by hlung** [comment]
> These tools work completely differently to Homebrew to the extent that they are not worth comparing in this way.
 
What other tools work similar to homebrew then?

**Comment by MikeMcQuaid** [comment]
> What other tools work similar to homebrew then?

@hlung Nothing that also has something like `brew bundle`.
