### ISSUE TITLE
Feature request: do not overwrite links of dependencies

### ISSUE THREAD

**Issue by pereorga** [Homebrew/homebrew-bundle#1150]
I have the following Brewfile on Ubuntu, because these packages do not exist on apt-get, or because I need a newer version (in the case of npm/nodejs):

```
brew "hadolint"
brew "nodejs"
brew "npm"
brew "oxipng"
brew "shfmt"
```

This works fine. The problem is that when running `brew bundle install` it also installs the following dependencies, replacing the links to the existing Ubuntu binaries:

```
bizon brotli bzip2 sqlite unzip xz
```

At least on Linux, I would say the ideal behavior would be to not replace existing links of these packages. IMHO, ideally, links should be created only if they do not exist.

I'm currently doing the following, but wondering if there is a better way to handle this:

```
brew unlink bizon brotli bzip2 sqlite unzip xz
```

**Comment by MikeMcQuaid** [comment]
Specify those packages specifically with `, link: false`. We won't be changing the default behaviour here.
