### ISSUE TITLE
Support `--no-quarantine` flag

### ISSUE THREAD

**Issue by lougreenwood** [Homebrew/homebrew-bundle#1155]
Brew now has the `--no-quarantine` flag, but it seems that `bundle` doesn't support this.

I've found a weird behaviour where certain apps which I install with `brew bundle` (and possibly `brew`, I didn't test this yet) just don't open at launch when they are added to the login items. (For extra context if anyone is curious, I install my apps from `brew` as an `admin` user, but my day-to-day user is not admin. However, I see the issue in both the admin & standard user).

I did some tests, removing these apps & manually installing them from their respective upstream allows the app to launch correctly at login, if I then reinstall those apps using `brew install --no-quarantine` they also launch at login. Additionally, other apps which have this issue but which I didn't test manually installing from upstream also get fixed if I run `brew install --no-quarantine --force`.

To continue my effort to test if `--no-quarantine` is the solution and if there is some issue with home-brew, I wanted to nuke my installed brew apps, reinstall everything from my `Brewfile` with `--no-quarantine` and see if it fixed the issue (and if so, create an issue on the main `brew` GitHub project). But now I see that there is no `brew install --no-quarantine`.

I also found [this](https://github.com/Homebrew/homebrew-bundle/issues/474) issue from 2019 which also requested it.

Maybe a more general solution is for `bundle` to pass through all **unknown** flags. That would at least keep bundle compatible with future versions of `brew` (seemingly) without any breaking changes to bundle?

**Comment by MikeMcQuaid** [comment]
> but it seems that `bundle` doesn't support this

Have you tried using `args:` specified to the Cask? That should work.

> Maybe a more general solution is for `bundle` to pass through all **unknown** flags.

No, definitely not, sorry.

---

We don't want to support all possible options through Homebrew. I personally particularly do not want to support globally disabling a security feature like this. 

Passing on this, sorry. Happy to continue to talk about `args`: here.

**Comment by lougreenwood** [comment]
Thanks!

> Have you tried using args: specified to the Cask? That should work.

No, I didn't - so this would look something like the following, correct? (I'm not sure on the casing to use for kebab-case args or if it accepts a boolean value to use for an arg which doesn't receive a value for the command)

```
cask "firefox", args: { noQuarantine: true }
```

**Comment by MikeMcQuaid** [comment]
> No, I didn't - so this would look something like the following, correct? (I'm not sure on the casing to use for kebab-case args or if it accepts a boolean value to use for an arg which doesn't receive a value for the command)

I'm not sure off the top of my head, sorry. May be better asking in Homebrew/discussions or playing around in the code.

**Comment by gromgit** [comment]
https://github.com/Homebrew/homebrew-bundle/issues/940#issuecomment-808334576
```
cask "firefox", args: { no_quarantine: true }
```

**Comment by MikeMcQuaid** [comment]
@gromgit worth putting this in the README, what do you think? I'm somewhat loathe to point out how to disable a security feature but if multiple people want it...

**Comment by colindean** [comment]
@lougreenwood can you list some of the affected apps?

My thought is that if there is a class of apps that must have that no_quarantine flag passed in order to operate properly, that should be defined in the formula or cask definition, which refuses to install upon install request if it needs to have no_quarantine for proper operation. Upon failing to provide it, something could tell the user where to look for more information about why the security feature must be disabled for installation.

**Comment by lougreenwood** [comment]
@colindean Sure, the apps that are affected for me are the following:

- Raycast
- Amethyst
- Kindavim
- Wooshy
- Scrolla
- Bartender

Maybe some others too. I'm going to do some more investigations before I come to the conclusion that the problem is quarantine, but it seems that so far apps which are installed with brew bundle won't launch on startup, but if I reinstall with `brew install --force --no-quarantine` it will launch at startup.

My next step is to uninstall all of brew & apps, create a new user and try to replicate with a plain `brew install` for one of the affected apps and try to get a simple reproduction...
