### ISSUE TITLE
Support for whitelisting dependency-only installs in `brew bundle`

### ISSUE THREAD

**Issue by jaminthorns** [Homebrew/homebrew-bundle#1162]
I use Homebrew to install dependencies for some programs that I compile from source, and I specify those in my `Brewfile` like this:

```ruby
brew "erlang", args: ["only-dependencies"]
brew "postgresql@14", args: ["only-dependencies"]
```

Which works great, but when running `brew bundle --cleanup`, the dependencies for `erlang` and `postgresql@14` get uninstalled. I can easily remedy this by running `brew bundle` afterwards, which will reinstall those dependencies, but it would be nice if I didn't have to do that.

**Comment by colindean** [comment]
I do this, too, but for the python formula. I don't run `brew bundle --cleanup`, though, ever (it runs `brew bundle cleanup --force` after `brew bundle`). I work in too many projects with dissimilar environments… I'd spend a lot of time (re|un)installing.

**Comment by jacobbednarz** [comment]
this is a `brew` behaviour, not bundle so you can add (unsupported) `args: ["--ignore-dependencies"]` to the formula themselves and explicitly call out your dependencies. iirc, this will work in reverse and only remove the formula but not the dependencies.

**Comment by MikeMcQuaid** [comment]
The supported solution for this is to just install these dependencies explicitly and then use `brew bundle dump` to keep them in your `Brewfile`. Passing on this given this and above workarounds, sorry!
