### ISSUE TITLE
Locking step fails with "Error: No available tap homebrew/core." if homebrew/core isn't tapped.

### ISSUE THREAD

**Issue by faisal** [Homebrew/homebrew-bundle#1169]
Bundling fails in lockfile generation when using brew 4 with homebrew/core untapped.

Steps:

1. `brew update` to 4.0 or later.
2. `brew untap homebrew/core`
3. `brew bundle`

Expected behavior: Homebrew completes the bundling process.

Actual behavior: Homebrew goes through the bundling process but fails in locking, reporting "Error: No available tap homebrew/core."

Notes:
- It looks like Bundle::Locker#system_macos's interaction with CoreTap assumes homebrew/core is tapped.
- Running `brew bundle --no-lock` succeeds.
- Removing the `"Homebrew/homebrew-core" => CoreTap.instance.git_head,` line from Bundle::Locker#system_macos allows the bundle to proceed for this case, but presumably would do the wrong thing if homebrew/core _is_ tapped.

**Comment by colindean** [comment]
I'm not able to reproduce this immediately. 

I'm on `HOMEBREW_VERSION: 4.0.1-58-g82a36d2` on Linux (Debian 11.6) and just today updated to 4.x and untapped homebrew/core. I'm able to run brew bundle with a variety of Brewfiles I have laying around.

Can you provide the output of:

* `brew config`
* `brew doctor`

**Comment by colindean** [comment]
I just caught that I have lockfiles disabled on this machine. I'm able to reproduce it now.

```
unset HOMEBREW_BUNDLE_NO_LOCK; brew bundle --file=Brewfile.all                                                                                                                
Using colindean/personal
Using bash
Using bash-completion@2
Using bat
Using git-delta
Using coreutils
Using eoconv
Using fzf
Using zoxide
Error: No available tap homebrew/core.
```

**Comment by colindean** [comment]
The quick workaround is to use `--no-lock` or set `export HOMEBREW_BUNDLE_NO_LOCK=1`.
