### ISSUE TITLE
Docs on .lock file?

### ISSUE THREAD

**Issue by jrochkind** [Homebrew/homebrew-bundle#1182]
I'm trying out `brew bundle` for the first time. 

The README definitely says:

> Homebrew does not support installing specific versions of a library, only the most recent one, so there is no good mechanism for storing installed versions in a .lock file.

And yet, after I ran `brew bundle`, I definitely got a `Brewfile.lock.json` created. 

Are there any docs available on how this works and is intended to be treated?  

Because of the caveat in the README that I quoted, I am very curious what happens if you try to brew bundle using the lockfile when it specifies versions that are no longer the most recent in homebrew, among other questions. 

I am not sure if we are suggested to check Brewfile.lock.json into version control, or what it does exactly. 

Should these things be doc'd in README?

**Comment by jacobbednarz** [comment]
> And yet, after I ran `brew bundle`, I definitely got a `Brewfile.lock.json` created.

are you able to elaborate on your question here? you're correct that a lock file is created but it's not a source of truth for versions. see #1057 for some more details.

> Are there any docs available on how this works and is intended to be treated?
> I am not sure if we are suggested to check Brewfile.lock.json into version control, or what it does exactly.

there are no docs (since it's not a source of truth) however, the issue tracker has some previously discussed issues on this topic. see #1145, #547 and #802.

> Because of the caveat in the README that I quoted, I am very curious what happens if you try to brew bundle using the lockfile when it specifies versions that are no longer the most recent in homebrew, among other questions.

`brew bundle` doesn't do anything however, i assume `brew` would fallback to the latest it has available if a newer version has been yanked.

**Comment by jrochkind** [comment]
> are you able to elaborate on your question here? 

That's my question -- what does the Brewfile.lock.json do, what's it for, how are we recommended to use it?

I'm confused that you wouldn't want to put documentation in the README that the `Brewfile.lock.json` is created, and what it does or is for. Like a couple sentences or such. 

But it's your project, up to you! I will check out those issues, thanks. Thanks for the project, it is useful!

**Comment by MikeMcQuaid** [comment]
> Why might we want to do that or not do it?

I can't speak too much to that but personally: I created this file and I don't check it in.



> I'm confused that you wouldn't want to put documentation in the README to answer those questions.

I'm game to add something short to the README for this.

> What is it meant to do, why does it exist, what does `brew bundle` use it for?

It's used to debug failures. If `brew bundle` has worked previously and fails now: it'll use the differences in the lock file to help you figure out what's changed and therefore a potential cause of issues. Similarly, you can compare these across a team if some members have success and some members have failures with the same `Brewfile`.

Does that help at all?

How about this: let's talk here until your questions are addressed (I'm happy to help answer questions) and, once you feel like you have the answers you were originally looking for: you can add them to the README and/or `man brew` output.

**Comment by jrochkind** [comment]
OK, thanks I read the Issues you mentioned, and a few other relevant ones I found including the original #552 as well as #1057 and a few others. 

I took a stab at a PR to do cin README in #1183.  

I have to admit.... after reading all of this and wrapping my head around it... I still don't really understand the use of this file, and am not seeing much evidence that otheres do either. I wish that it were off by default, and only generated if you turned it on with an ENV or command-line arg.  But after reading all of this, I also see that your mind is pretty made up and you aren't really interested in feedback, so that's up to you!

**Comment by MikeMcQuaid** [comment]
> But after reading all of this, I also see that your mind is pretty made up and you aren't really interested in feedback, so that's up to you!

We're always interested in feedback, we might just not do what's suggested but come up with our own solutions.

We're talking more about how to improve or change behaviour based on your feedback so: thanks.

> I like having it in the README so they can find out more easily.

Agreed, thanks for the PR 🙇🏻
