### ISSUE TITLE
Request to add `postInstall` option

### ISSUE THREAD

**Issue by kopach** [Homebrew/homebrew-bundle#1190]
Hello
Currently, the tool lacks a `postInstall` option, which can be inconvenient when installing packages that require additional setup steps.

For instance, some packages like https://github.com/junegunn/fzf#using-homebrew require running a script after installation to fully install everything. This is currently not possible with Brew Bundle, and I believe that adding a `postInstall` option would greatly improve the user experience.

I came across some past requests on this topic (https://github.com/Homebrew/homebrew-bundle/issues/181 and https://github.com/Homebrew/homebrew-bundle/issues/450), but they have since been closed, and I am unable to comment on them. Hence, I am creating this issue to request that a `postInstall` option be added to Brew Bundle.

I understand that you may have other priorities or vision on this project, but I believe that this feature would greatly benefit users of the tool and make it even more useful. Please let me know your thoughts on this, and if there is anything I can do to help here

**Comment by colindean** [comment]
While I can see the tempting utility of it, this pattern is best off left to scripts that call `brew bundle`, as suggested in https://github.com/Homebrew/homebrew-bundle/issues/181#issuecomment-226442072 and https://github.com/Homebrew/homebrew-bundle/issues/450#issuecomment-464452684. In a a lot of my usage of Brewfiles, I have a Makefile enabling `make deps` which calls `brew bundle install --file=Brewfile --no-lock` [^explicit] and then will do things with the programs that Homebrew installed, e.g. creating Python virtual environments and installing dependencies or using a tool to sync data, etc.

[^explicit]: Explicitly specifies all defaults, better for folks less familiar with tools

**There is another way I just thought of…**

You could put an [`at_exit`](https://ruby-doc.org/core-2.6.8/Kernel.html#method-i-at_exit) block in your Brewfile and run any setup steps there if `brew bundle` is your primary entry point for dependency installation.

```ruby
brew 'jq'

at_exit do
  puts 'Running post-install tasks...'
end
```

begets:

```
$ brew bundle
Using jq
Homebrew Bundle complete! 1 Brewfile dependency now installed.
Running post-install tasks...
```

So, give this a shot— completely untested:

```ruby
brew `fzf`

at_exit do
  system '/usr/local/opt/fzf/install'
end
```

**Comment by MikeMcQuaid** [comment]
> While I can see the tempting utility of it, this pattern is best off left to scripts that call `brew bundle`

Agreed, passing on this, sorry.

Another option, as @colindean mentioned, is you can just add arbitrary Ruby to your `Brewfile`.

**Comment by kopach** [comment]
Cool, thank you. Wasn't aware arbitrary Ruby is an option. That would do the job. Thank you for your help

**Comment by MikeMcQuaid** [comment]
@kopach You're welcome, thanks!
