### ISSUE TITLE
Formula without a bottle for a platform (linux) are skipped, even when given "build-from-source"

### ISSUE THREAD

**Issue by Otterverse** [Homebrew/homebrew-bundle#1191]
```
$ brew bundle --file=- <<-EOS
> brew "upx", args: ["build-from-source"]
> EOS
Skipping upx (no bottle for Linux)
Homebrew Bundle complete! 0 Brewfile dependencies now installed.
```

This doesn't appear to happen with formulae from my own tap that have no bottles at all, and I've confirmed that formulae WITH bottles still honor build-from-source.

I'm unclear if this is intended behavior, and/or if there's some flag or option I can set to always install this from source anyway. My apologies if there is and I've simply missed it.

**Comment by MikeMcQuaid** [comment]
`build-from-source` isn't a valid option.

This is intentional for homebrew/core because a missing bottle indicates that we failed to build a bottle for that platform. Please submit a PR there to build the a bottle.

Sorry!
