### ISSUE TITLE
Feature Request: Respect `--quiet`/`-q` cli flag

### ISSUE THREAD

**Issue by maxcbc** [Homebrew/homebrew-bundle#1202]
**Problem**
Homebrew bundle has quite verbose output at times, such as the `Using package_x` output ([source](https://github.com/Homebrew/homebrew-bundle/blob/6b01bd338af95db59f1d6db87ebf6416d7518297/lib/bundle/installer.rb#LL43C1-L43C1)) when running `brew bundle install`.

`brew bundle --help` lists the standard homebrew `--quiet`/`-q` flag in its output, which is intended for use cases where the user wishes to suppress extraneous output. Currently homebrew bundle does not appear to respect this flag.

**My Usecase**
I use homebrew bundle as part as my standard dotfiles setup to maintain a consistent development setup across multiple macos devices and to minimise disaster recovery time.
As part of this, I run `brew install --global --quiet --cleanup` on every call to `brew` which would potentially change the state of my brewfile.
I'd like the `--quiet` flag to reduce the output from this command, so that it only tells me if it is installing/uninstalling packages/casks from my system.

**Solution**
Update homebrew bundle to respect the `--quiet`/`-q` flag by replacing relevant direct calls to `puts` with a custom log function which acts as a noop if the flag is active.

**Comment by MikeMcQuaid** [comment]
Thanks for the good write-up. What would you expect the output to be with `--quiet`? Nothing unless there are errors?

**Comment by maxcbc** [comment]
I think it is best to mirror the behaviour of the `brew` command, which I think would mean "Nothing unless there are errors" as you say.

Though, that aside, just as a cli user I'd expect:
- `quiet`: log errors or prompts for input only (i.e. if something goes wrong or the user needs to elevate to sudo etc)
- `default`: same as `quiet`, plus logging changes to the system (i.e. things being installed or removed).
- `verbose`: same as `default`, plus logging where changes to the system aren't required (i.e. where something is already installed, etc).

**Comment by MikeMcQuaid** [comment]
> * `quiet`: log errors or prompts for input only (i.e. if something goes wrong or the user needs to elevate to sudo etc)

Agreed. I think the `default` and `verbose` already behaves as described so I think that'd be good scope for this issue.

@maxcbc Do you want to give this a go implementing it yourself? Happy to provide review and help on a partially working/CI failing draft PR?

**Comment by maxcbc** [comment]
@MikeMcQuaid Sure. It'll probably be a few weeks before I can get to it, but a good opportunity to refresh my ruby skills.
Watch this space 🙂

**Comment by hermitmaster** [comment]
I'd like this as well.

**Comment by osalbahr** [comment]
Let us know if you made some progress and stuck on something!

**Comment by colindean** [comment]
Taking a look at this, there are 61 places we're using puts instead of calling a logging function.

@MikeMcQuaid Is there a reason _not_ to use `ohai` for the majority of these? I see that at least `cmd/bundle.rb` uses `onoe` in a few places, implying that `ohai` is available.

**Comment by MikeMcQuaid** [comment]
> Taking a look at this, there are 61 places we're using puts instead of calling a logging function.
> 
> @MikeMcQuaid Is there a reason _not_ to use `ohai` for the majority of these? I see that at least `cmd/bundle.rb` uses `onoe` in a few places, implying that `ohai` is available.

@colindean Yes. We should be using `puts` instead. This is what Homebrew/brew does. `ohai` is not any more of a logging function: it's just a `puts` with a prefix. Homebrew/brew also uses `puts` all over the place, intentionally.
