### ISSUE TITLE
Brew quits unexpectedly during a bundle install

### ISSUE THREAD

**Issue by log2** [Homebrew/homebrew-bundle#1205]
Our automatic alignment procedure, chezmoi-based, runs the following command when detecting any change in brew content:

`brew bundle install --no-lock --no-upgrade --file=~/.Brewfile`

This morning I was running a routine alignment, with the following Brewfile:

[Brewfile-without-a-dot-thankyou-GitHub.txt](https://github.com/Homebrew/homebrew-bundle/files/11505740/Brewfile-without-a-dot-thankyou-GitHub.txt) (actual file is named `~/.Brewfile`, but GitHub rejects files named this way, so I had to rename it, in order to attach it. Sorry for the confusion)

When I got the following error:

> Error: Unexpected run command:
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formula.rb:1949:in `[]'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:43:in `formulae_by_full_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/skipper.rb:12:in `skip?'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:37:in `block in install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

If execution order in brew is linear, the troublesome instruction could be:

`brew "podman"`

My current Brewfile, as reported by `brew bundle dump`, is as follows:

[current-Brewfile-output-from-bundle-dump.txt](https://github.com/Homebrew/homebrew-bundle/files/11505758/current-Brewfile-output-from-bundle-dump.txt)

**Comment by MikeMcQuaid** [comment]
> [Brewfile-without-a-dot-thankyou-GitHub.txt](https://github.com/Homebrew/homebrew-bundle/files/11505740/Brewfile-without-a-dot-thankyou-GitHub.txt) (actual file is named `~/.Brewfile`, but GitHub rejects files named this way, so I had to rename it, in order to attach it. Sorry for the confusion)

> current-Brewfile-output-from-bundle-dump.txt

Could you paste the contents inline so they don't require a download? Use `<details>` if they are absurdly long.

Note that `brew bundle install --no-lock --no-upgrade --file=~/.Brewfile --verbose --debug` will provide a _lot_ more debugging information that may help you here.

**Comment by MikeMcQuaid** [comment]
> If execution order in brew is linear, the troublesome instruction could be:
> 
> `brew "podman"`

It is and, actually, can skip the above because this issue is https://github.com/Homebrew/homebrew-core/issues/131284
