### ISSUE TITLE
brew bundle dump not respecting --brews/--casks args

### ISSUE THREAD

**Issue by zhengpd** [Homebrew/homebrew-bundle#1207]
Is there any argument to `brew bundle dump` with only brews and casks? `--brews/--casks` only works in `brew bundle list` but not dumping.

**Comment by jacobbednarz** [comment]
not as of today. `brew bundle dump` will dump all resources without consideration for the type they are.

**Comment by zhengpd** [comment]
@jacobbednarz Thanks for reply. I ended up using alias: 

`alias brew-dump="brew bundle dump -f --file=- | sed '/mas .*/d' > ~/.config/homebrew/Brewfile"`
