### ISSUE TITLE
Request: Ability to disable vscode extension handling

### ISSUE THREAD

**Issue by duckpuppy** [Homebrew/homebrew-bundle#1209]
I've been using a script for a very long time that installs items in my global Brewfile and then cleans up with `zap` after the fact. Now that it understands vscode extensions, it uninstalls every one of them each time I try to run it. I use the built-in vscode sync to keep extensions synced across multiple systems, not all of which are macOS/Homebrew managed.

There should be a way to disable the management of vscode extensions so that users that don't want to use brew to manage them can still benefit from the cleanup commands without losing their setup every time.

**Comment by MikeMcQuaid** [comment]
Thanks for the feedback. Is there a reason you would not like to dump your VSCode extensions also to your `Brewfile`?

**Comment by duckpuppy** [comment]
I'm not sure where the anger is coming from... You asked for my reasons and I simply provided them. I was unaware you were on vacation, so really that didn't enter my mind. 

I was certainly surprised that you fixed it so quickly, so a belated thank you for that. Perhaps I should have done that earlier, and that's certainly on me. I apologize for that. 

In any case, this was a catastrophic failure mode for a feature that didn't exist two days ago and was a surprise to anyone who routinely used `--cleanup`. My mention of using the sync feature was meant to be illustrative. Anyone who DOESN'T use that would have had no recourse. I had no idea that vscode extension management was incoming.

**Comment by duckpuppy** [comment]
If you feel that I was being belligerent in any way. I apologize. I certainly do appreciate the work done on Homebrew.

**Comment by MikeMcQuaid** [comment]
> I'm not sure where the anger is coming from

No anger here ❤️ 

> I was certainly surprised that you fixed it so quickly, so a belated thank you for that. Perhaps I should have done that earlier, and that's certainly on me. I apologize for that.

Much appreciated 🙇🏻
