### ISSUE TITLE
Addition of VSCode Extension handling breaks `brew bundle cleanup --global` for extensions not managed by Homebrew

### ISSUE THREAD

**Issue by philoserf** [Homebrew/homebrew-bundle#1211]
Introduced in #1208

This is surprising and dangerous. It breaks existing workflows.

I count the new behavior as a bug, which should be removed.

See also #1210

**Comment by MikeMcQuaid** [comment]
> See also #1210

This was already merged. Please don't open issues for things that are already in the process of being fixed and/or already have an open issue.

**Comment by philoserf** [comment]
Had I known, I wouldn't.

**Comment by MikeMcQuaid** [comment]
> It might have landed as I was typing since I did search and browse open and closed issues and pull requests.

You didn't because you linked to the pull request that closed it literally in this issue when you created it.

**Comment by philoserf** [comment]
Oh, yeah. That was an edit—fast work @MikeMcQuaid. Thank you.

**Comment by MikeMcQuaid** [comment]
@philoserf You're welcome ❤️
