### ISSUE TITLE
vscode extensions have written into Brewfile event without --vscode argument 

### ISSUE THREAD

**Issue by tony-sol** [Homebrew/homebrew-bundle#1212]
I have Brewfile, created by 
```
brew bundle dump --all --describe --force
```
But after last updates, it also writes vscode extensions.
So, i tried to run dump as
```
brew bundle dump --casks --taps --brews --describe --force
```
but it still writes vscode extensions into Brewfile

**Comment by MikeMcQuaid** [comment]
Yes, as documented, `--casks` etc. only affect `brew bundle list`. Please either manually remove them or consider adding a PR for `--no-vscode` or similar.
