### ISSUE TITLE
bundle dump spams warning messages to console regarding a deprecated function call

### ISSUE THREAD

**Issue by jschank** [Homebrew/homebrew-bundle#1223]
When running `$ brew bundle dump --force` I get this error message. Which suggests I report it here.

```
Warning: Calling Formula#oldname is deprecated! Use Formula#oldnames instead.
Please report this issue to the homebrew/bundle tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:160
```

**Comment by jschank** [comment]
I am using:

- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
- fish, version 3.6.1
- Mac OS
    - ProductName:		macOS
    - ProductVersion:		13.4.1
    - BuildVersion:		22F82

**Comment by hermitmaster** [comment]
Seeing the same error, the only noteworthy difference is that I'm using zsh. This just started today.

**Comment by gh640** [comment]
I met this warning when running `brew bundle`. My Homebrew version is same `4.0.28-7-gcb61785`.

`homebrew-bundle/lib/bundle/brew_dumper.rb:160`:

https://github.com/Homebrew/homebrew-bundle/blob/c02dfff991181c3ad1721138e2ac8bdce3c6ee5d/lib/bundle/brew_dumper.rb#L160

`formula.oldname`:

https://github.com/Homebrew/brew/blob/4bbc0af6935816c75e0057364a84fd7fa8de071b/Library/Homebrew/formula.rb#L500-L505

Just changing `formula.oldname` in `brew_dumper.rb:160` to `formula.oldnames.first` would work but there might be a better resolution.

**Comment by colindean** [comment]
I've confirmed that #1225 resolves this problem. Thank you for the report!
