### ISSUE TITLE
`brew bundle dump` opens VScode

### ISSUE THREAD

**Issue by colindean** [Homebrew/homebrew-bundle#1226]
After updating to 5264d22 after resolving #1225, I tried a `brew bundle dump` and it opened a VScode window just before the process exited. It opened to the file `\Ubuntu\mnt\c\Program Files\Microsoft VS Code\resources\app\out\cli.js` as a new, unsaved file. The path is sensible: this Homebrew installation is in WSL. However, I'd not expect VScode to open another window, esp. when I already have one open, and open in the WSL scope at that.

I'm not sure what's happening. It's not very annoying to me because I don't use `brew bundle dump` regularly.

One thing I tried is what `Bundle::VscodeExtensionDumper#extensions` does: `code --list-extensions`. Running this in a WSL terminal did not open another VScode window.

**Comment by Moulick** [comment]
Not happening on MacOS 13.4.1 (22F82)

```
HOMEBREW_VERSION: 4.0.28-20-g5b30de8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5b30de880d3c937b121dcc036582143dc4548b4f
Last commit: 19 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e346e1cb3fc7921fbc8208c3e4f66fad141c6067
Core tap last commit: 10 minutes ago
Core tap branch: master
Core tap JSON: 02 May 22:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

**Comment by MikeMcQuaid** [comment]
Closing as seems to be WSL-specific which is a small minority of users. Will review a PR to fix underlying issue here.
