### ISSUE TITLE
Exit with 1 when failed `brew bundle check`

### ISSUE THREAD

**Issue by 5ouma** [Homebrew/homebrew-bundle#1242]
I use the `brew bundle check` command in a shell script.
It should exit with 1 to notify not satisfied when it says this.

```
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
```

**Comment by MikeMcQuaid** [comment]
It does:

https://github.com/Homebrew/homebrew-bundle/blob/4d03d87b61bd5202ffb89232592965252a096820/lib/bundle/commands/check.rb#L19-L27

**Comment by 5ouma** [comment]
Yes, I found the code, but even I run `echo $?`, it outputs `0`.

**Comment by colindean** [comment]
Can you share how you're invoking `brew bundle check`?

Working for me, and on a machine I don't use for development regularly:

```
[18:54:00 colin@penguin /tmp ]
$ echo 'brew "adr-tools"' > Brewfile
[18:54:18 colin@penguin /tmp ]
$ brew bundle check
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
[18:54:32 colin@penguin /tmp ]
$ echo $?
1
```

**Comment by 5ouma** [comment]
I use `brew bundle check --no-upgrade --file="/path/to/Brewfile"`.
However, even when I tried the method you said, it output `0`.

**Comment by 5ouma** [comment]
I found out why mine doesn't output `1`.
The reason is I wrap `brew` with a function.
I'm sorry for the confusion.
