### ISSUE TITLE
brew bundle dump - Error: undefined method `bottle_disabled?' for...

### ISSUE THREAD

**Issue by auntchilada** [Homebrew/homebrew-bundle#1243]
$ brew bundle dump

Error: undefined method \'bottle_disabled?' for #<Formulary::FormulaNamespaceAPIce117a0dac25e1f68b18d873426f22a0::Rubberband:0x00007fb3b3c17078>
Did you mean?  bottle_defined?
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:152:in `formula_to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:111:in `add_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:38:in `formulae_by_full_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:23:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:55:in `dump'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:19:in `build_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:29:in `dump_brewfile'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:9:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:111:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

\# ----------------------------------------

$ brew config:

HOMEBREW_VERSION: 4.1.7-35-gde50e841
ORIGIN: https://github.com/Homebrew/brew
HEAD: de50e8418458fbb547fac2ecdbeaa6d4898c0835
Last commit: 22 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a99ade9e16d3b97b2c49cc4f61dd5dbd945c4678
Core tap last commit: 22 hours ago
Core tap branch: master
Core tap JSON: 02 Sep 19:22 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 15
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: /Users/bduart/bin/beditor
HOMEBREW_EVAL_ALL: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit icelake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode-14.3.1.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1 => /Applications/Xcode-14.3.1.app/Contents/Developer

\# ----------------------------------------

$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sphinx
  xml2

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  uutils-coreutils
  proctools
  gdu

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
   M Formula/u/uutils-coreutils.rb

\# ----------------------------------------

respectfully submitted,

-brian

**Comment by MikeMcQuaid** [comment]
Run `brew update-reset` and try again.

**Comment by auntchilada** [comment]
hi Mike,

ha, did just  that after i submitted the issue. 

results are the same. rapid, unscheduled disassembly.

thank you for your support!

**Comment by MikeMcQuaid** [comment]
@auntchilada You have too many `brew doctor` warnings for me to help you here, I'd suggest you fix them all. This is an issue with your machine/installation and not Homebrew as a whole.
