### ISSUE TITLE
`vagrant plugin install ...`

### ISSUE THREAD

**Issue by TheKnarf** [Homebrew/homebrew-bundle#1245]
Maybe it could support also installing `vagrant` plugins?

Ex. `vagrant plugin install vagrant-qemu`

That way I could have the following in a Brewfile:

```
cask "vagrant"
brew "qemu"
vagrant-plugin "vagrant-qemu"
```

**Comment by jacobbednarz** [comment]
i'm happy your review a PR for this. there is some prior art for vscode extensions in #1208 if you would like to take a pass.

**Comment by MikeMcQuaid** [comment]
Sorry, I don't think Vagrant plugins are widely used enough for this to be useful. What I would be interested in is a way to add extensions for such things to be easily addable in another repository without us needing to maintain it in this one.
