### ISSUE TITLE
Feature Request: Global Dart Packages

### ISSUE THREAD

**Issue by vincekruger** [Homebrew/homebrew-bundle#1247]
It would be awesome if we could also have Global Dart packages stored :)

**Comment by MikeMcQuaid** [comment]
Does Dart have a `Brewfile`/`Gemfile`/`package.json` equivalent?

**Comment by vincekruger** [comment]
For sure. 

https://formulae.brew.sh/formula/dart-sdk
https://formulae.brew.sh/cask/flutter

**Comment by MikeMcQuaid** [comment]
I guess I mean: if it has an equivalent: what's the value of having this in `Brewfile` as well/instead?

**Comment by vincekruger** [comment]
I use a `Brewfile` to keep a running list of all my installed software, extensions, etc

**Comment by colindean** [comment]
If there's something that you want a brew-installed package to execute _after_ `brew bundle` is done with its installation work, consider using an atexit command. See https://github.com/Homebrew/homebrew-bundle/issues/1190#issuecomment-1493430099 for more information.

**Comment by MikeMcQuaid** [comment]
Thought about this more and: passing on this, sorry @vincekruger. Will consider if over time we see a bunch more requests.

**Comment by vincekruger** [comment]
I'll try to give it a bash myself and see if I succeed :)
