### ISSUE TITLE
Error: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by nate-fm** [Homebrew/homebrew-bundle#125]
When I use the option to `dump`, I get the following error:

**Error: undefined method `map' for nil:NilClass**
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:78:in `formula_inspector'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:64:in `block in formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:64:in `map'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:64:in `formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:14:in `formulae'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:34:in `cask_requirements'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:17:in `dump_brewfile'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle:73:in `<main>'

**More output below to diagnose the issue:**

 $ ls Brewfile
Brewfile

 $ brew bundle dump
Error: undefined method `map' for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:78:in `formula_inspector'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:64:in `block in formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:64:in `map'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:64:in `formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:14:in `formulae'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:34:in `cask_requirements'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dumper.rb:17:in `dump_brewfile'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/dump.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle:73:in `<main>'

 $ brew update
Already up-to-date.

 $ brew doctor
Your system is ready to brew.

 $ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

 $ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 62ac6f05d15a8e4742ce60c51c5380a92eea56d3
Last commit: 85 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.1.1
CLT: 7.1.0.0.1.1444952191
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.3/bin/ruby
Java: 1.8.0_65

 $ cat Brewfile

$

**Comment by mikemcquaid** [comment]
Can you paste your `brew info --json=v1 --installed`? Thanks!

**Comment by nate-fm** [comment]
Sure. Paste it here: http://pastebin.com/UW73Xyb8
