### ISSUE TITLE
Feature Requests: Automatically Run `brew bundle dump` After `brew install`

### ISSUE THREAD

**Issue by VoxDai** [Homebrew/homebrew-bundle#1280]
Just the same way how `brew update --auto-update` works. It would be great if Homebrew can automatically run `brew bundle dump` every time `brew install xxx` or `brew uninstall xxx` is launched.

**Comment by jacobbednarz** [comment]
this isn't something we would roll out as the default given not all users of `brew` are also using `brew bundle`. perhaps we could add a flag in Homebrew/brew itself (not this repository)? 

instead, i'd recommend changing your workflow to update the `Brewfile` and then run `brew bundle ...` instead which will keep things in sync.
