### ISSUE TITLE
Add SetApp support

### ISSUE THREAD

**Issue by SukkaW** [Homebrew/homebrew-bundle#1288]

**Comment by jacobbednarz** [comment]
given the issues we've had with `mas` support in the past (due to the Apple APIs) and lack of requests so far, this isn't something that I think warrants the effort just yet. sorry!

**Comment by SukkaW** [comment]
> given the issues we've had with `mas` support in the past (due to the Apple APIs) and lack of requests so far, this isn't something that I think warrants the effort just yet. sorry!

Understood. Thanks for your explanation!
