### ISSUE TITLE
VSCode extensions that have capital letters seem to not be registered, and get uninstalled

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#1302]
I have a bunch of extensions that are managed using homebrew: https://gist.github.com/vraravam/8c9eae91a3750bed86b81e3a4711f842#file-brewfile-L193-L231

After a recent upgrade of VSCodium Insiders and homebrew, I noticed that while "brew bundle install" will install all the extensions, "brew bundle cleanup" will somehow delete only those extensions that start with capital letters!
<img width="972" alt="Screenshot 2024-02-08 at 9 51 01 PM" src="https://github.com/Homebrew/homebrew-bundle/assets/69629/b124bb4f-a096-4eee-8164-81540423c0e4">

The actual/valid extension names (all of the ones marked as "would be deleted") have capital letters somewhere in the extension-id as seen in the above link of the Brewfile, but for some reason they show up with lower-case - and I suspect this marks them for deletion. Please help fix asap.

**Comment by MikeMcQuaid** [comment]
I've opened a PR: https://github.com/Homebrew/homebrew-bundle/pull/1303

> Please help fix asap.

This is a volunteer run open source project. If you need a fix ASAP: you need to open a PR yourself. Do not say things like this in future, please.

**Comment by vraravam** [comment]
> Do not say things like this in future, please.

sure - i apologize. It took me some time to understand and diagnose where the problem lies. But, in the future, i will try to get into the source code for a PR as well. Thanks -  <3 for homebrew!
