### ISSUE TITLE
Specify Package Installed from Source

### ISSUE THREAD

**Issue by vicmattos** [Homebrew/homebrew-bundle#1318]
Hi,

This is my first PR, so I might need your patience. Sorry in advance for any rookie mistake.

I would like to have packages installed from source (`brew install -s package`) specified in `Brewfile`.

I'm trying to install [neovim](https://formulae.brew.sh/formula/neovim), but it depends on [LuaJIT](https://formulae.brew.sh/formula/luajit) (which is in a [weird spot right now](https://github.com/Homebrew/homebrew-core/issues/68013))

The workaround is to [install LuaJIT from source](https://github.com/orgs/Homebrew/discussions/4563), which works just fine.

I keep my system packages in my dotfiles repository and would be ideal to have the luajit flagged as installed from source. Is this possible?

**Comment by jacobbednarz** [comment]
you can use `args: ["--build-from-source"]` in your Brewfile definition.

```rb
brew "packagename", args: ["--build-from-source"]
```

**Comment by vicmattos** [comment]
Thanks for the quick response!!
