### ISSUE TITLE
[Feature] Support groups

### ISSUE THREAD

**Issue by spuder** [Homebrew/homebrew-bundle#1327]
As a user with multiple laptops, I'd like to have 1 brewfile that can support multiple installation targets using groups
so that I can prevent unapproved apps from being installed on my work computer

### Example

```ruby
group :personal do
  cask "arduino-ide"
  cask "steam"
end


group :work do
  brew "git"
  cask "visual-studio-code"
end
```

## Reference

https://bundler.io/guides/groups.html

**Comment by jacobbednarz** [comment]
this was recently discussed in #1315 and has a couple of ideas in there how you can achieve this today.
