### ISSUE TITLE
Error: cannot load such file -- abstract_command

### ISSUE THREAD

**Issue by bgrzesiak-fetch** [Homebrew/homebrew-bundle#1336]
[This change](https://github.com/Homebrew/homebrew-bundle/commit/5bdef585b27b283257b0d7757341bbb4847e1ffb#diff-2ba13d1d1d9b7abcde49568b7aec20c97f4541f44f6befd62ac6a4d820ddb7ccR3) seems to be breaking CI for us. To me, it looks like a circular dependency, though I'm not sure if that's actually causing the failure.

Circular dependency:
* `brew` defines `abstract_command`
* `brew` loads `homebrew-bundle`
* `homebrew-bundle` attempts to reach back into `brew` for `abstract_command`

Actual error I'm getting:

```
$ brew "bundle"
==> Tapping homebrew/bundle
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (109 files, 2.3MB).
Error: cannot load such file -- abstract_command
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:3:in `require'
/opt/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:3:in `<top (required)>'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/opt/homebrew/Library/Homebrew/commands.rb:78:in `external_ruby_v2_cmd_path'
/opt/homebrew/Library/Homebrew/brew.rb:85:in `<main>'
Can't install with Brewfile:  exit status 1
Can't install with Brewfile:  exit status 1
```

We're using [bitrise](https://bitrise.io) for CI, and here's the `brew-install` [step](https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/brew-install/0.12.3/step.yml) that's failing. It hasn't been touched in 10 months.

**Comment by SMillerDev** [comment]
What does your `brew config` say?

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-bundle/pull/1335 was just merged which will tell you the solution: you need to run `brew update`.
