### ISSUE TITLE
Vscode : Case sensitive issue is back

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#1341]
this was fixed in an earlier PR that I had raised a couple of months ago, and it had been fixed at that time. But, when I rerun the same commands now, the vscode extensions that have upper and lower case characters in the extension id are now being cleaned up forcibly.
My Brewfile is here: https://gist.github.com/vraravam/8c9eae91a3750bed86b81e3a4711f842
I can confirm that only those extensions that have both upper and lower case characters are affected.

**Comment by MikeMcQuaid** [comment]
> are now being cleaned up forcibly

What does this mean?

To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by vraravam** [comment]
1. Use the brewfile from the home folder (link in the original description)
2. `brew bundle check || brew bundle --all --cleanup; brew bundle cleanup -f; brew cleanup --prune=all; brew autoremove; brew upgrade`
3. The above set of commands uninstalls the following vscode extensions
  a. BrandonKirbyson.vscode-animations
  b. BriteSnow.vscode-toggle-quotes
  c. DavidAnson.vscode-markdownlint
  d. DigitalBrainstem.javascript-ejs-support
  e. EditorConfig.EditorConfig
  f. IBM.output-colorizer

(and others that have both upper and lower case characters in the extension id

**Comment by MikeMcQuaid** [comment]
I cannot reproduce on multiple levels:

**Comment by MikeMcQuaid** [comment]
I cannot reproduce on multiple levels:
- `code --list-extensions` always outputs lowercase extensions for me, even for e.g. `EditorConfig.EditorConfig` (which I have installed https://github.com/MikeMcQuaid/dotfiles/blob/412f3362fe3eb6bc0f68082f03ad75f5b609c7e7/Brewfile#L166)
- we always `downcase` all extension names before dumping, anyway: https://github.com/Homebrew/homebrew-bundle/blob/40ab9cfe3e5e59b0b690b5afd0dd59288d407551/lib/bundle/vscode_extension_dumper.rb#L15
- we always compare downcased extension named on cleanup: https://github.com/Homebrew/homebrew-bundle/blob/40ab9cfe3e5e59b0b690b5afd0dd59288d407551/lib/bundle/commands/cleanup.rb#L146

As a result, it seems likely that you are on an old version of homebrew-bundle, can you check please?

If you are not: 

> 1. Use the brewfile from the home folder (link in the original description)

Please provide minimal input data here.



> 2\. brew bundle check || brew bundle --all --cleanup; brew bundle cleanup -f; brew cleanup --prune=all; brew autoremove; brew upgrade

And provide minimal commands. These should not all be necessary to reproduce.

Ideally: try to open a PR. Thanks!

**Comment by vraravam** [comment]
thanks @MikeMcQuaid .
1. The PR #1303  was in fact submitted by me.
2. The Brewfile that you have linked (from your gist) might be the reason its not showing up since it has all the extension ids in lower case.
 
Here's my investigation: When I go into VSCode, go to the Extensions view, click on 1 of the extensions, (for eg editorconfig), click on the gear icon, and select the "Copy Extension ID", the text that's copied is NOT all lowercase. I would assume that any other user is also following similar steps when adding a new extension, they follow the same steps.
<img width="738" alt="Screenshot 2024-04-09 at 2 26 33 PM" src="https://github.com/Homebrew/homebrew-bundle/assets/69629/45c8ce20-dc7f-47c7-a480-00acba9f29ee">

For the editorconfig extension, the text that's copied is `EditorConfig.EditorConfig` and not `editorconfig.editorconfig`

If I run `code --list-extensions`, i realize that it dumps everything in lowercase - but, that's an inconsistency in how the CLI behaves vs what the original extension author has put as the id.

**Comment by MikeMcQuaid** [comment]
@vraravam I know the text it not always lowercase. My point is: even if it is lowercase we only compare lowercase names to lowercase names. Even when I edit my `Brewfile` manually to not have lowercase names: I cannot reproduce your issue.
