### ISSUE TITLE
[Question] Can formula and cask have the same name?

### ISSUE THREAD

**Issue by wenfangdu** [Homebrew/homebrew-bundle#1344]
I understand that formula is cli tool and cask is gui tool, but does homebrew allow a formula and a cask having the same name? If it does, what happens if I run `brew install dupe-name`?

**Comment by wenfangdu** [comment]
@SMillerDev Thank you for the quick response, can you give an example of such a package, I've never seen one.

**Comment by jacobbednarz** [comment]
docker used to be one but i cannot think of another off the top of my head.

**Comment by wenfangdu** [comment]
@jacobbednarz Thanks, looks like it still is:
![image](https://github.com/Homebrew/homebrew-bundle/assets/28700378/26047074-d8b3-44af-8b9b-442dc9433059)
