### ISSUE TITLE
Unattended install of a bundle

### ISSUE THREAD

**Issue by LukasKnuth** [Homebrew/homebrew-bundle#1356]
I have my Brewfile created with `brew bundle dump --global --force --describe`

When I install it with `brew bundle install --file=.Brewfile` every formulae/cask that requires sudo for installation will prompt independently. This means that I can't just start the task and leave the laptop unattended, since it might wait for my password input at any moment.

Is there a way to give my password once initially and then know it will work unattended? Can I simply run `sudo bundle install` or will that mess up the non-sudo formulae/cask installations?

**Comment by SMillerDev** [comment]
That's simply how sudo works. `sudo brew bundle install` will not work since brew will not work with sudo.

Your best guess is probably `SUDO_ASKPASS`, which might also be a security problem

**Comment by MikeMcQuaid** [comment]
> Your best guess is probably `SUDO_ASKPASS`, which might also be a security problem

Yes, this is the solution or, worse, running as a user with `sudo` `NOPASSWD` (not recommended).

**Comment by LukasKnuth** [comment]
For future reference, what you're suggesting is:

1. Create a script like `echo "my perosnal password"`
2. Run `SUDO_ASKPASS=/path/to/script.sh brew bundle install`

This will then run the script when brew uses `sudo` to elevate privileges and inputs whatever the script returns to stdout into the sudo prompt, correct?

**Comment by SMillerDev** [comment]
Yes, sudo is just sudo. So whatever mechanisms sudo has to allow unattended access, you can use them for brew.
