### ISSUE TITLE
Confusion on what should be dumped

### ISSUE THREAD

**Issue by jedahan** [Homebrew/homebrew-bundle#1398]
I've been migrating my own install scripts to take advantage of brew bundle, and noticed that `brew bundle dump` lists more packages than `brew leaves --installed-on-request`.

Is this the expected behavior, and is there an option I should be using to only install the packages described by `brew leaves --installed-on-request`?

**Comment by MikeMcQuaid** [comment]
This is expected. You can either use `brew mark` to mark things you do not wish to be installed on request.
