### ISSUE TITLE
Remove `tap 'caskroom/cask'` instructions

### ISSUE THREAD

**Issue by adityadalal924** [Homebrew/homebrew-bundle#142]
Not sure if `tap 'caskroom/cask'` is explicitly required anymore (after https://github.com/caskroom/homebrew-cask/pull/15381), can this be safely removed from the directions?

Happy to submit a PR with the fixes if appropriate, as well.

**Comment by mikemcquaid** [comment]
The tap is still required, just not the installation of the `brew-cask` formula.
