### ISSUE TITLE
Don't cleanup dependencies of whitelisted formulae

### ISSUE THREAD

**Issue by justmytwospence** [Homebrew/homebrew-bundle#143]
Is it possible to prevent `brew bundle cleanup` from uninstalling dependencies of the whitelisted formulae? This would facilitate a nice use-case: keep a .Bundle file of just the formula that you actually care about (without their dependencies explicitly), and still be able to run `brew bundle clean` without breaking them all.

**Comment by mikemcquaid** [comment]
We'd review a pull request for this but currently: no, sorry. I'd recommend instead using `brew bundle --global dump` and `brew bundle --global cleanup` and just have it list all the dependencies in there.

**Comment by AlJohri** [comment]
Just adding a +1 to this issue which I see was also requested here #55.

I like to organize and comment my Brewfile like such:

```
# Get started faster
cask 'google-chrome-beta'
cask 'iterm2-nightly' # terminal emulator
...

# [Brew Cask] Non-essential Apps
cask 'airserver'
cask 'licecap' # gif creator
...
```

and also include some commands such as:
```
cask 'anaconda' unless File.directory?(ENV['HOME'] + '/anaconda3')
```

it would be great to use `brew bundle cleanup` for this purpose.

**Comment by mikemcquaid** [comment]
@AlJohri As mentioned above: `brew bundle cleanup` is designed to be used with `brew bundle dump` output so we'll accept a pull request for this but won't be working on it ourselves.

**Comment by audy** [comment]
I thought about tackling this but it looks like homebrew-bundle doesn't parse homebrew formulae and so doesn't know anything about dependencies.

One solution is to do what Kenneth Reitz [does with pip](http://www.kennethreitz.org/essays/a-better-pip-workflow) and keep the full and autogenerated list of dependencies in a separate file (such as `Brewfile.lock`).

Since not all of homebrew-bundle command's take a `--brewfile` argument, you need to do this backwards:

```
Brewfile.tidy
Brewfile # the real list of dependencies
```

```
brew bundle --brewfile Brewfile.tidy
brew bundle dump --file Brewfile
# later on
brew cleanup
```

**Comment by MikeMcQuaid** [comment]
> I thought about tackling this but it looks like homebrew-bundle doesn't parse homebrew formulae and so doesn't know anything about dependencies.

Homebrew will start tracking dependencies used at install-time as of https://github.com/Homebrew/brew-evolution/blob/master/003-install-bottles-of-arbitrary-versions.md so that may open the door to do something smarter then (CC @sjackman).

Will reopen this. Thanks for the comments, folks.

**Comment by sjackman** [comment]
As a workaround, you could tack on the dependencies of the packages listed in the Brewfile to the end of the Brewfile with a script that gets the `brew deps` of all the packages list in the Brewfile.

**Comment by MikeMcQuaid** [comment]
Finally opened a PR for this: https://github.com/Homebrew/homebrew-bundle/pull/263
