### ISSUE TITLE
Option to exclude/disable vscode in dump

### ISSUE THREAD

**Issue by JtMotoX** [Homebrew/homebrew-bundle#1456]
Would it be possible to have a `brew bundle dump` flag, something like `--no-vscode` to disable the vscode integration?  I use vscode built-in sync functionality and this is causing some issues.

Currently, I have to perform `sed -i '/^vscode /d' $HOME/Brewfile` after every dump.

**Comment by jacobbednarz** [comment]
today there isn't a way to selectively output some types over others. the assumption is that if you have it installed, you will want to manage it via `brew bundle` -- in your case, that isn't true.

i don't know how widely used this would be but open to leaving this here to gauge the interest and welcome a PR if you want to see this land.

**Comment by JtMotoX** [comment]
This has been requested in https://github.com/Homebrew/homebrew-bundle/issues/1209 and https://github.com/Homebrew/homebrew-bundle/issues/1212 so there are others that are interested in this option.

**Comment by MikeMcQuaid** [comment]
@JtMotoX would you prefer `brew bundle dump --skip-vscode` or something like `export HOMEBREW_BUNDLE_NO_VSCODE=1`?

**Comment by JtMotoX** [comment]
`--skip-vscode` would be preferred

**Comment by MikeMcQuaid** [comment]
@JtMotoX you're welcome, thanks for taking the time to say thanks!
