### ISSUE TITLE
Allow comments in Brewfile

### ISSUE THREAD

**Issue by AlexKucera** [Homebrew/homebrew-bundle#146]
Hi,

I wanted to add a few comments to my Brewfile like the syntax of this bundle and a link to this GitHub for future reference. Sadly I was not able to figure out a comment syntax that worked. Pointing `brew bundle` to the Brewfile with comments always throws syntax errors.

Any ideas on how to work around this?

**Comment by mikemcquaid** [comment]
`Brewfile`s are a Ruby DSL so comments can be added with `#`.
