### ISSUE TITLE
Mention project has been renamed

### ISSUE THREAD

**Issue by dideler** [Homebrew/homebrew-bundle#148]
I assume this project was once called brewdler?

When I run `brew doctor` I get the following many times:
```
Found command `brew-brewdler` in following places:
    /usr/local/Library/Taps/homebrew/homebrew-brewdler/cmd/brew-brewdler.rb
    /usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-brewdler.rb
```

When I search for `homebrew brewdler`, this repository is the first result. Could it be mentioned somewhere in the README that this repository has been renamed to avoid confusion?

---

For those wondering how to fix the above warning, run
```
brew untap homebrew/brewdler                                                                                                                    ```

**Comment by mikemcquaid** [comment]
I'll bear this in mind but I'd rather not add this unless a few people have this problem. Thanks for the issue, though!
