### ISSUE TITLE
Add support for hidden .brewfile

### ISSUE THREAD

**Issue by onemanstartup** [Homebrew/homebrew-bundle#15]
For installing machine specific software :)

**Comment by loranger** [comment]
It seems dotfiles is not supported, am I wrong ?

I tried to move my Brewfile to .Brewfile, but bundle failed to check :

```
Merlin ~ ⎠⎠⎠ la .Brewfile                                                                                      ⏎
-rw-r--r--  1 loranger  staff   4,3K 18 avr 16:33 .Brewfile
Merlin ~ ⎠⎠⎠ brew bundle check
Error: No Brewfile found
```

**Comment by mikemcquaid** [comment]
@loranger Tried `--global`?

**Comment by loranger** [comment]
I did not, and it works.
I should have check the options first.

Thanks @mikemcquaid !

**Comment by mikemcquaid** [comment]
@loranger My pleasure!
