### ISSUE TITLE
PowerShell module support

### ISSUE THREAD

**Issue by jhoek** [Homebrew/homebrew-bundle#1506]
With more and more non-Windows power users adopting PowerShell (I would argue that PowerShell is roughly as "widely used" as VS Code - which is supported), would it make sense to add support for installing PowerShell modules from the PowerShell Gallery? They can be installed without sudo or user interaction, and testing if they are installed is trivial. 

Thank you for considering my suggestion. I'm afraid I don't speak any Ruby, otherwise I would have tried to add it myself.

**Comment by jacobbednarz** [comment]
much like our previous requests (#1477) for expanding ecosystem support, we don't yet have a strong enough signal this is something we should add and support. additionally, given this is for a platform that no one on the maintainer team uses full time (to my knowledge), i cannot see us adding support anytime in the near future and would seek a community contribution if it ever got legs.

**Comment by jhoek** [comment]
Fair enough, thanks anyway for your time, @jacobbednarz.
