### ISSUE TITLE
Were update and upgrade purposely removed from the DSL?

### ISSUE THREAD

**Issue by yyyc514** [Homebrew/homebrew-bundle#151]

**Comment by yyyc514** [comment]
Ah looks like maybe it was an internal brew feature that got canned?

**Comment by mikemcquaid** [comment]
There was an old DSL that wasn't well designed. This one is better. `upgrade` is done implicitly but `update` needs done manually now.

**Comment by yyyc514** [comment]
Interesting.  How is this better than say a shell script with calls to brew?

**Comment by mikemcquaid** [comment]
Well, the previous DSL wasn't any better. This one understands Homebrew versions and the like in a slightly smarter way and allows you to embed some Ruby logic inside your Brewfile. It's basically more like a Gemfile.
