### ISSUE TITLE
Show cask name when asking for sudo password

### ISSUE THREAD

**Issue by alias1** [Homebrew/homebrew-bundle#153]
When installing a bundle file I get asked for my `sudo` password with no indication of what is trying to be installed. The only real way to find out currently is to enter it wrong 3 times and wait for the error message to say what was trying to be installed.

It would be really good if there could be some context shown before prompting for a password.

**Comment by mikemcquaid** [comment]
I think this is a `brew cask` issue rather than a `homebrew-bundle` one. We don't have control over what `cask` does so this would require printing every cask's names before it was installed (which I think would produce unnecessarily spammy output).
