### ISSUE TITLE
VSCodium, Cursor and other VS Code platform based

### ISSUE THREAD

**Issue by romanr** [Homebrew/homebrew-bundle#1544]
Discussed in #1208 a year ago. I don't think it was done, if you only have VSCodium installed it will not bundle dump anything from it.
The workaround is to have VS Code installed, which others, such as VSCodium and Cursor, will use to discover configured VSCode extensions.

**Comment by SMillerDev** [comment]
The opinion of the project leader who implemented it at the time was: people can add it if they want. This issue won't change that.

**Comment by MikeMcQuaid** [comment]
Will review a PR for this.
