### ISSUE TITLE
Deterministically create `bundle dump`

### ISSUE THREAD

**Issue by demosdemon** [Homebrew/homebrew-bundle#157]
Dump files should have a deterministic output. At least, it would be nice so I can keep them versioned without lines jumping around all over the place randomly.

I haven't looked at the code base in a while, but if I recall correctly, there's a dependency tree traversal when outputting. The nodes should probably be sorted lexicographically before descending further into the tree.

I'll remind myself to look at this later and drum up a PR if no one else has when I get around to it.

**Comment by mikemcquaid** [comment]
I think this would be cool but we don't really accept feature requests and a PR would be welcome.
