### ISSUE TITLE
Syntax error with `brew 'gpg'`

### ISSUE THREAD

**Issue by mcmillion** [Homebrew/homebrew-bundle#165]
This just started happening this morning, so not sure where the problem lies, but here's the trace from the error:

```
Error: /usr/local/Library/Taps/homebrew/homebrew-core/Aliases/gpg:1: syntax error, unexpected ..
../Formula/gnupg.rb
  ^
/usr/local/Library/Taps/homebrew/homebrew-core/Aliases/gpg:1: unknown regexp options - gpg
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formula.rb:1183:in `[]'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:59:in `formula_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:105:in `conflicts_with'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:116:in `resolve_conflicts!'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:26:in `install_change_state!'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:22:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:10:in `install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:49:in `block in install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:36:in `each'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:36:in `install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:72:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:90:in `<main>'
```

**Comment by ilovezfs** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md

Please follow (all of) these steps and post the information here so we can help you with your problem.

**Comment by mikemcquaid** [comment]
What's the contents of your `Brewfile`? Have you run `brew update` recently?

**Comment by UniqMartin** [comment]
To me this looks like there is an issue with the checked out `homebrew/core` tap. `/usr/local/Library/Taps/homebrew/homebrew-core/Aliases/gpg` contains the literal text `../Formula/gnupg.rb` instead of being a symbolic link, hence the syntax error.

@mcmillion A workaround would be to change your `Brewfile` from `brew 'gpg'` to `brew 'gnupg'`. But I'd check your global Git configuration or any other condition that blocks Git from creating symbolic links in a checkout. Have you set `core.symlinks = false` globally or for your user?

**Comment by mcmillion** [comment]
Sorry @ilovezfs, just following what the app told me to do. That troubleshooting document should probably be linked there as well, rather than just telling you to post here.

Looks like changing from `brew 'gpg'` to `brew 'gnupg'` did the trick! Maybe the project changed something? Either way, it's now working again. Thanks.

**Comment by ilovezfs** [comment]
@mcmillion Thanks for following up with the additional info. Did you get a chance to check what @UniqMartin said?
