### ISSUE TITLE
Other Installers

### ISSUE THREAD

**Issue by darkn3rd** [Homebrew/homebrew-bundle#169]
**Enhance Request**
Add methods for `gem`, `npm`, `pip`, or have a plug-in interface for these add methods.  I regularly use Homebrew to setup dev environments, so this would be nice to have, and keep it in a single install file.

**Comment by mikemcquaid** [comment]
This is definitely out of scope for the goals of homebrew-bundle. It's worth just having single files for each of these. If you're looking for a standard way to setup dev environments these may be of interest: https://github.com/mikemcquaid/strap https://github.com/github/scripts-to-rule-them-all
