### ISSUE TITLE
Contained Dependencies

### ISSUE THREAD

**Issue by jcampbell05** [Homebrew/homebrew-bundle#173]
Is there a way to mimic `Gemset` functionality ? 

So If I'm in a folder A with a `Brewfile` then all the dependencies installed for that tool are only accessible when in that folder.

**Comment by mikemcquaid** [comment]
Unfortunately not. It may be possible to `brew install` with a prefix inside e.g. `vendor` but this would mean many binary packages won't work. It also doesn't really make sense to "vendor" something like e.g. MySQL that exists as a systemwide dependency.
