### ISSUE TITLE
Add 'context'/group type option

### ISSUE THREAD

**Issue by alias1** [Homebrew/homebrew-bundle#175]
It would be awesome if we could add a 'context' to the Brewfile, so a bunch of packages could be installed or not based on a flag. I'm thinking along the lines of [bundler groups](http://bundler.io/v1.12/groups.html).

```
brew "everywhere-tool" # goes into :default group

brew "different-style-personal-tool", :group => :personal
brew "different-style-2", :group => [:personal, :work]

group :personal do
  brew "personal-tool"
end

group :work do
  brew "work-tool"
end
```

```
brew bundle install --without personal
brew bundle install --only work # maybe
```

**Comment by mikemcquaid** [comment]
Seems reasonable but we don't really accept feature requests. If you could try and submit a PR I'll review it and this seems like a feature we'll accept 👍

**Comment by alias1** [comment]
Hokai, will see what I can do when I find some spare time :)
