### ISSUE TITLE
Brewfile syntax needs escaping

### ISSUE THREAD

**Issue by Arcank** [Homebrew/homebrew-bundle#178]
Installing with `/` in the argument works:
```shell
14:36 ~ % brew install --HEAD homebrew/head-only/gitstats
Warning: homebrew/head-only/gitstats-HEAD already installed
```

But not when in a Brewfile:
```shell
14:36 ~ % brew bundle --file=Developer/dotfiles/Brewfile
Error: (eval):3: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
install --HEAD homebrew/head-only/gitstats
                       ^
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
~/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `instance_eval'
~/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `process'
~/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:21:in `initialize'
~/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `new'
~/homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
~/homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:72:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/homebrew/Library/brew.rb:22:in `require?'
~/homebrew/Library/brew.rb:93:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Can you paste the contents of your `Brewfile`?

**Comment by Arcank** [comment]
It was
```bash
install --HEAD homebrew/head-only/gitstats
```

Which I converted to correct syntax:
```bash
brew 'homebrew/head-only/gitstats', args: ['HEAD']
```

Now that works :)

**Comment by Arcank** [comment]
It's a bummer that the syntax in the Brewfile is to use `brew 'foo'` instead of `install 'foo'`. Doesn’t match with `cask install`, `tap`, etc.

**Comment by MikeMcQuaid** [comment]
It does match: https://github.com/Homebrew/homebrew-bundle#usage. You're probably confusing this with a previous (poor) implementation of `brew bundle` that simply appended `brew` to the beginning of each line and ran it.

**Comment by Arcank** [comment]
What I meant was that running `brew install foo` is converted into `brew 'foo'`, while `brew tap foo` is converted into `tap 'foo'`.
Why did the syntax change?

**Comment by MikeMcQuaid** [comment]
> What I meant was that running brew install foo is converted into brew 'foo', while brew tap foo is converted into tap 'foo'.

Ok, I see. As it's a DSL there's not a 1:1 mapping with Homebrew commands.

> Why did the syntax change?

It was effectively just a bash script and the current approach allows things like `brew bundle check` to be implemented and performant.
