### ISSUE TITLE
Extending the DSL to allow the installation of programming language packages like pip, npm, ect. ?

### ISSUE THREAD

**Issue by l00mi** [Homebrew/homebrew-bundle#179]
Sometimes I would be quite handy to let homebrew bundle install also tools from other package managers. I was thinking stuff like: 

`pip install jupyter`

**Comment by MikeMcQuaid** [comment]
This has been mentioned a few times but we'll pass on it as it's a scope creep; we want to focus on system-level dependencies as things like `pip` have their own `Brewfile` equivalents.

**Comment by l00mi** [comment]
True, a way to call these equivalents would be nice also ?

**Comment by MikeMcQuaid** [comment]
@l00mi I think this is a better pattern: https://github.com/github/scripts-to-rule-them-all. Have a separate script that calls them all.
