### ISSUE TITLE
Feature request: postinstall

### ISSUE THREAD

**Issue by SimenB** [Homebrew/homebrew-bundle#181]
Hey!

Would it be possible to add a postinstall to entries?

In my case, I'd like to install keybindings for [fzf](https://github.com/junegunn/fzf#using-homebrew) after installation (much like `do` in plug (https://github.com/junegunn/vim-plug#plug-options))

So it'd be something like `brew 'fzf', postinstall: ['/usr/local/opt/fzf/install']`.

**Comment by MikeMcQuaid** [comment]
I'm not sure I understand what this API is doing, is it just calling a command? If so, why is this not in the Homebrew formula `post_install`?

**Comment by SimenB** [comment]
You might not want to have it mess with the built in recursive search in the terminal. I.e. it's opt-in, extra features

**Comment by MikeMcQuaid** [comment]
I still don't really understand what you're requesting here? Can you elaborate a lot more?

**Comment by SimenB** [comment]
I would like to be able to specify a command to be automatically run after installation from `Brewfile`, similar to `restart_service: :changed`, e.g. `post_install: [:changed, '/usr/local/opt/fzf/install']` (I haven't written ruby outside of a single class 3 years ago, so the syntax is probably wrong), to do some post processing work. This work is optional and opt-in

Does that clarify it? I don't know how brew works, might be better to add it directly to the formula, and pass a flag during `brew install`?

**Comment by MikeMcQuaid** [comment]
Ok, I understand, thanks. In this case you're better to have a script call `brew bundle` and then run your command of choice. https://github.com/github/scripts-to-rule-them-all is the pattern I recommend. Thanks!
