### ISSUE TITLE
Multiple password prompts

### ISSUE THREAD

**Issue by nathany** [Homebrew/homebrew-bundle#187]
If I leave `brew bundle` to run, it pauses several times to prompt for my Mac password.

In my case, it was before installing each of the following casks:
alfred, vagrant, adobe-photoshop-lightroom, gog-galaxy

Is there any way that the password could be prompted just once?

**Comment by nathany** [comment]
see https://github.com/caskroom/homebrew-cask/issues/8817

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/8817 (thanks for the link). When they've fixed that we'll definitely accept a PR to handle this better.
