### ISSUE TITLE
bundle check should verify services have been started

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-bundle#188]
If `restart_service: true` or `start_service: true` are set then `brew bundle check` should ensure that all the services have been started by `brew services`.

**Comment by voanhduy1512** [comment]
I created a PR for this issue here https://github.com/Homebrew/homebrew-bundle/pull/204.

I don't see we use `start_service: true` anywhere in the project so I don't add support for that option. Another thing is do we need to check if `restart_service: changed`.
