### ISSUE TITLE
Snippet to dump Mac App Store apps with mas

### ISSUE THREAD

**Issue by asmod3us** [Homebrew/homebrew-bundle#190]
I was missing info on how to dump apps installed via Mac App Store. If you have [mas-cli](https://github.com/argon/mas), the following works to append these to a Brewfile:

```shell
mas list | awk '{ print "mas '"'"'" $2 "'"'"', id: " $1 }' >> Brewfile
```

**Comment by MikeMcQuaid** [comment]
Does `brew bundle dump` not already do this for you?

**Comment by asmod3us** [comment]
I'll check again later, but I don't think it did.
