### ISSUE TITLE
[dump] Record started services

### ISSUE THREAD

**Issue by rprimus** [Homebrew/homebrew-bundle#192]
Mon Aug  8 10:56:27 BST 2016

```brew bundle dump``` does not record which services are currently ```started```.

Would this not be required to duplicate a system via [strap](https://github.com/MikeMcQuaid/strap)?

**Comment by MikeMcQuaid** [comment]
I don't think it's required but making `brew bundle dump` set `restart_service: true` for those services currently running would be a nice feature, yeh 👍. Would accept a PR for this if you beat me to it.

**Comment by rprimus** [comment]
Mon Aug  8 13:10:09 BST 2016

Notes [to self] (from initial code reading):

1.  ```brew_services.rb```:   self.{stop,restart}: for services running as root, ```sudo``` is reguired.
2.  Create class member (for started services) with following: {f[:full_name], :user}
3. Create self.started? method to check member from (2.)
4.  Modify self.{stop,restart} to check user: if ```root```,  prepend system command with ```sudo```

**Comment by MikeMcQuaid** [comment]
Done in https://github.com/Homebrew/homebrew-bundle/issues/193, nice work @rprimus!
