### ISSUE TITLE
Issues with running thoughtbot:laptop setup / provisioning laptop

### ISSUE THREAD

**Issue by kapziel** [Homebrew/homebrew-bundle#198]
Error: undefined local variable or method `shell_profile' for #<Formulary::FormulaNamespacecc13dfc76e452057b82dd3b49090ab6c::Perl:0x007fc21daa4bf0>

Updating Homebrew formulae ...
Already up-to-date.
Succeeded in tapping thoughtbot/formulae
Succeeded in tapping homebrew/services
Error: undefined local variable or method `shell_profile' for #<Formulary::FormulaNamespacecc13dfc76e452057b82dd3b49090ab6c::Perl:0x007fc21daa4bf0>
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:71:in `caveats'
/usr/local/Library/Homebrew/formula.rb:1352:in `to_hash'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:69:in `block in formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:69:in `map'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:69:in `formulae_info'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:14:in `formulae'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:34:in `formula_names'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:77:in `installed_formulae'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:69:in `formula_installed?'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:93:in `installed?'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `install_change_state!'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:22:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:10:in `install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:54:in `block in install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:36:in `each'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:36:in `install'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:60:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Library/Homebrew/brew.rb:97:in `<main>'
failed

**Comment by kapziel** [comment]
For reference here's the thoughtbot script

https://github.com/thoughtbot/laptop

**Comment by MikeMcQuaid** [comment]
Should be fixed now, sorry for the pain.
