### ISSUE TITLE
brew bundle check fails

### ISSUE THREAD

**Issue by nandub** [Homebrew/homebrew-bundle#201]
`brew bundle check` fails with:

```
brew bundle can't satisfy your Brewfile's dependencies.
Install missing dependencies with `brew bundle install`.
```

Even after creating a new `Brewfile` using `brew bundle dump` command.  
https://gist.github.com/nandub/40eea91abc261c6333aa9fa2473545e9

**Comment by MikeMcQuaid** [comment]
Can you follow some requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by nandub** [comment]
I could but I'm not installing a formula but rather I'm running `brew bundle check` after a new `Brewfile` was created.

**Comment by MikeMcQuaid** [comment]
Can I see your `brew config` output?

**Comment by nandub** [comment]
```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e22610aedd550cb5577dd08cedb7a5609d0ff0b8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ae1f185d9f24d5cc82f9524df7288297a3a0c74
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 7.3 build 703
Git: 2.10.0 => /usr/local/bin/git
Perl: /Users/nandub/.plenv/shims/perl
Python: /Users/nandub/.pyenv/shims/python => /Users/nandub/.pyenv/versions/3.5.1/bin/python3.5
Ruby: /Users/nandub/.rbenv/shims/ruby => /Users/nandub/.rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_72, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

**Comment by nandub** [comment]
Take your time.  I know you busy working on brew.

**Comment by MikeMcQuaid** [comment]
Can I see your `Brewfile`? Thanks!

**Comment by technicalpickles** [comment]
Could this be related to https://github.com/Homebrew/homebrew-bundle/issues/176  ie handling renames?

**Comment by MikeMcQuaid** [comment]
@nandub Reping: can I see your `Brewfile`? Thanks!

**Comment by MikeMcQuaid** [comment]
Closing due to no response.

**Comment by sihil** [comment]
I seem to hit this, also when calling check - in my case `brew bundle check --global`. I've stripped my `.Brewfile` down by trial and error to be:
```
tap "cask room/versions"
cask "java8"
```

Ultimately this isn't strictly causing a problem, everything is happily installed but the message is disconcerting.

My `brew config` is:
```
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8307347987ce31a6c00bb262a7c1fc66ffa2e6ae
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 63009c4256dcd9f900405f5efcff94a08606f59e
Core tap last commit: 70 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_162
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
> cask "java8"

That should be `cask "caskroom/versions/java8"`. That's what `brew bundle dump` outputs and if I use that I cannot reproduce it locally.

**Comment by sihil** [comment]
Ah - interesting. It does work, it just produces the error. I'll switch over to using the long form (for all taps?).

**Comment by MikeMcQuaid** [comment]
> (for all taps?)

Yep.

> It does work

It works as long as the tap is tapped, yeh.
