### ISSUE TITLE
missing quotes in curl command

### ISSUE THREAD

**Issue by MoritzFago** [Homebrew/homebrew-bundle#202]
if I add `brew 'https://raw.githubusercontent.com/MoritzFago/homebrew-core/airport-bssid/Formula/airport-bssid.rb'` to my Brewfile it's unable to download the file due a problem with the curl command:
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --fail --progress-bar --remote-time --location --user-agent Homebrew/1.0.0\ (Macintosh;\ Intel\ macOS\ 10.12)\ curl/7.49.1 https://raw.githubusercontent.com/moritzfago/homebrew-core/airport-bssid/formula/airport-bssid.rb -o /Users/moritz/Library/Caches/Homebrew/Formula/airport-bssid.rb
```

**Comment by MikeMcQuaid** [comment]
It's because that URL 404s. We don't support using URLS like this in a `Brewfile`; create a `tap` and use that instead.
