### ISSUE TITLE
Brew Bundle error

### ISSUE THREAD

**Issue by mamsw** [Homebrew/homebrew-bundle#207]
When loading brewfile, I get the following error:

Error: (eval):38: syntax error, unexpected tIDENTIFIER, expecting end-of-input
cask '==> We'll set permissions properly so ...
               ^
Please report this bug:
    https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `instance_eval'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:29:in `process'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:21:in `initialize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `new'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:4:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:60:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'

**Comment by MikeMcQuaid** [comment]
What's the contents of your `Brewfile`?

**Comment by mamsw** [comment]
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
brew 'pkg-config'
brew 'libyaml'
brew 'openssl'
brew 'ansible'
brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'awscli'
brew 'readline'
brew 'bash'
brew 'smake'
brew 'cdrtools'
brew 'libtool'
brew 'jpeg'
brew 'libpng'
brew 'libtiff'
brew 'wxmac'
brew 'erlang'
brew 'gdbm'
brew 'git'
brew 'go'
brew 'icu4c'
brew 'leiningen'
brew 'sqlite'
brew 'python'
brew 'mercurial'
brew 'node'
brew 'rebar'
brew 'unixodbc'
brew 'wget'
brew 'homebrew/dupes/openssh'
cask 'Uninstalling brew-cask... (4 files, 7.9K)'
cask '==> Creating Caskroom at /usr/local/Caskroom'
cask '==> We'll set permissions properly so we won't need sudo in the future'

**Comment by mamsw** [comment]
I removed the cask comments below and its working. Thank you for your assistance.

cask 'Uninstalling brew-cask... (4 files, 7.9K)'
cask '==> Creating Caskroom at /usr/local/Caskroom'
cask '==> We'll set permissions properly so we won't need sudo in the future'

**Comment by MikeMcQuaid** [comment]
CC @reitermarkus @jawshooah for a heads up that Cask prints this message on `brew list` on stdout; should probably be stderr: https://github.com/Homebrew/homebrew-bundle/blob/b67dc7ce236118059145b729547208f732e75f79/lib/bundle/cask_dumper.rb#L9
