### ISSUE TITLE
dry-run flag

### ISSUE THREAD

**Issue by helgi** [Homebrew/homebrew-bundle#220]
It would be nice being able to run `brew bundle dump --force --dry-run` and get an output of the diff between the current file and what would be written

I know I could write a little `brew-bundle-diff` that outputted the current state to a `tmp` file and did a diff for me but having that built in would be nice :)

**Comment by MikeMcQuaid** [comment]
I don't think `--force --dry-run` makes sense. To get a similar diff I have my `Brewfile` in a git repository and use `git diff`.

**Comment by helgi** [comment]
`--force` was just there as that as what I used `brew bundle` with last - `--dry-run` could be used without it.

I understand that you can get it by storing your file in git, but I am not. I'll just stick to using `--file` to `/tmp` and do a local `diff -u` against my main file.
