### ISSUE TITLE
Should `brew bundle dump` dump only packages in `brew list` or all installed packages?

### ISSUE THREAD

**Issue by danielcompton** [Homebrew/homebrew-bundle#236]
My expectation when running `brew bundle dump` is that it would make a Brewfile which contains all of the packages that I have installed by running `brew install x`. However the Brewfile that was created also includes the dependencies of top level packages I have installed, like 

```
brew 'libebml'
brew 'libevent'
brew 'libmagic'
brew 'libmatroska'
brew 'libzip'
```

I'd prefer not to have these packages in my Brewfile as

1.  Homebrew can figure out dependencies at install time
2. My conceptual understanding of a Brewfile is that it lists the software I want installed. Including package dependencies adds noise to the Brewfile for no benefit (as far as I can tell?). It also means that if I no longer need a package, I can't just remove it from the Brewfile, I also need to search for and remove its dependencies.

Would it be possible to add an option to only dump top level installed packages? It's entirely possible I'm missing something important here though.

**Comment by MikeMcQuaid** [comment]
> Would it be possible to add an option to only dump top level installed packages?

We don't currently have a way of figuring this out; Homebrew does not "know" this information. Additionally, what if you manually install a package because you need it, install something that depends on it later and then remove the thing that depended on it. Should it be kept or removed?

**Comment by danielcompton** [comment]
> We don't currently have a way of figuring this out; Homebrew does not "know" this information. 

That's the part that I was missing :)

**Comment by MikeMcQuaid** [comment]
Thanks for understanding! Note this is something I will probably want to do eventually when it becomes possible.

**Comment by RichardBronosky** [comment]
Using `brew leaves` would have less noise than `brew list`. My concern is that I have a package that **used to have** excessive dependencies. After a major code refactor, most of the dependencies are gone. Unfortunately, `brew bundle` makes it very difficult to get rid of those dependencies unless every `brew bundle` user edits their `Brewfile`.

It's like the problem you get when you remove code from git by editing git history rather than making a forward commit that does an rm. #shudder

**Comment by MikeMcQuaid** [comment]
> Using brew leaves would have less noise than brew list.

As I've said above: it would also be wrong.

**Comment by RichardBronosky** [comment]
Regarding the scenario you outlined: The bundle file should omit anything that isn't top level. It's not difficult to install something you need it a race condition edge case caused it to be omitted. What is more difficult is identifying and removing clutter. Brew files are for when you are starting fresh on a new environment. I think it's best to err on the side of cleanliness.

**Comment by MikeMcQuaid** [comment]
> The bundle file should omit anything that isn't top level.

Repeating myself again: no, it shouldn't as this would produce the wrong behaviour. If your project has e.g. a RubyGem that links against OpenSSL and MySQL which depends on OpenSSL then under your strategy OpenSSL would be omitted from the Brewfile. MySQL gets an upgrade, uses SecureCrypto so no longer depends on OpenSSL so it's no longer installed and now your RubyGem installation is broken for all fresh installs.

> Brew files are for when you are starting fresh on a new environment.

No, they are not (and, diplomatically, it's a little silly telling the primary maintainer of this project what it is or is not for: I'm the one who decides that). That's a single use-case of which there are multiple. 

Again, the above example can be repeated for a fresh environment. You need OpenSSL, it gets omitted and then on a clean system install it's not installed any more and things break.

Look, I understand there's a desire for this feature and, long-term, I may think about implementing it. It will require, however, significant, non-trivial changes in both Homebrew/brew and Homebrew/homebrew-bundle. In the meantime there's nothing stopping you from manually editing the output of `brew bundle dump` (or not using it all) to hand-craft your `Brewfile`s just how you like them.

**Comment by MikeMcQuaid** [comment]
> I think it's best to err on the side of cleanliness.

And to address this last point: no, it's always better to err on the side of correctness and reliability.

**Comment by RichardBronosky** [comment]
Well, for now this works for me. I'll drop it here for the people who will get here via Google.

```
# The following line adds the convenience of creating the file by pasting into a terminal
cat > brewstrainer.awk << EOF # omit this line and the last if not creating the file be pasting into a terminal
# Usage: brew bundle dump; brew leaves | awk -f brewstrainer.awk - Brewfile

# read file1 into an array (stdin via - in usage above)
FNR == NR {
    leaves["'" $1 "'"] = ""
    next
}

# skip lines that begin with brew but weren't in file1
$1 == "brew" {
    if (! ($2 in leaves))
        next
}

# print everything that's left
{
    print $0
}
EOF # omit this line if not creating the file be pasting into a terminal
```

**Comment by stealthybox** [comment]
@RichardBronosky here's a version of your `cat` heredoc that fixes the unescaped `$` signs:
```bash
cat << EOF > brewstrainer.awk
# Usage: brew bundle dump; brew leaves | awk -f brewstrainer.awk - Brewfile

# read file1 (stdin via - in usage above) into an array
FNR == NR {
    leaves["'" \$1 "'"] = ""
    next
}

# skip lines that begin with brew but weren't in file1
$1 == "brew" {
    if (! (\$2 in leaves))
        next
}

# print everything that's left
{
    print \$0
}
EOF
```

Thanks for posting it!

**Comment by stealthybox** [comment]
Seems like `brew bundle dump` already ignored a bunch of dependencies for me anyway:
```
brew list | wc -l
     194
cat Brewfile | grep '^brew' | wc -l
      84
cat Brewfile.leaves | grep '^brew' | wc -l
      75
brew leaves | wc -l
      71
```

Most of the lib deps for my packages were left out of the Brewfile.
It's probably not necessary to filter the output using `brew leaves`.

**Comment by MikeMcQuaid** [comment]
We don't output dependencies unless they were specifically installed by the user. This is an old issue and the discussion above is outdated.
