### ISSUE TITLE
`brew bundle` not working from launchd script

### ISSUE THREAD

**Issue by n8henrie** [Homebrew/homebrew-bundle#237]
In spite of being a Homebrew user for several years, I hadn't heard of `brew bundle` until just recently. I've been using a `launchd` script to backup my Homebrew stuff -- runs nightly, and basically does `brew list > brew.txt`, `brew cask list > brew_cask.txt`, you get the idea. These are output to a git repo with a subdirectory specific to the host, and the script makes a daily pull, autocommit, and push.

Coming across `brew bundle`, it seemed like a great way to simplify the process, but for some reason I can't get it to work.

Here's the relevant portion of the script, with the only new line being the one with the `brew bundle` command:

```bash
backup_homebrew() {
  /usr/local/bin/brew list > "${subdir}"/brew.txt
  /usr/local/bin/brew cask list > "${subdir}"/brew_cask.txt
  HOMEBREW_NO_AUTO_UPDATE=1 /usr/local/bin/brew tap > "${subdir}"/brew_tap.txt
  /usr/local/bin/brew bundle dump --force --file="${subdir}"/Brewfile
}
```

Curiously, the script runs fine when run interactively and creates `Brewfile` at the expected path (as well as the other files listed above), but from my launchd script, I get no `Brewfile` and this in my stderr output:

```
Error: No such file or directory - brew
```

Googling the error brings up several threads on `brew cask`, Windows line endings, and ruby env / path -- which I suspect may be the culprit, having had similar `$PATH` issues with launchd scripts in the past. However, those issues were generally resolved by using the full path to an executable, which is why I used `/usr/local/bin/brew` instead of just `brew` from the beginning.

- OSX 10.12.1
- Homebrew 1.1.0
- Nothing new or unusual in `brew doctor`

**Comment by MikeMcQuaid** [comment]
What user does the script run as and what's in the `$PATH`? You likely need to add `/usr/local/bin/` to your PATH in the script.

**Comment by n8henrie** [comment]
Thanks for the quick response.

Running the `launchctl` commands without `sudo` and `${HOME}` evaluates as expected, so I presume the user is me.

Why would I need to add `/usr/local/bin` to the path if I'm specifying the full path `/usr/local/bin/brew` already? Especially if all the other commands (`brew list`, `brew cask list`, and `brew tap`) are working?

**Comment by MikeMcQuaid** [comment]
> Why would I need to add /usr/local/bin to the PATH if I'm specifying the full path /usr/local/bin/brew already?

Homebrew doesn't automatically add itself to its PATH. `brew bundle` calls `brew` as a separate process in order to run Homebrew. Arguably it could automatically add itself to the PATH.

**Comment by n8henrie** [comment]
Sure enough, changing the line to `PATH=/usr/local/bin:${PATH} /usr/local/bin/brew bundle dump --force --file="${subdir}"/Brewfile` fixes the issue.

**Comment by MikeMcQuaid** [comment]
In the case of your script adding `PATH=/usr/local/bin:${PATH}` on the first line of `backup_homebrew()` would allow you to drop the full command scoping anyway and save you some lines. You could always put everything in the function in a subshell (wrap with `( )`) if you want to avoid it being set after the function has returned.

**Comment by n8henrie** [comment]
Fair enough. Thanks for your help on this!
