### ISSUE TITLE
Update Brewfile while preserving arguments

### ISSUE THREAD

**Issue by Saklad5** [Homebrew/homebrew-bundle#238]
I’m looking to use `brew bundle` update all of my software with launchd every night. However, checking current programs for updates is impossible without overwriting the existing Brewfile, and doing so would erase all of my arguments for Casks and such.

Could a flag be added to `brew bundle dump` that would remove uninstalled programs from the Brewfile, add new ones, and preserve arguments that existed on programs that remain installed?

**Comment by MikeMcQuaid** [comment]
Sorry, that would be considerable harder than the current `dump` logic. The better approach would be to ensure the Cask arguments are dumped. I'm not sure how/where they are stored but I'd definitely review and likely accept a PR that dumped them to the `Brewfile`.
