### ISSUE TITLE
Dump to Brewfile in alphabetical order

### ISSUE THREAD

**Issue by molovo** [Homebrew/homebrew-bundle#242]
I use `brew bundle dump --global --force` to generate a brewfile which I use to keeps my macs in sync. Every time this is generated I get superfluous changes in the file as each of my machines outputs the installed taps/brews/casks in a different order. This either means a ton of noise in the commit log of my dotfiles repo, or difficulty distinguishing between new packages that I want to sync, and lines which have just been moved (especially as my Brewfile has ~300 lines).

It's a really minor non-issue, but how difficult would it be to output each of the taps/brews/casks to the Brewfile in alphabetical order, to reduce this kind of noise?

**Comment by MikeMcQuaid** [comment]
Alphabetical order would cause problems because then it'll try and install dependencies twice. We've tried a few approaches to avoid things "moving" so I'd consider accepting a PR to improve that further.
