### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Tombar** [Homebrew/homebrew-bundle#252]
Hello,

Kudos for Homebrew-bundle it is such a great tool! 

My question is how to define in the Brewfile brews like `homebrew/php/php71`. which normally installs with `brew install homebrew/php/php71`

I've tried all of the below options which don't work

```
brew 'php71'
brew 'php/php71'
brew 'homebrew/php/php71'

tap 'php71'
tap 'php/php71'
tap 'homebrew/php/php71'
```

Regards!

M

**Comment by MikeMcQuaid** [comment]
`brew 'homebrew/php/php71'` should work but if not:
```
tap 'homebrew/php'
brew 'homebrew/php/php71'
```
should.

Just FYI, "don't work" doesn't give me any information I can use to help you or fix this.
