### ISSUE TITLE
Output MAS list to Brewfile in alphabetical order

### ISSUE THREAD

**Issue by aheckler** [Homebrew/homebrew-bundle#256]
Perhaps the output of `mas list` in the Brewfile should at least be in alphabetical order? To my knowledge, the App Store doesn't have a concept of dependencies, so the objection mentioned in #242 doesn't apply.

This would avoid needless changes if, for example, you have your Brewfile in a git repo.

**Comment by MikeMcQuaid** [comment]
@aheckler That makes sense to me. Could you try to create a pull request? Happy to help if needed. Thanks!

**Comment by aheckler** [comment]
@MikeMcQuaid I don't actually know any Ruby, so I'd just be copy/pasting from StackOverflow. :P I can still try if you'd like.

**Comment by MikeMcQuaid** [comment]
Copy-paste away 😁. We all start somewhere!
