### ISSUE TITLE
"mas" being uninstalled when using "brew bundle cleanup --force"

### ISSUE THREAD

**Issue by MetalArend** [Homebrew/homebrew-bundle#260]
You can use mas inside your bundle file, but when you use `brew bundle cleanup --force` it uninstalls mas, as it is nowhere being listed inside the bundle file. Is there a way to list it? Or to detect in bundle that mas is being used, so it should not uninstall it?

**Comment by MikeMcQuaid** [comment]
`brew bundle cleanup --force` should only be used with the output of `brew bundle dump` which will include `mas` if `brew bundle` installs it. Sorry!

**Comment by MetalArend** [comment]
So how do I include mas? What package do I tap? Even the mas documentation did not mention that. I'll go try to do a brew bundle dump... At least it might be interesting to make that clear in the documentation, and show some examples as what else might be possible, because AFAIK I could not find any way to reference mas anywhere in my file.

Just to point it out: it seems to be hard to find some correct information on the use of your amazing work. There's lots and lots of information on "brew bundle", but as far as I can see, "bundle" has been deprecated, removed, and your bundle was named brewler and then renamed. It makes things really difficult. Are there any plans to add some more documentation, instead of only that single (self-explaining?) example in the README.md? Or did I miss it somewhere?

Keep up the amazing work, and thanks for all the effort!!!

**Comment by MikeMcQuaid** [comment]
> So how do I include mas?

`brew bundle dump` after installing something with it or `brew install mas`.

> Are there any plans to add some more documentation, instead of only that single (self-explaining?) example in the README.md?

Not currently but I'll consider in future, thanks.



> Keep up the amazing work, and thanks for all the effort!!!

Thanks for the kind words ❤️

**Comment by MetalArend** [comment]
I was looking for a way to include mas, in a way that would avoid uninstalling it with `brew bundle cleanup --force`. After doing a dump, it turns out the easiest way seems to add a line into the Brewfile: `brew 'mas'`.
