### ISSUE TITLE
`brew bundle dump` misses packages

### ISSUE THREAD

**Issue by brainsik** [Homebrew/homebrew-bundle#270]
Running `brew bundle dump` missed the `rust` and `sqlite` packages.

```
$ brew bundle dump
$ brew bundle cleanup
Would uninstall formulae:
rust                                                                                                   sqlite
```

```
$ brew --version
Homebrew 1.2.0
Homebrew/homebrew-core (git revision 107d9; last commit 2017-05-12)
```

**Comment by MikeMcQuaid** [comment]
It's not missed `sqlite`, it intentionally omits dependencies you haven't manually installed. Similarly with `rust` it's a build-time dependency for something else so can be cleaned up. If you wish this to not happen you can run `brew install rust` after it's already been installed which will consider it manually installed. Note this behaviour matches apt-get. Thanks!
