### ISSUE TITLE
Error: Unknown command: bundle

### ISSUE THREAD

**Issue by marcoc84** [Homebrew/homebrew-bundle#281]
Hi,

after installing **Homebrew/bundle** with: "brew tap Homebrew/bundle"

brew bundle is still not available.

<img width="439" alt="screen shot 2017-08-02 at 4 06 57 pm" src="https://user-images.githubusercontent.com/1436181/28859829-148b15e8-779d-11e7-9293-e0e62537b8ac.png">

**Comment by MikeMcQuaid** [comment]
What does your `brew config` output?

**Comment by marcoc84** [comment]
<img width="642" alt="screen shot 2017-08-03 at 9 09 21 am" src="https://user-images.githubusercontent.com/1436181/28898883-80290614-782b-11e7-9834-b5d7413df749.png">

**Comment by marcoc84** [comment]
Any thoughts?

Thanks

**Comment by marcoc84** [comment]
Probably some permission issues. 

An untap/tap fixed the issue.

Cheers

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted.
