### ISSUE TITLE
`dump` does not appear to preserve `args:` for tapped forumlae

### ISSUE THREAD

**Issue by aramprice** [Homebrew/homebrew-bundle#286]
I'm seeing an issue where I have a tapped formula (`cloudfoundry/tap/bosh-cli`) which is installed with `--without-bosh2` but this option is not being recorded in the Brewfile.

```
brew info bosh-cli
cloudfoundry/tap/bosh-cli: stable 2.0.33
New BOSH CLI (beta)
https://bosh.io/docs/cli-v2.html
/usr/local/Cellar/bosh-cli/2.0.33 (3 files, 25.8MB) *
  Built from source on 2017-08-18 at 18:31:22
From: https://github.com/cloudfoundry/homebrew-tap/blob/master/bosh-cli.rb
==> Requirements
Required: arch ✔
==> Options
--with-bosh2
	Rename binary to 'bosh2'. Useful if the old Ruby CLI is needed.
```

When I run `bundle dump --force` I see the following change.

```diff
brew "vim", args: ["with-luajit"]
-brew "cloudfoundry/tap/bosh-cli", args: ["without-bosh2"]
+brew "cloudfoundry/tap/bosh-cli"
```

Perhaps this is something with the formula itself since it appears that `brew bundle dump` correctly preserves `with-luajit` from `vim`.

**Comment by MikeMcQuaid** [comment]
This is because `without-bosh2` is on by default and `args` only stores the non-default arguments.

**Comment by aramprice** [comment]
@MikeMcQuaid thanks for the clarification, sorry for the clutter.

**Comment by MikeMcQuaid** [comment]
No worries; thanks for the humility @aramprice!
