### ISSUE TITLE
brew bundle cleanup is uninstalling fonts - which **are still in my Brewfile**

### ISSUE THREAD

**Issue by dstroot** [Homebrew/homebrew-bundle#291]
brew bundle cleanup is uninstalling fonts - which **are still in my Brewfile**.   Then the next time I run brew bundle they get installed. then I run brew bundle cleanup and they get uninstalled.  I can't figure out why cleanup thinks they should be uninstalled.  

```
❯ brew bundle cleanup --file=$HOME/.Brewfile
Would uninstall casks:
caskroom/fonts/font-droid-sans-mono                  caskroom/fonts/font-iosevka
caskroom/fonts/font-hack                             caskroom/fonts/font-monoid
caskroom/fonts/font-hasklig                          caskroom/fonts/font-source-code-pro
caskroom/fonts/font-input
```

Brewfile:
```
# homebrew apps
tap 'homebrew/bundle'
tap 'homebrew/versions'
tap 'homebrew/core'
tap 'go-delve/delve'
# -------------------------
brew 'bash-completion'
brew 'git'

brew 'hugo'
brew 'mackup'
brew 'n'
brew 'jq'
brew 'gpm'
...

# install fonts
tap 'caskroom/fonts'
# --------------------------
cask 'font-droid-sans-mono'
cask 'font-hack'
cask 'font-hasklig'
cask 'font-monoid'
cask 'font-source-code-pro'
cask 'font-iosevka'
cask 'font-input'
```

**Comment by MikeMcQuaid** [comment]
> cask 'font-droid-sans-mono'

What if you make this `caskroom/fonts/font-droid-sans-mono`?

**Comment by admhlt** [comment]
Mike: That seems to fix an issue I had where fonts were being reinstalled every time I ran `brew bundle`. If I list them as `caskroom/fonts/font-droid-sans-mono`, I don't get that issue.

Thanks!

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted.

**Comment by dstroot** [comment]
That worked for me also.  Thanks Mike.  What was the logic/reasoning on why this changed? (so I have a better understanding of how this works) My other casks were unaffected - only fonts.

Cheers!

**Comment by MikeMcQuaid** [comment]
@dstroot This was a product of using full cask names correctly in https://github.com/Homebrew/homebrew-bundle/pull/278 which would avoid clashes/inconsistency between taps. Sorry for the pain!

**Comment by dstroot** [comment]
Got it!  Thanks - the reasoning makes a lot of sense.

**Comment by dstroot** [comment]
For anyone landing here now the current way to do this is:

```sh
# install fonts
tap 'homebrew/cask-fonts'
# --------------------------
cask 'font-hack'
cask 'font-hasklig'
cask 'font-monoid'
cask 'font-source-code-pro'
cask 'font-iosevka'
cask 'font-input'
```
