### ISSUE TITLE
`brew bundle cleanup` wants to clean up dependencies of formulae from custom taps

### ISSUE THREAD

**Issue by wendorf** [Homebrew/homebrew-bundle#301]
If `vitorgalvao/tiny-scripts/cask-repair` is in your Brewfile, `hr` will be installed because it is a dependency. However, if you then `brew bundle cleanup --force`, `hr` will be uninstalled.

This is because `Bundle::Commands::Cleanup#formulae_to_install` constructs `kept_formulae` and `current_formulae` differently. `kept_formulae[i][:name]` is the formula's `full_name`, but `current_formulae[i][:name]` is the "short" `name`. When the two names are compared in `#recursive_dependencies`'s `current_formulae.find { |f| f[:name] == name }`, the names do not match and the dependency is not found.

**Comment by MikeMcQuaid** [comment]
Nice spot. Would you mind submitting a pull request for the fix?
