### ISSUE TITLE
bundle dump w/ mas resulting in segmentation fault

### ISSUE THREAD

**Issue by jamesdh** [Homebrew/homebrew-bundle#308]
Trying to perform `brew bundle dump` and getting the following error: 

> sh: line 1: 18965 Segmentation fault: 11  mas list 2> /dev/null

Independently running `mas list` correctly outputs installed MAS apps.

**Comment by MikeMcQuaid** [comment]
I can't reproduce this locally I'm afraid. Try `brew reinstall mas`.

**Comment by jamesdh** [comment]
Aww snap. Yea that fixed it. It looks like it was the High Sierra installer causing the issue as it doesn't have an ID. After updating mas it now correctly lists the installer (just minus an ID). 

Actually, this might be a different issue. Look at the line it adds to the Brewfile in this case:

`mas "macOS High Sierra", id: Install`

When I do `mas list`, this is how it appears within some other items:
```
595191960 CopyClip (1.9)
 Install macOS High Sierra (13105)
803453959 Slack (2.9.0)
```

**Comment by MikeMcQuaid** [comment]
@jamesdh Ok. Would you consider submitting a PR to address that case?

**Comment by jamesdh** [comment]
@MikeMcQuaid will do

**Comment by jamesdh** [comment]
Decided not to bother because A) the OSX installers aren't typically something you'd want to keep around B) am unable to find anything else that recreates this issue. 

Either way, thanks for the response @MikeMcQuaid!

**Comment by paulp** [comment]
For clarity in posterity, see mas-cli/mas#82 regarding the seg fault.

**Comment by MikeMcQuaid** [comment]
@paulp I cannot reproduce this locally with the installer installed. We will accept a pull request to resolve this (likely just not including anything in a dump missing an ID).

**Comment by paulp** [comment]
Re #321, it's a different bug - as I said, "the bug in bundle being masked by the bug in mas" - regardless of your agreement, it's childish and hostile to immediately close and lock the ticket. Sorry to have bothered you with my effort.

**Comment by MikeMcQuaid** [comment]
@paulp Calling someone who maintains software you use "childish and hostile" because they don't run their issue tracker in the way that you would like (not keeping issues open that we don't plan to work on) is rude. I've invested significantly more effort into this project (and Homebrew itself) over a long period of time than you or, at this point, frankly anyone. Would consider apologising?

**Comment by MikeMcQuaid** [comment]
@paulp I'll take that as a no, then.

**Comment by MikeMcQuaid** [comment]
Anyone else who hits this: we'll consider accepting a PR for fixing the case where `mas` does not output IDs.
