### ISSUE TITLE
Update/Upgrade of Xcode didn't work as expected via `mas` via `brew bundle`

### ISSUE THREAD

**Issue by janpio** [Homebrew/homebrew-bundle#309]
README says:

> If a dependency is already installed and there is an update available it will be upgraded.

But:

```
Virtuals-Mac:~ foo$ brew bundle
Using homebrew/core
Using homebrew/bundle
Using caskroom/cask
Using mas
Using google-chrome
Using Xcode
Using visual-studio-code
Using sourcetree
Using android-studio
Using genymotion
Installing TextWrangler
Using dockutil
Using fastlane
Homebrew Bundle complete! 13 Brewfile dependencies now installed.
Virtuals-Mac:~ foo$ mas outdated
497799835 Xcode (9.1 -> 9.2)
Virtuals-Mac:~ foo$ mas upgrade
Upgrading 1 outdated application:
Xcode (9.2)
==> Downloading Xcode
------------------------------------------------------------ 0.0% Waiting
```

Did I do something wrong or shouldn't the Xcode upgrade already have happened with `brew bundle`?

`Brewfile`:
```
tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"

# Config
cask_args appdir: "/Applications"

# Internal
brew "mas"

# Basics
cask "google-chrome"

# Programming
mas "Xcode", id: 497799835
cask "visual-studio-code"
cask "sourcetree"
cask "android-studio"
mas "TextWrangler", id: 404010395

# CLI Tools
brew "dockutil"
cask "fastlane"

# Special cases that will fail first!
cask "genymotion"
```

**Comment by MikeMcQuaid** [comment]
Xcode is not a dependency so will not be upgraded. Is it listed in your `Brewfile`? If it is and it is not upgraded: that could be something cool to submit a pull request implementing.

**Comment by janpio** [comment]
`<details>` tag seems to have hidden my `Brewfile` to well, I edited my post so the `Brewfile` is visible.

Doesn't mean having `mas "Xcode", id: 497799835` in there that it is a dependency?

**Comment by MikeMcQuaid** [comment]
> Why a pull request - shouldn't this already work if I believe the README?

We don't ever attempt to use `mas upgrade` but I think we should so reopening this.

**Comment by janpio** [comment]
Ok, thanks for confirming this is indeed unwanted behavior. 

Hope someone that actually knows ruby can take a shot at solving this.
