### ISSUE TITLE
Output of installed software is swallowed - How to handle?

### ISSUE THREAD

**Issue by janpio** [Homebrew/homebrew-bundle#310]
I added `cask "fastlane"` to my `Brewfile`.
`brew bundle` ran as expected and installed it.
But it didn't work, as the manual steps that are normally output if needed, weren't done:

```
...
==> Couldn't detect shell config file (bash - ~/.bash_profile)
==> Please add the following line to your bash profile:
==> 
==> export PATH="$HOME/.fastlane/bin:$PATH"
...
```

Similar situation with `brew "nvm"`. Normally it outputs these instructions:

```
Virtuals-Mac:~ foo$ brew reinstall nvm
==> Reinstalling nvm 
==> Downloading https://github.com/creationix/nvm/archive/v0.33.6.tar.gz
Already downloaded: /Users/foo/Library/Caches/Homebrew/nvm-0.33.6.tar.gz
==> Caveats
Please note that upstream has asked us to make explicit managing
nvm via Homebrew is unsupported by them and you should check any
problems against the standard nvm install method prior to reporting.

You should create NVM's working directory if it doesn't exist:

  mkdir ~/.nvm

Add the following to ~/.bash_profile or your desired shell
configuration file:

  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

You can set $NVM_DIR to any location, but leaving it unchanged from
/usr/local/opt/nvm will destroy any nvm-installed Node installations
upon upgrade/reinstall.

Type `nvm help` for further information.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/nvm/0.33.6: 7 files, 134.9KB, built in 4 seconds
Virtuals-Mac:~ foo$ 
```

How should something like this be handled? 
`homebrew-bundle` swallowing all output is certainly normally useful, but what about cases like this?

**Comment by MikeMcQuaid** [comment]
> homebrew-bundle swallowing all output is certainly normally useful, but what about cases like this?

This is either-or, unfortunatley.. `brew bundle --verbose` may print what you desire and if it doesn't: we'd welcome a PR to do so.

**Comment by janpio** [comment]
`--verbose` does output more, will check if this includes these.

Specific reason this is not documented or can I submit a PR?

Might there be a way for `brew bundle` to "collect" these "Caveats" outputs and echo them when all installation is finished?

**Comment by MikeMcQuaid** [comment]
It's documented in `brew bundle --help`.

> Might there be a way for brew bundle to "collect" these "Caveats" outputs and echo them when all installation is finished?

Nah, that's going to be really messy.

**Comment by janpio** [comment]
> It's documented in brew bundle --help.

Which itself is not documented in the README ;)

> Nah, that's going to be really messy.

Thought so. I'll try to write down the "manual steps" somehow.

(Sorry for putting your software through this noob treatment by the way - usually not a Mac user, which is why `homebrew-bundle` could also be so super useful to get a consistent setup for iOS development)

**Comment by MikeMcQuaid** [comment]
> Which itself is not documented in the README ;)

I think that's pretty redundant given pretty much all Unix software supports `--help`.

> (Sorry for putting your software through this noob treatment by the way - usually not a Mac user, which is why homebrew-bundle could also be so super useful to get a consistent setup for iOS development)

No worries, it's always good to get people with a different take to try this stuff out. It may seem like I'm discounting your problems but it's something I'll remember if more people have similar problems.
