### ISSUE TITLE
installed cask "java8" is not recognized as installed, installation fails

### ISSUE THREAD

**Issue by janpio** [Homebrew/homebrew-bundle#312]
I successfully installed the `java8` cask (from the caskroom/versions tap) via `brew bundle` before.
When running `brew bundle --verbose` now it doesn't seem to recognize it as already installed though:

```
Virtuals-Mac:~ foo$ brew bundle --verbose
...
Skipping install of caskroom/versions tap. It is already installed.
Using caskroom/versions
...
Installing java8 cask. It is not currently installed.
Warning: Cask 'java8' is already installed.

To re-install java8, run:
  brew cask reinstall java8
Installing java8
...
Skipping install of gradle formula. It is already up-to-date.
Using gradle
...
Homebrew Bundle complete! 17 Brewfile dependencies now installed.
```
All the others dependencies are recognized as already installed as they should, see `gradle` as an example.

If I run the install command manually, I directly get an error:
```
Virtuals-Mac:~ foo$ brew cask install java8
Warning: Cask 'java8' is already installed.

To re-install java8, run:
  brew cask reinstall java8
```

In the Brewfile it looks like this:
```
cask "java8"
```

Is this a problem of bundle with this specific cask or some general behavior I missed?

**Comment by ilovezfs** [comment]
Try referring to it as `cask "caskroom/versions/java8"`

**Comment by janpio** [comment]
Thanks, that fixed the problem!

```
Skipping install of caskroom/versions/java8 cask. It is already installed.
Using caskroom/versions/java8
```

Can you explain why this is necessary? 
Was I using the wrong command in the firs place?
