### ISSUE TITLE
brewfile - skip specific packages if already installed

### ISSUE THREAD

**Issue by tleunen** [Homebrew/homebrew-bundle#313]
Currently, if a package is already installed when running `brew bundle`, it fails. Is there any way to skip those packages instead of failing?

**Comment by MikeMcQuaid** [comment]
> Currently, if a package is already installed when running brew bundle, it fails.

This is not the case.

**Comment by tleunen** [comment]
But it exits with a non zero code when something is already installed, right? Maybe specific to a cask install?

**Comment by MikeMcQuaid** [comment]
> But it exits with a non zero code when something is already installed, right?

Nope.

> Maybe specific to a cask install?

Works for me.

You'll need to figure out this issue yourself, I'm afraid.

**Comment by LandonSchropp** [comment]
@MikeMcQuaid I run into this issue when packages are already installed outside of Homebrew.

```
Installing google-chrome has failed!
Installing dropbox has failed!
Homebrew Bundle failed! 2 Brewfile dependencies failed to install.
```

If I'm running an individual `brew cask install` command, that's fine. However, for a `brew bundle` install my ideal behavior would be for the command to exit with `0`.

**Comment by MikeMcQuaid** [comment]
@LandonSchropp Remove them from your `Brewfile`.
