### ISSUE TITLE
"brew bundle --global" freezes my Mac (mostly)

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/homebrew-bundle#315]
My ~/.Brewfile is this: https://github.com/ahmetb/dotfiles/blob/2ec355ca7d9b3a00c6cdedd721d5e42fcfc49b4a/.Brewfile

(I can reproduce the following problem on two different Mac hardware running on two different macOS versions.)

Right now on my machine most of the packages in brewfile are installed, but I regularly `brew bundle --global` manually.

I noticed some odd behavior about a month ago. After running `brew bundle --global`, after a few minutes (it's hard to tell where) **my Mac starts acting weirdly**:

- No new applications can be launched (they keep jumping in the Dock), so can't even launch `Terminal.app` to debug with ps/pstree/top.
- iTerm freezes, can't even change tabs
- another iTerm window showing `htop` shows 99% CPU on all 4 cores, now frozen, too
- already open apps (like Chrome) keeps working (for Chrome, I can open close tabs and browse just fine)
- I can launch "Activity Monitor.app", but it's not showing any processes or CPU/memory stats, [it's an empty UI](https://user-images.githubusercontent.com/159209/34632478-84f9a0da-f22a-11e7-8b6b-b8905cf6ce24.png
)

The only solution to save my computer from this is to Reboot.

I tried stuff like `brew bundle --global --verbose | tee debug.log` to capture what the hell is going on and if a particular package is causing this.

Did you ever hear about something like this? How can I debug this reliably?

**Comment by ilovezfs** [comment]
Sounds like https://github.com/hishamhm/htop/issues/682

**Comment by ahmetb** [comment]
But the problem happens if I don’t launch hterm at all, too. (Will double check after force rebooting.) However, I observe many of the mentioned symptoms:

https://github.com/hishamhm/htop/issues/682#issuecomment-337475227
https://github.com/hishamhm/htop/issues/682#issuecomment-336585781

**Comment by ilovezfs** [comment]
I assume you mean `htop` not `hterm`

**Comment by ahmetb** [comment]
Yeah I meant htop, sorry.

htop was indeed the culprit here. If I don't use htop to watch the progress, it worked just fine. Such an odd bug.

**Comment by ilovezfs** [comment]
@ahmetb yeah it's likely a macOS 10.13 kernel bug because a user process like htop shouldn't be able to bring down the whole system like that.
