### ISSUE TITLE
EOS.undent deprecated, and segfault

### ISSUE THREAD

**Issue by jschank** [Homebrew/homebrew-bundle#316]
I am using fishshell.

```
brew --version
Homebrew 1.5.1
Homebrew/homebrew-core (git revision f66a0; last commit 2018-01-23)

```
Receiving this error when I run
`brew bundle dump --force --file=~/Dropbox/Apps/"$hostname"_Brewfile`

```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:87:in `block in formulae_info'
Please report this to the homebrew/bundle tap!

sh: line 1: 67189 Segmentation fault: 11  mas list 2> /dev/null
```

and, $hostname evaluates to:
`sadmustard.corp.local`

**Comment by kyoshidajp** [comment]
Related #308. Try `brew reinstall mas`.

**Comment by MikeMcQuaid** [comment]
> Warning: Calling <<-EOS.undent is deprecated!

Opening #317 to fix this.



> sh: line 1: 67189 Segmentation fault: 11  mas list 2> /dev/null

As @kyoshidajp mentioned: `brew reinstall mas` for this.

**Comment by paulp** [comment]
`brew reinstall mas`  will not fix it. See mas-cli/mas#82. 

`brew reinstall --build-from-source mas` will fix it if you have a sufficiently recent version of Xcode.

**Comment by ilovezfs** [comment]
In case it helps: https://github.com/Homebrew/homebrew-core/pull/23556

**Comment by Fundebug** [comment]
FYI, I solved the problem by just update brew:

```bash
brew update
```

the Homebrew version is 1.6.9 currently

```bash
 brew --version
Homebrew 1.6.9
Homebrew/homebrew-core (git revision 07928; last commit 2018-07-06)
```
