### ISSUE TITLE
All bundle commands choke on "id: Install" produced by mas

### ISSUE THREAD

**Issue by paulp** [Homebrew/homebrew-bundle#321]
For instance 
```
% brew bundle --global check
Error: Invalid Brewfile: uninitialized constant #<Class:#<Bundle::Dsl:0x00000101a5d898>>::Install
```
Due to the Brewfile contents
```
 mas "macOS High Sierra", id: Install
```

This was previously opened as #308, with the bug in bundle being masked by the bug in mas, then closed. But there's no reason people should have to move the installer out of the way to run "bundle dump", nor does the opaque error message effectively point to the problem.

**Comment by MikeMcQuaid** [comment]
> This was previously opened as #308, with the bug in bundle being masked by the bug in mas, then closed.

Please don't reopen known duplicate issues but instead comment on the existing issue.

**Comment by MikeMcQuaid** [comment]
Anyone else who hits this: we'll consider accepting a PR for fixing the case where mas does not output IDs.
