### ISSUE TITLE
brew bundle should output package name before starting install

### ISSUE THREAD

**Issue by FiloSottile** [Homebrew/homebrew-bundle#331]
By the time the line `Installing X` is printed, the package was installed.

This is not great because when some package is taking forever to install you don't know which one it is, as the last line printed is about the previous package.

For example, with this output:

```
Using homebrew/core
Using homebrew/bundle
Tapping caskroom/cask
Using ansible
Installing git
Using go
Installing httpie
Using joe
Using pv
Installing stow
Installing wget
^C
```

`wget` was successfully installed. I interrupted the install of the next, unknown package.

**Comment by MikeMcQuaid** [comment]
Is the `brew bundle --verbose` output not sufficient?

**Comment by alyssais** [comment]
👍 I agree this would be a nice improvement.

Currently, it colours the output based on whether the installation would be successful, but we would preserve this by printing the uncolored message, then overwriting it in color if `$stdout.tty?`.

**Comment by FiloSottile** [comment]
I didn't think of reaching for `--verbose` because the normal output seemed clear (until I noticed how long `stow` was taking).

**Comment by MikeMcQuaid** [comment]
I think the `--verbose` output is currently sufficient. We're mirroring `bundler`'s output here and I think it works well for the default case.
