### ISSUE TITLE
brew Directive: Cannot Install URL Formulae Due to Case Sensitivity

### ISSUE THREAD

**Issue by sshaw** [Homebrew/homebrew-bundle#336]
The `brew` command allows one to use a formula at a URL. For example:

```
brew "https://raw.githubusercontent.com/Homebrew/homebrew-core/f1a767645f61112762f05e68a610d89b161faa99/Formula/elasticsearch.rb"
```

Given a server that respects case sensitivity in paths, this will not work in a Brewfile because [the URL is downcased](https://github.com/Homebrew/homebrew-bundle/blob/9c4ad2aea911d0b2a0f7de6e5876a9e7cdbcca9a/lib/bundle/dsl.rb#L73).

In the given URL, `Formula` is switched to `formula`, which results in a 404. 

While I'm not familiar with the codebase, it seems the solution is to [make `HOMEBREW_TAP_FORMULA_REGEX` case insensitive](https://github.com/Homebrew/homebrew-bundle/blob/9c4ad2aea911d0b2a0f7de6e5876a9e7cdbcca9a/lib/bundle/dsl.rb#L71). Though not sure what affect this will have on code that uses `Entry`.

**Comment by MikeMcQuaid** [comment]
Sorry, it's more or less accident that URL formulae work. I strongly recommend creating and using your own tap instead.

**Comment by sshaw** [comment]
Are URL formulas being depreciated by the brew command? If now, what's the reason for not supporting them?

**Comment by MikeMcQuaid** [comment]
They are not deprecated but we're not supporting them here because you should create a tap instead.
