### ISSUE TITLE
brew bundle dump no longer dump casks

### ISSUE THREAD

**Issue by pwang2** [Homebrew/homebrew-bundle#338]
casks in my Brewfile was removed after run `brew bundle dump`
https://github.com/pwang2/dotfiles/commit/22158cb049d7681610906040fcda0684f93b296f#diff-95e400bd03bd7b404542fc351f9939de

This seems related with homebrew/brew v1.6.6 release.

**Comment by stevenspasbo** [comment]
I'm seeing this as well.

**Comment by pwang2** [comment]
wasted some time on it but still no clue.

**Comment by MikeMcQuaid** [comment]
CC @reitermarkus

**Comment by pwang2** [comment]
Thanks for the quick fix. 

Users need to go to reinstall homebrew to fix the missing dump.  brew update WON'T work.

```sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by pwang2** [comment]
Thanks, @MikeMcQuaid. could you tell the steps to fix the cask missing here?  I think I have tried brew update before I redump it. but no affect.

**Comment by reitermarkus** [comment]
Try `brew update-reset`.
