### ISSUE TITLE
brew bundle doesn't seem to use args for ffmpeg, always gives me the bottled binary

### ISSUE THREAD

**Issue by jeffbski** [Homebrew/homebrew-bundle#343]
I just love the new bundle feature, however I need to build ffmpeg with special options and on OS X brew bundle seems to ignore the args and always gives me the bottled version which doesn't have these options. 

I tried to follow the docs on how to specify this. I ran with verbose and don't see any errors.

I even deleted the bottle for ffmpeg to see if that would help but it did the same thing.

Here is what I had in my Brewfile which gives me ffmpeg 4.0.1 from the bottle and doesn't have these options.

```
brew "ffmpeg", args: ["build-from-source", "with-fdk-aac", "with-libass", "with-opencore-amr", "with-openjpeg", "with-openssl", "with-rtmpdump", "with-schroedinger", "with-sdl2", "with-tools", "with-freetype", "with-frei0r", "with-libcaca", "with-libvorbis", "with-libvpx", "with-opus", "with-speex", "with-theora"]
```

If I build manually using `brew install` then this gives me what I need.

```
brew install ffmpeg --build-from-source --with-fdk-aac --with-libass --with-opencore-amr --with-openjpeg --with-openssl --with-rtmpdump --with-schroedinger --with-sdl2 --with-tools --with-freetype --with-frei0r --with-libcaca --with-libvorbis --with-libvpx --with-opus --with-speex --with-theora
```

Have I missed something in the Brewfile or is this a defect? Please help.

Thanks!

**Comment by MikeMcQuaid** [comment]
Did you try to `brew bundle dump` after running `brew install` manually? What did that output?

**Comment by jeffbski** [comment]
```
brew bundle dump
Error: /Users/jeff/Brewfile already exists
```

Basically it was always using the one from the bottle, it was ignoring my request to build from source and with those specific options. 

ffmpeg outputs the flags it was built with, so I could easily tell that it was not using the flags.  It was also obvious from the verbose output, indicating it was using the bottle version rather than downloading and building.

so it appears to me that the bundle command is ignoring the args.

**Comment by jeffbski** [comment]
tap "golangci/tap"
tap "homebrew/nginx"
tap "homebrew/science"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
tap "yudai/gotty"
cask "xquartz"
brew "ansible"
brew "bash-completion"
brew "chromedriver"
brew "go"
brew "dep"
brew "ffmpeg", args: ["with-fdk-aac", "with-freetype", "with-frei0r", "with-libass", "with-libcaca", "with-libvorbis", "with-libvpx", "with-opencore-amr", "with-openjpeg", "with-openssl", "with-opus", "with-rtmpdump", "with-sdl2", "with-speex", "with-theora", "with-tools"]
brew "webp"
brew "ghostscript"
brew "git"
brew "graphviz"
brew "haproxy"
brew "htop"
brew "httpie"
brew "ircii"
brew "youtube-dl"
brew "mpv"
brew "mtr"
brew "poppler"
brew "rclone"
brew "redis"
brew "telnet"
brew "golangci/tap/golangci-lint"
brew "homebrew/nginx/nginx-full"
brew "yudai/gotty/gotty"
cask "adobe-acrobat-reader"
cask "alfred"
cask "aquamacs"
cask "authy"
cask "avibrazil-rdm"
cask "burn"
cask "calibre"
cask "cyberduck"
cask "firefox"
cask "franz"
cask "gimp"
cask "handbrake"
cask "inkscape"
cask "keepassx"
cask "mattr-slate"
cask "omnidisksweeper"
cask "rclone-browser"
cask "reactotron"
cask "scribus"
cask "shiftit"
cask "skype"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vlc"
cask "yujitach-menumeters"
cask "homebrew/cask-versions/google-chrome-canary"

**Comment by jeffbski** [comment]
No after I removed ffmpeg and ran `brew -v bundle` with this setting it still just used the same prebottled version of ffmpeg which doesn't have all the features specified in the args.

The relevant part of the verbose output is below

```
Upgrading ffmpeg formula. It is installed but not up-to-date.
==> Upgrading 1 outdated package, with result:
ffmpeg 4.0.1
==> Upgrading ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.0.1.high_sierra.bottle.tar.gz
Already downloaded: /Users/jeff/Library/Caches/Homebrew/ffmpeg-4.0.1.high_sierra.bottle.tar.gz
==> Pouring ffmpeg-4.0.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/4.0.1: 246 files, 49.7MB
Installing ffmpeg
```

So it just seems to ignore the args that are specified.

**Comment by MikeMcQuaid** [comment]
> So it just seems to ignore the args that are specified.

That is likely because it is upgrading the formula. Try to remove it with `brew uninstall --force ffmpeg` and try again. I cannot reproduce this issue with the args specified as you have above.

**Comment by jeffbski** [comment]
Yes, you are correct. I guess that even though I was uninstalling ffmpeg v4, I still have v3 and v2 versions installed, so it was ignoring the args in that case. Very weird. Though once I deleted all of the versions then it does work properly from the bundle command.

Thanks for the help!
