### ISSUE TITLE
Adding an ENV var for the `--global` flag

### ISSUE THREAD

**Issue by aramprice** [Homebrew/homebrew-bundle#368]
I'm curious if there is any interest in being able to trigger the `--global` behavior using and ENV var. Something like `HOMEBREW_BUNDLE_GLOBAL=1`.

**Comment by colindean** [comment]
Maybe? What about an environment variable that lets the user specify which file to use, and the user can choose to use the global path or some other one?

**Comment by MikeMcQuaid** [comment]
I don't think so personally; it's not clear what should happen when you have that variable set and you specify a `--file` flag.

**Comment by aramprice** [comment]
We already have this lack of clarity when both `--global` and `--file` are specified. As the [code is today](https://github.com/Homebrew/homebrew-bundle/blob/bc97597d437f32712791d5b68d558da1798d34e1/lib/bundle/bundle.rb#L48) `--global` wins. Maybe `--global` should be removed in favor of `--file`?

I'm interested in being able to specify a `Brewfile` via an ENV var. If the project is interested in a PR for this perhaps we can work out how best to make this possible.

**Comment by MikeMcQuaid** [comment]
@aramprice We won't be removing `--global` as it's widely used.



> If the project is interested in a PR for this perhaps we can work out how best to make this possible.

That sounds reasonable, particularly if you address the conflicts when multiple things (e.g. `--global` and `--file`) are specified at once and error out appropriately.

**Comment by aramprice** [comment]
Just letting you know that I'm chipping away at this, slowly. I have some travel coming up in October perhaps by mid-October.
