### ISSUE TITLE
--file-path is not respected

### ISSUE THREAD

**Issue by danieljaouen** [Homebrew/homebrew-bundle#375]
I'm trying to install/dump/cleanup a Brewfile from a different directory than the current one.  From the help docs, it looks like this should be possible using something like `brew bundle install/dump/cleanup --file-path=~`, but this doesn't work.  All of these commands ignore the `--file-path` option and only look in the current directory for a Brewfile.

**Comment by MikeMcQuaid** [comment]
It's `--file` and is respected: https://github.com/Homebrew/homebrew-bundle/blob/09b65221ad490539ee064b764b1db01fa681a73c/lib/bundle/bundle.rb#L51
