### ISSUE TITLE
Manage old terraform version with homebrew-bundle

### ISSUE THREAD

**Issue by johnplaydrums** [Homebrew/homebrew-bundle#400]
Hey! We love managing brew dependencies with homebrew-bundle but have run into a snag trying to support older versions of terraform. We need to run terraform 0.11.7, and with the homebrew cli we can do:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/0a5f283f5fa18b4bd2dc0e111ca83257af962c9d/Formula/terraform.rb
```
and I'll be set with terraform 0.11.7.  But I haven't been able to figure out how to achieve that via a Brewfile. I may have missed the obvious solution but, any suggestions?

Thank you!

**Comment by johnplaydrums** [comment]
@jacobbednarz thanks for the quick response! That's not a bad solution, I think we can go with that solution for now. I don't know if there is a homebrew-bundle native way to handle this scenario but if not, creating our own tap will work.

**Comment by johnplaydrums** [comment]
@jacobbednarz trying your suggestion, homebrew is telling me to use `switch`. I don't think homebrew-bundle has support for a `switch` statement does it?
```
$ brew tap "johnplaydrums/terraform"
$ brew install "johnplaydrums/terraform/terraform"
Warning: johnplaydrums/terraform/terraform 0.11.7 is already installed
The currently linked version is 0.11.10
You can use `brew switch terraform 0.11.7` to link this version.
```

We want to enforce the `0.11.7` installment (or any other version in the future). Of course we could have our engineers run `brew switch terraform 0.11.7` but we were hoping to be able to resolve all dependencies needs with just `brew bundle`. Thanks again!

**Comment by johnplaydrums** [comment]
Thanks @colindean! If using `tfenv` is the best solution to this use case I'm happy to close this issue

**Comment by colindean** [comment]
Yeah, tfenv is def. the best way to control what version of tf you're using.

**Comment by johnplaydrums** [comment]
@colindean cool thank you. Also I guess I meant the question a little more broadly than just terraform. Like should homebrew-bundle support more features to manage specific homebrew deps. (e.g. `switch` support maybe?).

**Comment by colindean** [comment]
IIRC, one of the philosophies of Homebrew is that only the latest version of a formula is supported. I'm not sure we'd want to support installing old formula in this way.

@MikeMcQuaid can chime in…

**Comment by johnplaydrums** [comment]
Sounds good, thank you both!
