### ISSUE TITLE
`brew bundle check --verbose` gives a oddly different output then `brew bundle check` when there are `mas` entries in the `Brewfile`

### ISSUE THREAD

**Issue by jsatk** [Homebrew/homebrew-bundle#401]
<img width="873" alt="screen shot 2018-11-17 at 4 50 35 pm" src="https://user-images.githubusercontent.com/1005550/48667394-51e23b00-ea89-11e8-8f1d-beca69d6cf0f.png">

I'm attempting to write a `Makefile` that will run `brew bundle install --no-upgrades` if `brew bundle check` tells me that I have unsatisfied dependencies. 

`brew bundle check` by itself gives me the concerning message that has been reported before here 
https://github.com/Homebrew/homebrew-bundle/issues/201. If I throw `--verbose` on there I get a *shorter* output and a better output. Note: my stuff is all up-to-date so the message that it can't satisfy my dependencies is wrong.

Also worth noting the exit code of each is different too. With `--verbose` I get the expected `0`, but without it I get `1`. 

Any idea why `--verbose` gives me a better output and exit code?

**EDIT**: Appears to only be an issue when you have `mas` (the CLI tool for macOS App Store) entries in your `Brewfile`. See: 
https://github.com/Homebrew/homebrew-bundle/issues/401#issuecomment-442230453

**Comment by colindean** [comment]
I _think_ you can skip to running… `brew bundle install --no-upgrades`. You don't need to `brew bundle check` unless you _really_ want to only see what needs to be installed. That is, I believe that `install` installs and returns zero if it did not fail to bring the installation to the desired state, including the possibility that the system was already at the desired state.

That said, this is odd behavior: `brew bundle check` with any other options should not have a different result than with `--verbose`, except in that `--verbose` continues through errors. Without it, `check` stops after the first missing package. It doesn't _tell_ you which package, though: that's what `--verbose` is for!

Looking through the tests, I don't think I see one that covers `--no-upgrade` with `check`. I won't have time to look at it for a few days but maybe other maintainers will.

**Comment by jsatk** [comment]
> I _think_ you can skip to running… `brew bundle install --no-upgrades`. You don't need to `brew bundle check` unless you _really_ want to only see what needs to be installed. That is, I believe that `install` installs and returns zero if it did not fail to bring the installation to the desired state, including the possibility that the system was already at the desired state.

Very true, @colindean. The main reason I wanted to do this is that `brew bundle` doesn't have a `--quiet` or `--silent` option, and when I searched the issues for people requesting that I saw it suggested that `brew bundle check` should be used to see if `install` even needs to be ran.

Regardless, my *goal* is to make my `Makefile` less noisy. `brew bundle install` prints out way more information than I care to see if nothing needs to be done. 

So that's my *goal*. But while trying to achieve this goal I discovered that `--verbose` flag gives me different results.

**Comment by jsatk** [comment]
> What about if you don't pass `--no-upgrade`?

@MikeMcQuaid it simply prints out all the formula & casks and says it's already using the latest of each.

**Comment by colindean** [comment]
I could see a use case for `--silent` for some commands, such that the only real feedback is the exit code. Install? Zero means it ended in the desired state: everything installed. Check? Everything's installed. Etc. 

But `command > /dev/null` could also handle that…

**Comment by jsatk** [comment]
@jacobbednarz while the `> /dev/null` satisfies a desire for a `--silent` flag; the original issue still stands. `--verbose` returns a different exit code and message than without `--verbose` for `brew bundle check`.

**Comment by MikeMcQuaid** [comment]
@jsatk Can you work on finding a reproducible, minimal `Brewfile` for this? As-is there's very little actionable here.

**Comment by jsatk** [comment]
Sure!  Are you not seeing the same inconsistent results that I am when using `check` with and without the `--verbose` flag?

**Comment by MikeMcQuaid** [comment]
@jsatk No.

**Comment by jsatk** [comment]
@MikeMcQuaid figured out what's causing the issue. `mas`.

If you have any `mas` entires in your `Brewfile` you'll be able to recreate.

Example `Brewfile`
```Brewfile
mas "Byword", id: 420212497
```

Then run `brew bundle check --no-upgrade`

**Comment by MikeMcQuaid** [comment]
@jsatk Got it. See https://github.com/Homebrew/homebrew-bundle/pull/404
