### ISSUE TITLE
arbitrary ruby?

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/homebrew-bundle#413]
previously, I used to put the following snippet at the bottom of my Brewfile and it would work just fine:

```ruby
# requires password or interaction from user
if ENV['BREWFILE_INTERACTIVE']
  mas '1Password', id: 1333542190
  mas 'Pocket', id: 568494494
  mas 'DaisyDisk', id: 411643860
  mas 'Leaf', id: 576338668
  mas 'Todoist', id: 585829637
  mas 'WhatsApp Desktop', id: 1147396723

  cask 'ngrok'
  cask 'virtualbox'
  cask 'teamviewer'
  cask 'private-internet-access'
  cask 'flash-npapi'
  cask '1password-cli'
  cask 'google-hangouts'
  brew 'zzz'
end
```

for some reason, it doesn't seem to be working anymore. I even tried adding:

```ruby
puts ENV
puts ENV['BREWFILE_INTERACTIVE']
```

`puts ENV` doesn't show a hash of environment variables but instead prints the string, "ENV"

I tried setting the variable in multiple ways but neither worked. Tried both `BREWFILE_INTERACTIVE=1 ./script/setup` and `export BREWFILE_INTERACTIVE=1`.

any ideas if this functionality was removed?

**Comment by MikeMcQuaid** [comment]
Homebrew doesn’t pass through arbritrary environment variables unless they start with ‘HOMEBREW_’
