### ISSUE TITLE
dump fails with "topological sort failed" due to circular dependency

### ISSUE THREAD

**Issue by heptathlon** [Homebrew/homebrew-bundle#421]
"brew bundle dump --global" fails on my MacBook:

"Error: topological sort failed: ["libtiff", "webp"]
Formulae dependency graph sorting failed (likely due to a circular dependency)!"

How did I end up there and now how to do the dump? Can sorting be disabled so that at least I get some output? i like to install my apps on a different Mac (iMac).

Thanks

**Comment by colindean** [comment]
This appears to be a reproduction of #420. Can you check that thread for some rudimentary troubleshooting steps?

**Comment by heptathlon** [comment]
Can't spot any but the same thing happens for ["ffmpeg", "x264"] too.

Tried to uninstall ffmpeg. Fails with: "Refusing to uninstall (...) because it is required by x264"
Tried to uninstall x264. Fails with: "Refusing to uninstall (...) because it is required by ffmpeg and libav"

"brew deps --tree --installed|grep ffmpeg" only returns one line meaning that the dependency graph does not show that x264 depends on ffmpeg.

Hope this helps

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-bundle/issues/420
