### ISSUE TITLE
Brew bundle dump --file=- is now "brew bundle dump dump --file=-"

### ISSUE THREAD

**Issue by geowarin** [Homebrew/homebrew-bundle#426]
Hello,

This relates to #405. I think the fix in #406 is not completely correct as ARGV does not include `dump` when running `brew bundle dump`.

To access this branch https://github.com/Homebrew/homebrew-bundle/pull/406/commits/d103680ce24d6e47b57c8561ef606040e7bd90c5#diff-8f0facf48d9e19622fcf98d84e723c27R13 I have to type `brew bundle dump dump --file=-` 😄

**Comment by colindean** [comment]
https://github.com/Homebrew/homebrew-bundle/blob/36ba99674447c584af2133b8f61cf944d2a10413/cmd/brew-bundle.rb#L59-L61

I don't see a way that we can know what command is being used, so we might need to pass an override of the Brewfile path to use into `Brewfile.path` and move the logic from https://github.com/Homebrew/homebrew-bundle/blob/36ba99674447c584af2133b8f61cf944d2a10413/lib/bundle/brewfile.rb#L11-L18 to https://github.com/Homebrew/homebrew-bundle/blob/36ba99674447c584af2133b8f61cf944d2a10413/lib/bundle/dumper.rb#L34-L36
