### ISSUE TITLE
Installing packages with custom settings now that flags have been removed

### ISSUE THREAD

**Issue by fishpen0** [Homebrew/homebrew-bundle#447]
For example, I have had the following line in my Brewfile for years:
`brew 'findutils', args: ["with-default-names"]`

What do I need to do do keep using a brewfile and still get the expected result of having the installed package override the regular find commands?

Is this a feature simply something that Brewfiles will no longer support directly and should I just stop using brewfiles in favor of going back to scripts that install brew packages one at a time with the correct settings?

**Comment by jacobbednarz** [comment]
This should still work. Are you able to provide a test case with the results of what you're seeing locally? The code that handles this is still in the library so it _should_ work.

**Comment by fishpen0** [comment]
I think it is that all of the findutils, coreutils, etc packages have been individually updated to remove the flags per the new homebrew-core standards of no longer compiling packages (see https://github.com/Homebrew/homebrew-core/pull/35720).  

I think it may be impossible to avoid needing additional wrapper scripts outside of just using a Brewfile since it appears the new expected pattern is to update your PATH manually for each util package you install.

**Comment by MikeMcQuaid** [comment]
> I think it is that all of the findutils, coreutils, etc packages have been individually updated to remove the flags per the new homebrew-core standards of no longer compiling packages (see [Homebrew/homebrew-core#35720](https://github.com/Homebrew/homebrew-core/pull/35720)).

Yes.

This is unrelated to Homebrew/homebrew-bundle. See the relevant caveats (or `brew info`) for these packages and adjust your `PATH` accordingly.

**Comment by fishpen0** [comment]
What is the value of using a brewfile now over just a different single file install script that can also do things like setup a PATH?  I originally ran into this because it broke our new hire setup process which was to simply pull down a brewfile and go.

**Comment by MikeMcQuaid** [comment]
@fishpen0 Please do not confuse your personal use-case with a tool lacking value for others. You were relying on options which we gave prior notice they would be removed.
