### ISSUE TITLE
Error: protobuf: Unsupported special dependency :python3

### ISSUE THREAD

**Issue by readygo586** [Homebrew/homebrew-bundle#449]
When using brew to install protobuf 3.5.1, meet the following error  
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/41469645/52609177-51561680-2eb7-11e9-91a0-64fb9c15f7a9.png">

how to deal with this issue?

**Comment by readygo586** [comment]
the brew doctor and brew config information list below.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/41469645/52609447-4d76c400-2eb8-11e9-89ab-3a4cb99ec031.png">

**Comment by colindean** [comment]
I'm sorry, this is not the right repository for this issue. This repository is related to `brew bundle` only.

I think you're best off posting this at https://discourse.brew.sh, where you may be directed to post elsewhere.
