### ISSUE TITLE
Allow packages to be pinned

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#455]
Would you consider allowing pinning of packages? I have been using `brew bundle` for a long time, but I am in a situation that I have to use an older version of a package. So, either allowing to specify a particular version of a package and having it pinned or specifying a specific URL for a formula (like https://raw.githubusercontent.com/Homebrew/homebrew-core/300531275e320640923614a3b150b8a8f8677004/Formula/asdf.rb) - will automatically pin it. Need this asap - `brew bundle` becomes unusable for me till the formula author fixes their issue.

**Comment by colindean** [comment]
Homebrew Bundle pins only taps, not formulae. Homebrew supports the installation of only the latest version of a formula. 

If you need a specific version of a formula, you can use `brew extract` to put that formula in a tap and then _pin_ that tap with `brew tap-pin` and adding `tap: true` to that tap's line in `Brewfile`. Pinning a tap prioritizes its formulae over homebrew-core for formula names are supplied by the user.

See also #439.
