### ISSUE TITLE
Would you accept a PR to add Snap and Flatpak support?

### ISSUE THREAD

**Issue by jamescostian** [Homebrew/homebrew-bundle#463]
As the title says, I'm willing to make the changes necessary for this, I'm just wondering if they would be accepted.

# Introduction

I love the idea of saving a list of everything installed on my mac with `brew bundle dump` and then bringing another mac to life with `brew bundle`. And I'm truly grateful for all the work put into this, especially the thought that went into adding support for `mas`, so that reinstalling all the same apps from the Mac App Store is perfectly simple using `brew bundle`.

# Suggestion

Now that Homebrew officially supports Linux, I'd like to suggest adding the Linux analogues to `brew bundle` to support things like `mas` but for Linux. In the Linux world, instead of the Mac App Store, there is [Flathub](https://flathub.org/apps/collection/popular) for Flatpaks and [Snapcraft](https://snapcraft.io/store) for Snap.

# How I would implement this

I took a look at how `brew bundle` interfaces with `mas` in [this file](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_checker.rb), [this file](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_dumper.rb), and [this file](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/mac_app_store_installer.rb).

Just like how you use `mas list` to dump a list of apps from the Mac App Store, I'd use `flatpak list` and `snap list` to get a list of Flatpaks and Snaps installed on their machine. Just like how you use `mas install` I could use the flatpak and snap analogues (e.g. installing Spotify is done with `sudo snap install spotify` or `flatpak install flathub com.spotify.Client`).

In `Brewfile`, instead of adding something like `mas "Xcode", id: 497799835`, I'd add something like `snap "spotify"` or `flatpak "com.spotify.Client", remote: "flathub"`

Obviously, if someone uses `brew bundle` on a Mac, I wouldn't bother trying to do anything with flatpak or snap.

# Differences with `mas` integration

The main difference is out-of-date apps. If you wanted to update `foo`, you could use `flatpak update foo` or `snap refresh foo`, but that would be weird. Snap has a daemon that always keeps your snaps up-to-date, so you really shouldn't try `snap refresh foo`; that command actually serves a different purpose. And for Flatpak, there is no `flatpak outdated`, and the "right way" to do things is to just use `flatpak update` (which updates *all* installed flatpaks).

**Comment by MikeMcQuaid** [comment]
> Obviously, if someone uses `brew bundle` on a Mac, I wouldn't bother trying to do anything with flatpak or snap.

This is the main thing I've a bit dubious about with this: what is the output to the user? Do projects have a separate `Brewfile` per-OS? If so: what are they named?

I'm not opposed to the code all living in this one repo but I think perhaps having a different filename for Linux (`Linuxbrewfile`?) or something might make this conceptually better.

**Comment by jamescostian** [comment]
For me personally, a huge selling point of `brew` now that I'm moving to Linux is that it's a single package manager for macOS *and* Linux. If you separate `Brewfile` and `Linuxbrewfile`, then you you lose out on all the niceness of being able to just run e.g. `brew install ffmpeg` and sleep easy knowing it's in your `Brewfile`, and will automatically be installed on any of your macs/linux-boxes with `brew bundle`.

I believe that putting casks, mas apps, flatpaks, and snaps all in the same `Brewfile` makes more sense because it avoids the duplication of everything else like `wget` or `node` or `go` or `git`, etc.

**Comment by MikeMcQuaid** [comment]
> `brew install ffmpeg` and sleep easy knowing it's in your `Brewfile`, and will automatically be installed on any of your macs/linux-boxes with `brew bundle`.

Kinda. Remember Homebrew/homebrew-core and Homebrew/linuxbrew-core are different repositories with differing versions etc.

> I believe that putting casks, mas apps, flatpaks, and snaps all in the same `Brewfile` makes more sense because it avoids the duplication of everything else like `wget` or `node` or `go` or `git`, etc.

I think it would be confusing to have a `Brewfile` in which some things are installed on Mac and not on Linux. If there was some sort of DSL that indicated "this flatpack/snap installs the same software as this cask/mas" then 🆒 and we could consider that. Can Linuxbrew install flatpack/snap if it's not on the system?

**Comment by jamescostian** [comment]
> Homebrew/homebrew-core and Homebrew/linuxbrew-core are different repositories with differing versions etc.

This is true, but isn't the goal to keep these two in sync?

> I think it would be confusing to have a Brewfile in which some things are installed on Mac and not on Linux. If there was some sort of DSL that indicated "this flatpack/snap installs the same software as this cask/mas" then 🆒 and we could consider that

I like that DSL idea. So for example, things like Xcode that are mac-only or things like GParted that are linux-only would work using the preexisting (or in the case of Linux, aforementioned) specifications. And we could show warning messages when running `brew bundle`, like `Xcode could not be installed`. But, if you wanted to install something available on both Linux and macOS, like Spotify, perhaps we could put it in a single line, like:

```
[{mas "Spotify", id: 123456}, {snap "spotify"}, {flatpak "com.spotify.Client", remote: "flathub"}]
```

Given such a line, I propose `brew bundle` should first try to install Spotify using mas, and if mas isn't installed try snap, and if snap isn't installed try flatpak. If none of them are installed, try to install the first one you can that would work on your OS.

For example, on a mac, Spotify would get installed with `mas` whether or not you already had `mas` installed. On a Linux distro, Spotify would get installed by snap, unless you already had flatpak installed but not snap. If you didn't have snap or flatpak and were on Linux, snap would be installed because snap came before flatpak in the array of options.

What are your thoughts on this DSL? Also, it could be used for anything else like `brew cask install` or even just normal `brew install`. So if you need to be able to convert videos, you could have something like:

```
[{mas "Video Converter", id: 123}, {snap "Linux Video Converter"}, {brew "ffmpeg"}]
```

This would install GUIs, unless you were on a Linux machine without snap already installed, in which case `ffmpeg` would just be installed on the CLI.

> Can Linuxbrew install flatpak/snap if it's not on the system?

Yes. There's an official list of ways to install snap on any normal linux distro [here](https://docs.snapcraft.io/installing-snapd/6735), and the same exists for snap [here](https://flatpak.org/setup/).

**Comment by MikeMcQuaid** [comment]
> This is true, but isn't the goal to keep these two in sync?

That's the goal but the reality is they diverge.



> So for example, things like Xcode that are mac-only or things like GParted that are linux-only would work using the preexisting (or in the case of Linux, aforementioned) specifications.

I'd suggest a `linux do`, `macos do` block for each platform to be able to separate them. 

> perhaps we could put it in a single line

Looks a bit ugly to me. What about something like

```
package "Spotify" do
  macos: mas("Spotify", id: 123456)
  linux: snap("spotify")
end
```

> Given such a line, I propose `brew bundle` should first try to install Spotify using mas, and if mas isn't installed try snap, and if snap isn't installed try flatpak. If none of them are installed, try to install the first one you can that would work on your OS.

Do snap and flatpak work on macOS? Why would you use one and not the other? Feels a bit weird to give both equal prominence; will result in a lot of duplication.

> This would install GUIs, unless you were on a Linux machine without snap already installed, in which case ffmpeg would just be installed on the CLI.

This feels weird to be installing different software and treating them like the same thing.

> Yes. There's an official list of ways to install snap on any normal linux distro [here](https://docs.snapcraft.io/installing-snapd/6735), and the same exists for snap [here](https://flatpak.org/setup/).

Neither of those seem to reference Homebrew on Linux/Linuxbrew. We'd need to have a way to `brew install snap` or `brew install flatpak`; I don't think we can rely on them being on the system or installed out-of-band.

**Comment by jamescostian** [comment]
Ok, I'm fine with that syntax. Just curious, do you have any recommendations for how to parse that out? In the JS world we could just `eval` code that's written in JS syntax, and just provide the necessary functions. Is there such a concept in Ruby?

> Do snap and flatpak work on macOS?

No

> Why would you use one and not the other?

There is [lots](https://medium.com/nitrux/cross-distro-linux-applications-1169c3077136) [of](https://askubuntu.com/questions/866511/what-are-the-differences-between-snaps-appimage-flatpak-and-others) [debate](https://www.phoronix.com/scan.php?page=news_item&px=Snap-vs-Flatpak-2018-Distros) [on](https://www.reddit.com/r/linux/comments/60qdtw/flatpak_vs_snap_which_format_is_better_a_rather/) [this](https://www.reddit.com/r/linuxquestions/comments/9oiuup/repo_flatpak_or_snap/). People have strong opinions both ways; there isn't a clear winner, and both have massive help from large organizations, and lots of support for popular applications.

> We'd need to have a way to `brew install snap` or `brew install flatpak`; I don't think we can rely on them being on the system or installed out-of-band.

That sounds fair. I'd be willing to contribute those.

**Comment by MikeMcQuaid** [comment]
> There is [lots](https://medium.com/nitrux/cross-distro-linux-applications-1169c3077136) [of](https://askubuntu.com/questions/866511/what-are-the-differences-between-snaps-appimage-flatpak-and-others) [debate](https://www.phoronix.com/scan.php?page=news_item&px=Snap-vs-Flatpak-2018-Distros) [on](https://www.reddit.com/r/linux/comments/60qdtw/flatpak_vs_snap_which_format_is_better_a_rather/) [this](https://www.reddit.com/r/linuxquestions/comments/9oiuup/repo_flatpak_or_snap/). People have strong opinions both ways; there isn't a clear winner, and both have massive help from large organizations, and lots of support for popular applications.

In that case: we should pick one and support that. Perhaps the one that's easier to `brew install` with Linuxbrew 😉 


> Ok, I'm fine with that syntax. Just curious, do you have any recommendations for how to parse that out? In the JS world we could just `eval` code that's written in JS syntax, and just provide the necessary functions. Is there such a concept in Ruby?

You should see a bit when you look at the exiting code that's doing similar to what you describe. The `macos do` is calling a method with a block as a parameter which can be called/evaluated on an object/scope of your choice.

**Comment by MikeMcQuaid** [comment]
> In that case: we should pick one and support that. Perhaps the one that's easier to `brew install` with Linuxbrew 😉

Or at least: do not support saying "you can install this with snap or flatpak" interchangeably in a single block/Brewfile.

**Comment by jamescostian** [comment]
Ok, this sounds good. Also, it turns out there is already [`brew install snapcraft`](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/snapcraft.rb) which isn't the name I thought it would be, but is probably the more correct name for snap.

I'll start working on the PR when I have some free time.

**Comment by jamescostian** [comment]
Actually, snapcraft is a different thing. Nevermind, I'll work on making a formula for snap.

**Comment by MikeMcQuaid** [comment]
Sounds good! Closing this out but feel free to continue discussion here 👍
