### ISSUE TITLE
link: :force doesn't link if already installed.

### ISSUE THREAD

**Issue by adamchainz** [Homebrew/homebrew-bundle#468]
Hi

I just set up development for an application I'm working on that uses Brewfile, which has:

```
brew 'gettext', link: :force
```

I already had `gettext` installed, but not linked. After `brew bundle` running, it was still not linked.

I understand depending on linking isn't a great idea, but I'd still expect this to force link even though it is already installed, just so that it matches the Brewfile.

Thanks,

Adam

**Comment by MikeMcQuaid** [comment]
Yes, I agree. We'd accept a pull request to fix this.
