### ISSUE TITLE
gcc (et al) not on path within bundle environment

### ISSUE THREAD

**Issue by zofrex** [Homebrew/homebrew-bundle#471]
Firstly, this might not be a bug, it might be that I'm not correctly understanding what `brew bundle` does. What I can be sure of is there is a mismatch between what I expect it to do, and what it does:

Brewfile:
```
brew "gcc"
```

This of course installs `gcc-8` etc etc on the path outside of the bundled environment due to `gcc` already existing as the Clang compiler:

```
$ which gcc
/usr/bin/gcc
$ which gcc-8
/usr/local/bin/gcc-8
$ gcc --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
$ gcc-8 --version
gcc-8 (Homebrew GCC 8.3.0) 8.3.0
```

This is all as expected.

However, I thought a big advantage of using bundle is that within a `bundle exec` environment my brewed dependencies will be the ones picked up, which is how it seems to work with libraries and such, so I thought that would also be the case with gcc. However:

```
$ brew bundle exec which gcc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/gcc
$ brew bundle exec gcc --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
```

That first part is what makes me think this might be a bug - Homebrew is clearly putting _something_ on the PATH as gcc, but I'm still getting Clang. Is this a bug or am I misunderstanding what Homebrew Bundle is doing here?

**Comment by zbeekman** [comment]
I think you still need to be saying "gcc-8". AFAIK, the point is mostly to strip and sanitize your environment of other sources of errors. The GCC formula only installs binaries with suffixes containing the major version number of GCC. The environment needs to keep the majority of stuff provided by macOS around, because we still use that for building. The point is to move other formulae out of the way, and user environment/path insanity.

This is what I would do:

```
$ brew bundle exec which gcc-8
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/gcc-8
$ brew bundle exec gcc-8 --version
gcc-8 (Homebrew GCC 8.3.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by zbeekman** [comment]
IMO, this is correct behavior and this issue can be closed.
