### ISSUE TITLE
macOS gatekeeper quarantine

### ISSUE THREAD

**Issue by olbrichj** [Homebrew/homebrew-bundle#474]
Currently every app installed with brew gets set the quarantine flag, which most often is reasonable. This results in the first start after launching the app, gatekeeper will ask you whether you want to start it or not, as it was downloaded from the internet.

This is also the case when upgrading etc. Sometime you want to roll out your setup to a lot of computers and don't want to approve every single app after installation. So brew provides a --no-quarantine flag, which will not add the app to quarantine.

It would be great if brew bundle would support --no-quarantine. 
e.g.

'brew bundle --no-quarantine'

**Comment by MikeMcQuaid** [comment]
Will review a PR to add this. It may make more sense as an argument in the `Brewfile` for specifically trusted `cask`s.

**Comment by olbrichj** [comment]
I will have a look, but my Ruby is quite rusty ;) So it will take a while.

**Comment by MikeMcQuaid** [comment]
Passing on this until we have other requests or a PR.
