### ISSUE TITLE
Error upgrading formula from an URL 

### ISSUE THREAD

**Issue by lyricsboy** [Homebrew/homebrew-bundle#475]
I'm attempting to use brew bundle to install a package that is not (yet) part of the shared package directory. If I provide its formula URL, it will fetch that but it doesn't seem to know that it should be upgraded instead of simply installed.

Is there a limitation in the install-vs-upgrade logic that could be causing this?

Brewfile:

```
brew "https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/xchtmlreport.rb"
```

Output:

```
$ brew bundle
######################################################################## 100.0%
Error: xchtmlreport 1.6.1 is already installed
To upgrade to 1.7.0, run `brew upgrade xchtmlreport`.
```

**Comment by lyricsboy** [comment]
I previously installed 1.6.1 of this package without using the bundle, just manually.

**Comment by MikeMcQuaid** [comment]
Use a tap instead.

**Comment by lyricsboy** [comment]
OK. Using a tap as such in the Brewfile:

```
tap "TitouanVanBell/XCTestHTMLReport", "git@github.com:TitouanVanBelle/XCTestHTMLReport.git"
brew "xchtmlreport"
```

It is able to install the dependency, but it sees the older version 1.6.1:

```
$ brew bundle
Tapping titouanvanbell/xctesthtmlreport
Using xchtmlreport
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
$ xchtmlreport -v
XCTestHTMLReport 1.6.1
```

I believe this is because the repo's default branch is `develop`, and in that branch's head revision, the formula points to v1.6.1:

https://github.com/TitouanVanBelle/XCTestHTMLReport/blob/develop/xchtmlreport.rb

However, in the `master` branch, the formula points to the latest version 1.7.0:

https://github.com/TitouanVanBelle/XCTestHTMLReport/blob/master/xchtmlreport.rb

Is there any way to point brew to the master branch or this version specifically?

**Comment by colindean** [comment]
homebrew bundle doesn't support setting the branch because `brew tap` doesn't support setting a branch.

The shortest solution is to put that formula in another repo and use that as a tap. 

You could even try putting the file into a gist and using the gist as a tap, e.g.

```ruby
# using one of your own gists as an example
tap "xctesthtmlreport/mine", "https://gist.github.com/lyricsboy/9613890"
```

I've not tried this, just theorizing.

**Comment by lyricsboy** [comment]
Thanks for the ideas @colindean. I will also reach out to the repo owner and see if this can be fixed up on their side.
