### ISSUE TITLE
`brew bundle cleanup` would incorrectly remove formulae required by casks

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-bundle#480]
Steps to reproduce the bug.

```
brew cask install qlcolorcode
brew bundle dump
brew bundle cleanup
```

The last command would print:
```
Would uninstall formulae:
highlight
```

However `highlight` formula is in fact required by the `qlcolorcode` cask.

**Comment by MikeMcQuaid** [comment]
This is a missing feature rather than a bug. We don't handle formula dependencies for casks but this would be a desirable feature to add.

**Comment by alecclarke** [comment]
👋 I'd like to take this one on. Is it still up for grabs?

**Comment by MikeMcQuaid** [comment]
Yes.
