### ISSUE TITLE
Casks with manual installers

### ISSUE THREAD

**Issue by andrewhavens** [Homebrew/homebrew-bundle#484]
I recently used Homebrew Bundle for the first time to automate the installation of several casks. One of the casks I installed did not seem to install. Then I realized that it has a manual installer that I need to run. However, the output of running `brew bundle` did not tell me that I needed to do that. I also didn't know how to run the installer until I manually ran `brew cask install` which displays a message that shows the path to the manual installer. I'm not sure what should be done about it, but it seems like it's really important to display a similar message for casks that require manual installation.

**Comment by MikeMcQuaid** [comment]
`brew bundle --verbose` will output the necessary information. We cannot infer and output specifically manual instructions without changes in `brew cask`. Closing this until that happens (and it'll likely require you or someone else interested to create the PR rather than creating an issue).
