### ISSUE TITLE
brew bundle install and cleanup incorrectly handling casks from AdoptOpenJDK/openjdk

### ISSUE THREAD

**Issue by Okeanos** [Homebrew/homebrew-bundle#487]
In a similar vein to #480 the commands `brew bundle install` and `brew bundle cleanup` will incorrectly identify the casks `adoptopenjdk8` and `adoptopenjdk11` to be installed and cleanup when they are in fact part of the `Brewfile` as primary dependency (and already installed via the same bundle).

`brew update` was run prior to `brew bundle install`.

The relevant parts of the Brewfile are:
```rb
tap 'homebrew/cask'
tap 'AdoptOpenJDK/openjdk'
cask_args appdir: '/Applications'
cask 'adoptopenjdk8'
cask 'adoptopenjdk11'
```

Output
```sh
$ brew update
Already up-to-date.
$ brew bundle install
Installing adoptopenjdk8
Installing adoptopenjdk11
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
$ brew bundle install
Installing adoptopenjdk8
Installing adoptopenjdk11
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
$ brew bundle cleanup
Would uninstall casks:
adoptopenjdk/openjdk/adoptopenjdk11                                                          adoptopenjdk/openjdk/adoptopenjdk8
```

I checked the brew files of [both dependencies](https://github.com/AdoptOpenJDK/homebrew-openjdk), they both use `.pkg` installers and are from a cursorily analysis not wildly different then say the `firefox` cask (from [homebrew-casks](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/firefox.rb)). Maybe it has something to do with the AdoptOpenJDK dependencies requiring sudo and being installed in `/Library/Java/JavaVirtualMachines/`? Or is the `sha256` version hash applied incorrectly to verify a particular version is, in fact installed?

**Comment by MikeMcQuaid** [comment]
Please paste the `brew bundle check --verbose` output for anything that wants to be installed that already seems to be installed. Closing for now as this seems user/cask specific.

**Comment by Okeanos** [comment]
As requested the output of the check command as well as the output of `brew cask info` for each of the two casks:

```sh
$ brew bundle check --verbose
brew bundle can't satisfy your Brewfile's dependencies.
→ Cask adoptopenjdk8 needs to be installed or updated.
→ Cask adoptopenjdk11 needs to be installed or updated.
Satisfy missing dependencies with `brew bundle install`.
$ brew cask info adoptopenjdk8
adoptopenjdk8: 8,212:b03
https://adoptopenjdk.net/
/usr/local/Caskroom/adoptopenjdk8/8,212:b03 (97.7MB)
From: https://github.com/adoptopenjdk/homebrew-openjdk/blob/master/Casks/adoptopenjdk8.rb
==> Name
AdoptOpenJDK 8
==> Artifacts
OpenJDK8U-jdk_x64_mac_hotspot_8u212b03.pkg (Pkg)
$ brew cask info adoptopenjdk11
adoptopenjdk11: 11,0.3:7
https://adoptopenjdk.net/
/usr/local/Caskroom/adoptopenjdk11/11,0.3:7 (181.4MB)
From: https://github.com/adoptopenjdk/homebrew-openjdk/blob/master/Casks/adoptopenjdk11.rb
==> Name
AdoptOpenJDK 11
==> Artifacts
OpenJDK11U-jdk_x64_mac_hotspot_11.0.3_7.pkg (Pkg)
```

**Comment by MikeMcQuaid** [comment]
What's the output of `brew bundle dump`?

**Comment by Okeanos** [comment]
The output of `brew bundle dump` is:

```rb
tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "adoptopenjdk/openjdk/adoptopenjdk11"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
```

I guess then that simply using `adoptopenjdk11` or `adoptopenjdk8`in the original `Brewfile` is insufficient?

**Comment by MikeMcQuaid** [comment]
> I guess then that simply using `adoptopenjdk11` or `adoptopenjdk8`in the original `Brewfile` is insufficient?

Yep!

**Comment by Okeanos** [comment]
Would you have any idea on how to "fix" that in the upstream `adoptopenjdk` casks, i.e. make it consistent with what I expected to happen in the first place when creating the `Brewfile`? I'd be willing to do the actual work, I just have no idea what needs changing.

**Comment by MikeMcQuaid** [comment]
Can't be fixed in the casks, just need to use the correct `Brewfile` syntax as otherwise the reference is ambiguous.
