### ISSUE TITLE
Dump and install pinned versions

### ISSUE THREAD

**Issue by matt-continuousdelta** [Homebrew/homebrew-bundle#515]
It seems like `brew bundle dump --pinned` or similar should exist, to dump a Brewfile with pinned version numbers.

And `brew bundle install` should install versions specified in a Brewfile.

Apologies in advance if this repeats #439, or if this isn't the best place to suggest features vs report defects.

**Comment by MikeMcQuaid** [comment]
> Homebrew does not support installing specific versions of a library, only the most recent one, so there is no good mechanism for storing installed versions in a .lock file.
> If your software needs specific versions then perhaps you'll want to look at using Vagrant to better match your development and production environments.
https://github.com/Homebrew/homebrew-bundle#note
