### ISSUE TITLE
Casks from local formulae are included in dumps

### ISSUE THREAD

**Issue by dnicolson** [Homebrew/homebrew-bundle#520]
There are some apps (PhoneView, PixelSnap, AirBuddy) that do not provide a public download URL, so for the purpose of provisioning a new machine local Casks are required (`brew cask install phoneview.rb`).

The problem is the `brew bundle dump` command treats these normal Cask installs. As a result the Brewfile cannot be used to properly provision a new machine. A tap could be used instead, the problem of a public URL remains though.

It might make sense to exclude such Casks altogether from the dump, however, looking at the contents of the `/usr/local/Caskroom/` directory it appears it may not be possible to differentiate.

**Comment by jacobbednarz** [comment]
I would say the way forward is using a custom tap here in a private repository. There are a couple of guides on the internet about doing this but as long as you setup a `~/.netrc` most of it should work out of the box.

**Comment by dnicolson** [comment]
I agree a custom tap could be a solution, but not to the issue of `brew bundle dump` being a one way street with local Casks. From a cursory look it seems as though maybe there is not enough metadata available to make such a distinction?

**Comment by jacobbednarz** [comment]
I generally discourage the use of local casks as they are better utilised (and supported) by using taps instead. Happy to be persuaded however I can't see a good use case for local casks that can't be fulfilled better by a tap.

**Comment by colindean** [comment]
> I can't see a good use case for local casks that can't be fulfilled better by a tap.

I agree with @jacobbednarz on this. A privately-hosted tap is the best way to proceed here.

**Comment by MikeMcQuaid** [comment]
Agreed all around. Also, `brew bundle dump` output is designed to be something that can be modified by users. You may also be able to set `HOMEBREW_BUNDLE_CASK_SKIP` before you `brew bundle dump` to skip these.
