### ISSUE TITLE
mas app name with space can not be skipped

### ISSUE THREAD

**Issue by JounQin** [Homebrew/homebrew-bundle#525]
For example:

```sh
export HOMEBREW_BUNDLE_MAS_SKIP="Telegram\ Desktop"
```

**Comment by MikeMcQuaid** [comment]
Did you try using the `id` instead?

**Comment by JounQin** [comment]
I'm using `export HOMEBREW_BUNDLE_CASK_SKIP=$(brew bundle list --casks | paste -sd " " -)` to generate the command automatically.

**Comment by MikeMcQuaid** [comment]
`HOMEBREW_BUNDLE_MAS_SKIP` is not `HOMEBREW_BUNDLE_CASK_SKIP` so what are you using?

**Comment by JounQin** [comment]
Sorry, I'm using them both for Linux, just copied it incorrectly.

**Comment by MikeMcQuaid** [comment]
A PR doing something like https://github.com/Homebrew/homebrew-bundle/issues/517#issuecomment-507153167 is your best bet then.

**Comment by JounQin** [comment]
I don't understand, although I'm trying to skip to install on Linux, and it doesn't work as expected, but it should also won't work on macOS too (I tried).

So I think it's an issue with usage of `HOMEBREW_BUNDLE_MAS_SKIP` itself, not for Linux, this issue should not be closed.

**Comment by MikeMcQuaid** [comment]
Again: did you try using the `id` instead?

**Comment by JounQin** [comment]
It's generated automatically by `brew bundle list --mas`, I didn't find how to list ids?

**Comment by MikeMcQuaid** [comment]
Try the ids from  `brew bundle dump` instead.

**Comment by JounQin** [comment]
I mean I want to automatically to get them into a dynamic script, is there a simple way? Sorry I'm not so good at shell script.

**Comment by MikeMcQuaid** [comment]
We don't support either Linux or generating them from `brew bundle list --mas`. Can you try the IDs manually and, if it works for you, we may adjust the behaviour accordingly.

**Comment by JounQin** [comment]
It seems that does not work either.
