### ISSUE TITLE
Run a `system` command iff `:changed`?

### ISSUE THREAD

**Issue by OJFord** [Homebrew/homebrew-bundle#527]
For non-rubyists, if it's possible to do something like:
```ruby
# ! made up !
brew 'pre-commit',  when_changed: { system 'pre-commit install' }
```

it might be worth a readme example?

There's:
```ruby
unless system # ...
```
and:
```ruby
, restart_service: :changed
```

but I can't tell how (or even if it's possible) to combine those ideas.

From what little ruby I know, I think it ought to be possible to implement a '`when_changed`' arg to `brew` (et al.) that takes a block to execute when `:changed` is true? But I might even have got the block syntax wrong 🤷‍♂ 😄 .

(This `pre-commit` example is real, by the way. I encountered another where I wanted it recently, but I can't find it now. Basic pattern though is that installing 'thing' is not the end of intialising 'thing'; especially when it's a Brewfile in a specific dir vs. a 'system-wide' one.)

**Comment by MikeMcQuaid** [comment]
This is not possible, sorry. You'd need to write your own wrapper around `brew bundle`or, more likely, `brew install` for this case. I'm hesitant to add something relatively involved like this to the DSL unless we see a bunch more demand.

**Comment by OJFord** [comment]
Fair enough.

 I'll probably stick with my current 'workaround' (not really) which is to call `system` unconditionally on the following line, rather than write a wrapper, since it's usually possible to be idempotent, and if not a wrapper script that's the arg to `system` can easily be created - it just wastes time executing a possibly length initialisation when nothing's changed.

**Comment by OJFord** [comment]
Actually, for anyone else looking for this - note that that ^ only sort of works, it would take two runs to install and init: it seems that the `system` call is executed before any of the `brew`s.

Presumably bundle parses the whole file first, only _collecting_ brews/casks/et al. for execution all together at the end.

**Comment by MikeMcQuaid** [comment]
> Presumably bundle parses the whole file first, only _collecting_ brews/casks/et al. for execution all together at the end.

Yup 👍
