### ISSUE TITLE
brew bundle check doesn’t handle local formulae correctly

### ISSUE THREAD

**Issue by ydnar** [Homebrew/homebrew-bundle#539]
When bundle reads the `Brewfile`, it resolves the formula name by taking splitting on `/` and taking the last value. If you use a `Brewfile` to install a local formula, e.g. `brew "./formula/swift-grpc-nio.rb`, then `@name` resolves to `swift-grpc-nio.rb`, not `swift-grpc-nio`.

Would it be possible to strip the `.rb` off the resolved name if found so `brew bundle check` can operate correctly?

**Comment by MikeMcQuaid** [comment]
Local formulae are not handled well by Homebrew in general. I would remove them but I would likely break some existing workflows. I strongly recommend putting formulae in a tap instead.

**Comment by ydnar** [comment]
We’re using a monorepo, so a tap won’t work.

Homebrew handles the local formula just fine—we named it so it doesn’t collide with any public formulae. The only issue is `bundle check` fails because it thinks the tap is named with an `.rb` suffix.

**Comment by ydnar** [comment]
If it helps, I’m happy to either pay for the development of a fix or send a pull request.

**Comment by MikeMcQuaid** [comment]
> Homebrew handles the local formula just fine

It doesn't handle updates etc. correctly. 

> or send a pull request.

That seems like the best idea. I'll review one and consider merging if it's not too invasive.
