### ISSUE TITLE
Don't error when brew is outdated

### ISSUE THREAD

**Issue by glostis** [Homebrew/homebrew-bundle#540]
I am using `travis-ci` which proposes a feature that handles the installation of `homebrew` formulae. In my CI configuration file, I simply list the formulae names that I want to install, and behind the scenes `travis-ci` makes a `Brewfile` with them and then `brew bundle`s it.

The problem is the `macos` images of Travis do not always have the latest `brew` version, so regularly the `brew bundle` fails with
```
Error: Your Homebrew is outdated. Please run `brew update`.
Error: Kernel.exit
```
which in turn fails my build.

I found by digging in `brew bundle`'s code that the error comes from these lines: https://github.com/Homebrew/homebrew-bundle/blob/a544254c268b9eca64744d8b607dbe8e4b4133ac/cmd/brew-bundle.rb#L53-L56

I don't know to what extent it is critical for you to have the latest version of `brew` for `bundle` to work, but would it be possible maybe to pass this as a warning instead of an error?
Travis is always a bit late to catch up on the `brew` versions, so this is blocking for Travis users.

**Comment by colindean** [comment]
According to https://github.com/Homebrew/homebrew-bundle/commit/2e7ca50ab0059a5501599539c616956bdc42409c, homebrew-bundle requires ActiveSupport, which is provided in Homebrew 2.0.0+. 

The quick solution is to run `brew update` as early as you can in the CI workflow. 

What version of Homebrew is baked into the `macos` Travis image?

**Comment by MikeMcQuaid** [comment]
You need to `brew update` to use the latest version of `brew bundle`. Alternatively, `git reset --hard` to an older version.

**Comment by glostis** [comment]
Indeed `brew update` is a working solution to this problem, but it has the disadvantage of adding an incompressible 8-10 minutes to any build, which is a bit annoying when your builds normally take less than a minute.

@colindean I checked and the `brew --version` on the default `macos` image of Travis is:
```
Homebrew 1.6.9
Homebrew/homebrew-core (git revision 1b23; last commit 2018-06-25
```

This `brew` is more than one year old, so I can understand that `brew bundle` requires a newer version than this. I think this is definitely an issue with Travis and not with `bundle`.

If anyone reading this has the same issue as I did, a good working solution is to use a `macos` image that is newer than the default. At the time of writing this, the default is called `xcode9.4` and has `brew 1.6.9`, but the newest image called `xcode11` has `brew 2.1.9` which is enough for `bundle`. See here for the full list of Travis `macos` images: https://docs.travis-ci.com/user/reference/osx/#macos-version

**Comment by MikeMcQuaid** [comment]
> I think this is definitely an issue with Travis and not with `bundle`.

Agreed.

> At the time of writing this, the default is called `xcode9.4` and has `brew 1.6.9`, but the newest image called `xcode11` has `brew 2.1.9` which is enough for `bundle`.

👍
