### ISSUE TITLE
brewdle cleanup handling dependencies

### ISSUE THREAD

**Issue by exonintrendo** [Homebrew/homebrew-bundle#55]
Currently, using `Brewfile` as a 'whitelist' (using cleanup) will remove any installed dependencies for installed packages. A good example is installing `ffmpeg` and then running `brew brewdle cleanup` which removes the dependencies for `ffmpeg`.

I feel that the `cleanup` functionality should ignore/skip packages that are installed as dependencies for a package existing in the `Brewfile`. Otherwise, cleanup can break many installations.

**Comment by mikemcquaid** [comment]
Personally I think this is out of scope. You should use `cleanup` only when you've used `dump` previously to dump all packages and their dependencies. Homebrew does not store its dependencies so establishing them later is not trivial.

**Comment by mikemcquaid** [comment]
Passing on this.
