### ISSUE TITLE
dump doesn't respect --file=path

### ISSUE THREAD

**Issue by melgu** [Homebrew/homebrew-bundle#570]
The Brewfile is always dumped at the current directory, not respecting the `--file=path` argument.

**Comment by jacobbednarz** [comment]
@melgu Are able to please provide a more thorough reproduction case? Out of the box, this is working as expected.

```
$ pwd
/Users/jacob/Downloads

$ ls Brewfile*
ls: Brewfile*: No such file or directory

$ brew bundle dump --file=/tmp/Brewfile-example

$ ls Brewfile*
ls: Brewfile*: No such file or directory

$ ls /tmp/Brewfile*
/tmp/Brewfile-example
```

**Comment by melgu** [comment]
Found the error. My mistake, sorry. Didn't type the `=`.

**Comment by jacobbednarz** [comment]
great! thanks for the feedback!
