### ISSUE TITLE
Exec - conflict with global PATH

### ISSUE THREAD

**Issue by chrmod** [Homebrew/homebrew-bundle#588]
With given Brewfile:
```
brew 'node@12'
```

```sh
$ brew bundle exec -- node --version
# v10.15.0

$ brew bundle exec -- which node 
# /usr/local/opt/node/bin/node

$ /usr/local/opt/node/bin/node  --version 
# v12.12.0
```

Version 10.15.0 comes from the PATH.

**Comment by MikeMcQuaid** [comment]
`brew bundle exec` does not set the `PATH`. This is used for compilers to build against Homebrew dependencies: https://github.com/Homebrew/homebrew-bundle#exec.
