### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by y0y0z** [Homebrew/homebrew-bundle#589]
when i run `brew leaves`, i do get the formulas that i directly installed (without their dependencies, which are being installed automatically when executing `brew install`).

but when i execute `brew bundle dump --brews` i get a message saying
> Error: Formulae dependency graph sorting failed (likely due to a circular dependency): ...

i thought that `brew bundle dump --brews` should coincide with `brew leaves`. that is, i would expect that the output of `brew bundle dump --brews` will be `brew <LEAF>` for each `LEAF`, where `LEAF` is a leaf in `brew leaves` output.

if that is not the case, could you please explain why would i care to store formula dependencies in my `Brewfile`?

```shell
$ brew --version
Homebrew 2.1.16-87-gd65ad9f
```

**Comment by MikeMcQuaid** [comment]
I don't really understand your question but the output message explains how to resolve your circular dependency issue.

**Comment by y0y0z** [comment]
@MikeMcQuaid: there should not be a circular dependency, since only leafs should be present in the `Brewfile`. if there are leafs, there is no circular dependency by definition.

am i missing anything?

**Comment by MikeMcQuaid** [comment]
`brew bundle` does not use `brew leaves` or the same algorithm.

**Comment by y0y0z** [comment]
@MikeMcQuaid: i could deduce it, that is why it was totally strange that the outcome of the two are different. don't you think the need to be aligned?

**Comment by y0y0z** [comment]
@MikeMcQuaid: i want to contribute to the project, but you marked the issue as closed without having any discussion.

kinda funny that on your profile it is writter
> Rude people blocker
a camel does not see his own hump

**Comment by MikeMcQuaid** [comment]
> don't you think the commands need to be aligned (i.e. have corresponding output)?

No. They do different things for different use-cases. To change either to match exactly the other would render uses of the other to be broken.

> i want to contribute to the project

https://github.com/homebrew/brew/#contributing details how to do that. In short: submit pull requests. Issues asking questions are not contributions and are better done in our Discourse (https://discourse.brew.sh).

> but you marked the issue as closed

We only keep issues open if they are bugs or features that need or we wish to be worked on. This is consistent in the Homebrew organisation and across all open source projects I run.

> a camel does not see his own hump

I have not made anything resembling a personal attack on you in this issue and you have jumped to an insult (I take it as so regardless whether it is intended). I would like to ask you to retract that, please.

**Comment by y0y0z** [comment]
@MikeMcQuaid: you acted as a bully and only after i noted that, you have given explanation which you should have done before marking the issue as close. with that being said, **i truly respect and admire your work**.

i wanted to contribute to make the two command correspond to each other and was asking for your blessing.
 
> you have jumped to an insult

an allegory is not an insult and this discussion is way out of topic and unbeneficial.
