### ISSUE TITLE
Request: `brew bundle install --force`

### ISSUE THREAD

**Issue by nthapaliya** [Homebrew/homebrew-bundle#590]
Can we add a `--force` option to force installation/overwriting of installed casks? If I have "Firefox.app" already in `/Applications`, `brew bundle install` (rightly) refuses to install the cask. This option would be for people who really want to overwrite the existing one with a cask version.

In the meantime a workaround is something like
`brew cask install --force $(grep "^cask" ~/.config/brew/Brewfile | cut -d ' ' -f 2 | sed s/\"//g)` but it's ugly and prone to breakage.

**Comment by MikeMcQuaid** [comment]
`brew bundle list --casks | xargs brew cask install --force`
