### ISSUE TITLE
Cleanup tries to remove listed cask due to inconsistent naming

### ISSUE THREAD

**Issue by abeger** [Homebrew/homebrew-bundle#598]
I've discovered a variant of #519:

My `Brewfile` contained the following:
```
tap "homebrew/cask-versions"
cask "homebrew/cask-versions/adoptopenjdk8"
```
It wouls install just fine, but then when I ran a `brew bundle cleanup`, I would be told that `adoptopenjdk8` would be removed.

I threw a couple debug messages into `Bundle::Commands::Cleanup#casks_to_uninstall` and discovered that `Bundle::CaskDumper.casks(full_names_only: true)` lists the cask as `adoptopenjdk8`, but `kept_casks` lists it as `homebrew/cask-versions/adoptopenjdk8`. The two don't match up, so `cleanup` figures `adoptopenjdk8` can be removed.

Changing the listing to just be 
```
cask "adoptopenjdk8"
```
appears to have solved the immediate issue.

**Comment by MikeMcQuaid** [comment]
> Changing the listing to just be
> 
> ```
> cask "adoptopenjdk8"
> ```
> 
> appears to have solved the immediate issue.

👍 Use this instead.

**Comment by abeger** [comment]
OK, I'm just going to annotate a little more for the next person googling this issue:

Writing 
```
tap "homebrew/cask-versions"
cask "homebrew/cask-versions/adoptopenjdk8"
```
will install the app as `adoptopenjdk8` because `homebrew/cask-versions` has been tapped. Leave out the extraneous namespacing in the `cask` command.

Writing 
```
cask "homebrew/cask-versions/adoptopenjdk8"
```
without a `tap` will install the app as `homebrew/cask-versions/adoptopenjdk8` and not cause problems.

**Comment by abeger** [comment]
@MikeMcQuaid As a follow-up, I'd recommend altering this line in the README:

```
cask "homebrew/cask-fonts/font-charter"
```

It causes the same problem I encountered.

**Comment by MikeMcQuaid** [comment]
Actually I also think it should probably just print out a warning if you use the wrong format. Reopening with this in mind.
