### ISSUE TITLE
'brew bundle' stuck on packages with licenses.

### ISSUE THREAD

**Issue by kenorb** [Homebrew/homebrew-bundle#604]
My `Brewfile`:
```
brew "mssql-tools"
```

It's stuck when run:
```
brew bundle
```
It doesn't show anything.

I had to run with:
```
brew bundle -v
```
then the question is asked:

> Do you accept the license terms? (Enter YES or NO)

Bundle should detect the license and should print the output. And there should be a way to accept it in `Brewfile`.

**Comment by MikeMcQuaid** [comment]
This is an issue that needs to be fixed in the (non-Homebrew/homebrew-core) `mssql-tools` formula?

**Comment by kenorb** [comment]
Workaround: `export ACCEPT_EULA=y`.
