### ISSUE TITLE
Upgrades Even If --No-Upgrade Specified

### ISSUE THREAD

**Issue by Blackjacx** [Homebrew/homebrew-bundle#632]
Upgrades are performed even if no-upgrade is performed. This behavior siverges from similar, existing package managers like Bundler, Cocoapods, Carthage. There if you only execute an "install" you can be sure nothing is updated. This is especially good when the project is shared using git with multiple team mates.

**Comment by MikeMcQuaid** [comment]
`--no-upgrade` is not a documented or supported flag. Homebrew does not support workflows where packages are installed and not updated.

**Comment by Blackjacx** [comment]
Hmm but `brew bundle --help` gives me 🤔:

```
Install or upgrade all dependencies in a Brewfile.

    -v, --verbose         Print the output from commands as they are
                                     run.
    --no-upgrade        Don't run brew upgrade on outdated
                                     dependencies. Note they may still be
                                     upgraded by brew install if needed.
```
But ok good to know.

**Comment by MikeMcQuaid** [comment]
Apologies, I just checked the README (that's out of date and I'll fix it).

> Note they may still be upgraded by brew install if needed.

Does this not cover the behaviour your describe? Is `brew upgrade` being run when it shouldn't be?

**Comment by Blackjacx** [comment]
Well, when I run e.g. `bundle update` it updates and when I run `bundle install` it installs the versions from the lock file. All the major dependency managers behave this way. With `brew bundle` it is currently not possible to retain certain version on a git branch and other version on a different one.

**Comment by MikeMcQuaid** [comment]
This is not a normal language dependency manager and the lock file does not pin versions.
