### ISSUE TITLE
forcing short cask names makes it impossible to resolve ambiguous names

### ISSUE THREAD

**Issue by estraph** [Homebrew/homebrew-bundle#634]
When closing https://github.com/Homebrew/homebrew-bundle/issues/598 with https://github.com/Homebrew/homebrew-bundle/pull/600 we introduced logic which will always shorten fully-qualified cask names (tap + cask) into the short name (just cask).

Both of these taps contain a `adoptopenjdk8` cask:
- [`adoptopenjdk/openjdk`](https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/0336578702d597c5986820d11cfd27e63703a899/Casks/adoptopenjdk8.rb)
- [`homebrew/cask-versions`](https://github.com/Homebrew/homebrew-cask-versions/blob/52e364e73ffae05662df8c0f7b0391822ba12851/Casks/adoptopenjdk8.rb)

When using `brew cask` directly with just the short name, I initially get this error:

```
% brew cask install adoptopenjdk8
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
```

But when I provide the full name and it will install the desired cask:

```
% brew cask install homebrew/cask-versions/adoptopenjdk8
# works
```

The problem is that when specifying in a `Brewfile`, the new logic will force use of the ambiguous short name and fail:

```
tap "adoptopenjdk/openjdk"
tap "homebrew/cask-versions"
cask "homebrew/cask-versions/adoptopenjdk8"
```

```
% brew bundle
Warning: treating 'homebrew/cask-versions/adoptopenjdk8' cask as 'adoptopenjdk8'!
Please change `cask "homebrew/cask-versions/adoptopenjdk8"` to `cask "adoptopenjdk8"` in your `Brewfile`.
...
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
```

I propose the logic should not force short names unless a special flag is given. The default should be to take the name as given by the user, like `brew cask` does.

Related to https://github.com/Homebrew/homebrew-cask/issues/73730
Related to https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106

**Comment by estraph** [comment]
That was fast! Nice one @MikeMcQuaid - looks like that's working now, thank you.

**Comment by MikeMcQuaid** [comment]
You're welcome @estraph!
