### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by DylanYoung** [Homebrew/homebrew-bundle#644]
What options are supported by brewfile?  I can't find anything after extensive googling.  Even the main README mentions `unless` without describing it....

Can you point me to docs on the syntax of your DSL?

**Comment by jacobbednarz** [comment]
The DSL is defined at https://github.com/Homebrew/homebrew-bundle/blob/677f39d62a8aefdcbc091f193af1f7ddbee0052d/lib/bundle/dsl.rb

The individual components (`cask`, `brew`) are documented in their own repositories as bundle should be passing through any arguments or parameters as is.

**Comment by DylanYoung** [comment]
Those aren't docs :(

**Comment by MikeMcQuaid** [comment]
> Where are the docs?

In the README and `brew bundle --help`.

> Even the main README mentions `unless` without describing it....

`unless` is a Ruby keyword. `Brewfile` is a Ruby DSL.

> I think you should leave this issue open.

No, sorry, we don't leave issues open unless there's actionable work in them. As-is: there is not.

**Comment by DylanYoung** [comment]
Yes, so where's the description of the DSL.  I can write a DSL in python too, that doesn't mean it's going to have the same syntax. 

This is highly actionable.  There are zero docs, by your own admission.  If you'd like to keep it that way, I guess that's up to you.

**Comment by DylanYoung** [comment]
Here is the output of `brew bundle --help` in case you were curious:

```
Usage: brew bundle subcommand

Bundler for non-Ruby dependencies from Homebrew, Homebrew Cask and the Mac App
Store.

        --file=                      Read the Brewfile from this file. Use
                                     --file=- to pipe to stdin/stdout.
        --global                     Read the Brewfile from ~/.Brewfile.

brew bundle [install] [-v|--verbose] [--no-upgrade]
[--file=path|--global]

Install or upgrade all dependencies in a Brewfile.

    -v, --verbose                    Print the output from commands as they are
                                     run.
        --no-upgrade                 Don't run brew upgrade on outdated
                                     dependencies. Note they may still be
                                     upgraded by brew install if needed.

brew bundle dump [--force] [--describe] [--no-restart]
[--file=path|--global]

Write all installed casks/formulae/taps into a Brewfile.

        --force                      Overwrite an existing Brewfile.
        --describe                   Include a description comment above each
                                     line, unless the dependency does not have a
                                     description.
        --no-restart                 Do not add restart_service to formula
                                     lines.

brew bundle cleanup [--force] [--zap] [--file=path|--global]

Uninstall all dependencies not listed in a Brewfile.

        --force                      Actually perform the cleanup operations.
        --zap                        Remove casks using the zap command
                                     instead of uninstall.

brew bundle check [--verbose] [--no-upgrade] [--file=path|--global]

Check if all dependencies are installed in a Brewfile.

    -v, --verbose                    Print and check for all missing
                                     dependencies.
        --no-upgrade                 Ignore outdated dependencies.

brew bundle exec command

Run an external command in an isolated build environment.

brew bundle list [--all|--brews|--casks|--taps|--mas]
[--file=path|--global]

List all dependencies present in a Brewfile. By default, only Homebrew
dependencies are listed.

        --all                        List all dependencies.
        --brews                      List Homebrew dependencies.
        --casks                      List Homebrew Cask dependencies.
        --taps                       List tap dependencies.
        --mas                        List Mac App Store dependencies.
```

No mention of the DSL, not even the subcommands allowed.   I'm a big fan of brew-bundle, but it's not super useful for complex cases without docs.  It's especially confusing because there are a number of outdated docs on the net for old iterations of brew bundle.

**Comment by DylanYoung** [comment]
But I guess I'll start learning about Ruby DSLs since documentation doesn't seem to be a priority for you *sigh*.

**Comment by DylanYoung** [comment]
Perhaps you can answer this at least.

Is the following section of the man pages applicable to brew-bundle?

i.e. Can I define a custom external command and call it in a Brewfile?
```
CUSTOM EXTERNAL COMMANDS
       Homebrew, like git(1), supports external commands. These are executable
       scripts  that  reside  somewhere  in  the  PATH,  named brew-cmdname or
       brew-cmdname.rb, which can be invoked like brew  cmdname.  This  allows
       you to create your own commands without modifying Homebrew's internals.

       Instructions for creating your own commands can be found in  the  docs:
       https://docs.brew.sh/External-Commands
```

**Comment by MikeMcQuaid** [comment]
Please reread our Code of Conduct and adjust your communication accordingly: https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md#code-of-conduct

**Comment by DylanYoung** [comment]
How have I violated that code of conduct?  I'm sorry if I have.

**Comment by DylanYoung** [comment]
I came here with an issue that you've acknowledged exists.  I've done nothing but work with you to try to resolve that problem, respectfully and openly.

I will leave now.  Good luck with whatever's bugging you.

**Comment by MikeMcQuaid** [comment]
> I'm sorry if I have.

I appreciate the apology.

> I've done nothing but try to work with you to try to resolve that problem, respectfully and openly.

I have not found your communication to be respectful. For example:

> Good luck with whatever's bugging you.

Yes, I agree leaving is probably for the best, sorry.
