### ISSUE TITLE
Unknown command: bundle

### ISSUE THREAD

**Issue by brandon-leapyear** [Homebrew/homebrew-bundle#646]
Seeing this in our CI right now:
```
+ export HOMEBREW_BUNDLE_NO_LOCK=1
+ HOMEBREW_BUNDLE_NO_LOCK=1
+ brew bundle check --no-upgrade
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 93 (delta 4), reused 34 (delta 2), pack-reused 0
UnpacUnpacking objects: 100% (93/93), done.
Tapped (192 files, 262.8KB).
Error: Unknown command: bundle
+ brew bundle --no-upgrade
Error: Unknown command: bundle
```

I suspect it has something to do with the PR that was just merged #643 ?

**Comment by MikeMcQuaid** [comment]
You likely need to `brew update`. If that's not fixing it: run `brew config` and paste your output here.

**Comment by brandon-leapyear** [comment]
I'll try that, thanks. I thought `brew` automatically updates, though?

> it is a rolling release package manager
https://github.com/Homebrew/homebrew-bundle/pull/552#issuecomment-553178488

**Comment by jablko** [comment]
I'm investigating the [same error message](https://travis-ci.org/junegunn/fzf/jobs/653161626#L126). I'm using the Travis CI [Homebrew addon](https://docs.travis-ci.com/user/installing-dependencies#installing-packages-on-macos).

**Comment by jablko** [comment]
Adding `update: true` to my `.travis.yml` (documented [here](https://docs.travis-ci.com/user/installing-dependencies#installing-packages-on-macos)) did solve the problem. It sounds like Homebrew Bundle now depends on a newer version of Homebrew than the one included on the Travis CI VM?

**Comment by casconed** [comment]
> I'll try that, thanks. I thought `brew` automatically updates, though?
> 
> > it is a rolling release package manager
> 
> [#552 (comment)](https://github.com/Homebrew/homebrew-bundle/pull/552#issuecomment-553178488)

Travis (and maybe other CI systems) doesn't run `brew update`. From the Travis docs:

>By default, the Homebrew addon will not run brew update before installing packages. brew update can take a long time and slow down your builds.

**Comment by jablko** [comment]
Yes, I think Homebrew Bundle now depends on `external_ruby_v2_cmd_path`, introduced in Homebrew/brew@8a9dcad2c708ce945695029c5af79b4b3965a4de and distributed in [version 2.2.5](https://github.com/Homebrew/brew/commits/2.2.5).

**Comment by jablko** [comment]
Linking to the Travis CI community forum [thread](https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296).

**Comment by MikeMcQuaid** [comment]
> Travis (and maybe other CI systems) doesn't run `brew update`. From the Travis docs:
> > By default, the Homebrew addon will not run brew update before installing packages. brew update can take a long time and slow down your builds.

Travis should stop doing this. Running `brew update` can take some time (although it's been steadily improving) but not running `brew update` will break your builds (case in point here).

**Comment by casconed** [comment]
> Travis should stop doing this. 

No doubt, or at least stay more on top of making sure tools like homebrew are updated more than every six weeks or so. Would be nice also to get a deprecation notice from the software tools before functionality gets removed and things start breaking. 

Thanks for all your work on this project!

**Comment by MikeMcQuaid** [comment]
> Would be nice also to get a deprecation notice from the software tools before functionality gets removed and things start breaking.

No, sorry, you've misunderstood how this works:

- Homebrew (except for the package manager itself in Homebrew/brew) is a rolling release package manager which auto-updates by default so everyone is on the latest `master` branch of all repositories
- Travis CI have disabled this functionality for all taps and Homebrew itself
- They do not include e.g. `brew bundle` in their image at a supported version
- When you `brew tap` in their unsupported configuration (it normally auto-updates) you end up on the latest version of a tap which will likely fail

I'm not sure how we can really address this beyond "don't allow people with auto-update disabled to tap new taps" which will break things even further for Travis CI users (but perhaps is warranted).

> Thanks for all your work on this project!

Thanks for your kind words: they are genuinely appreciated.

**Comment by jablko** [comment]
It sounds like some Travis CI users [notice the performance](https://github.com/cyberbotics/webots/pull/1393) of `brew update`? Maybe when Travis updates macOS virtual machines, if they include the current version of Homebrew, they should also include the current version of Homebrew Bundle? You could still set `update: true` to get the latest version of both, but you wouldn't end up with this mismatch between the latest version of one and stale version of the other?

**Comment by casconed** [comment]
@jablko the issue was the other way around - the Travis image includes an older version of Homebrew, and was tapping the latest version of Bundle. @MikeMcQuaid is right - the answer is to just always run the auto-update.

**Comment by MikeMcQuaid** [comment]
Ultimately this is all down to Travis. I (and Homebrew) stopped using them years ago personally due to the host of problems with their macOS workers (performance, reliability, stuff mentioned here).

**Comment by jablko** [comment]
I opened a [macOS Packer Templates PR](https://github.com/travis-ci/packer-templates-mac/pull/13) to add Homebrew Bundle to the macOS images. Does that look right? Aside from the fact that disabling auto-update will continue to cause mismatches with other taps ...

Incidentally I tried adding `env: HOMEBREW_NO_AUTO_UPDATE=` to my `.travis.yml` (unset HOMEBREW_NO_AUTO_UPDATE) but this didn't provoke Homebrew to auto-update and resolve the current error, unlike `update: true` does. I'm not sure how Travis is disabling auto-update, but haven't investigated further.

**Comment by MikeMcQuaid** [comment]
> I opened a [macOS Packer Templates PR](https://github.com/travis-ci/packer-templates-mac/pull/13) to add Homebrew Bundle to the macOS images. Does that look right?

Have commented, thanks! Beyond that I'm not sure I know enough about Travis to help further.

**Comment by jablko** [comment]
Thank you for the feedback!
