### ISSUE TITLE
brew bundle cleanup hangs

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/homebrew-bundle#649]
Running `brew bundle cleanup --force` hangs when deleting files.
After orphan formulas are removed, brew appears to hang deleting files. I let it run for around 30 minutes before forcing it to terminate.

Other details:
- I have data in `/Volumes/Data/Homebrew` (a SMB network share)
- I am running the command as a normal user (not sudo)
- I cannot provide any more info for this one.

When I run `brew bundle cleanup` I get a list of files that will be deleted. I was able to clean up that text into a shell script that is a `rm -rf file` for each line of that dry-run output. Running that script, the operation completes quickly and sucessfully.

**Comment by MikeMcQuaid** [comment]
You'll need to figure this out yourself, there's nothing reproducible here, sorry.
