### ISSUE TITLE
Return non-zero when `$ brew bundle` fails

### ISSUE THREAD

**Issue by cknadler** [Homebrew/homebrew-bundle#67]
When running `brew bundle` now, if a package fails to install, the command still returns `0`. It would be awesome if the command returned `1` or some other non-zero value whenever it encounters an error.

For example, given the following Brewfile:

```
# Brewfile
brew 'node'
brew 'some-package-that-doesnt-exist'
```

```
$ brew bundle
Succeed to install node
Error: No available formula for some-package-that-doesnt-exist 
Searching formulae...
Searching taps...
Fail to install some-package-that-doesnt-exist

Success: 1 Fail: 1

$ echo $?
0
```

**Comment by mikemcquaid** [comment]
Agreed, good idea.
