### ISSUE TITLE
Installing pinned version from tap

### ISSUE THREAD

**Issue by endorama** [Homebrew/homebrew-bundle#674]
Hello, I'm successfully using `bundle` in multiple projects, but I found a strange behaviour which seems unexpected.

Using a `Brefile` of 

```
brew "go-task/tap/go-task@2.8.0"
```

or

```
tap "go-task/tap"
brew "go-task@2.8.0"
```

`brew bundle` is not able to find the proper Formula and fails:

```
Warning: 'go-task/tap/go-task@2.8.0' formula is unreadable: No available formula with the name "go-task/tap/go-task@2.8.0"
Error: No available formula with the name "go-task/tap/go-task@2.8.0"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
Error: No similarly named formulae found.
==> Searching for similarly named formulae...
Installing go-task/tap/go-task@2.8.0 has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
Check for differences in your Brewfile.lock.json!
```

From my understanding of the README it should be possible to pin Formulae version, but seems not to be working for Formulae coming from taps? Is this expected?

Using the Formula without the version constraint works as expected.

Thanks for your help!

**Comment by MikeMcQuaid** [comment]
You need to create a dedicated formula called `go-task@2.8.0`.

**Comment by endorama** [comment]
Thanks for the answer! And sorry for the silly question, I had no idea the underlying system was so simple :)

**Comment by MikeMcQuaid** [comment]
No worries!
