### ISSUE TITLE
Adjust output of check --verbose --no-upgrade

### ISSUE THREAD

**Issue by Nef10** [Homebrew/homebrew-bundle#682]
I am running  `brew bundle check --verbose --no-upgrade` and get the output:
```
brew bundle can't satisfy your Brewfile's dependencies.
→ Formula ffmpeg needs to be installed or updated.
Satisfy missing dependencies with `brew bundle install`.
```

Could it be adjusted to exclude the `or updated` part when running with `--no-upgrade`? I find it a little bit confusing.

Thanks!

**Comment by Nef10** [comment]
@MikeMcQuaid wow, thanks for the quick turnaround :)

**Comment by MikeMcQuaid** [comment]
You're welcome!
