### ISSUE TITLE
Errors running brew bundle from Brewfile

### ISSUE THREAD

**Issue by wlbentley** [Homebrew/homebrew-bundle#691]
On MacOS Mojave:
```
$ sw_vers -productVersion
10.14.6
$ brew --version
Homebrew 2.2.15
Homebrew/homebrew-core (git revision 632b9; last commit 2020-05-08)
Homebrew/homebrew-cask (git revision 6f369; last commit 2020-05-08)
```
I am developing a group of specialized Brewfiles, and when I enter:
`$ brew bundle --file="homebrew/Brewfile-shell"`
all the packages in my Brewfile are successfully upgraded/used as appropriate.

However, both before and after `brew bundle` executes the items listed in the Brewfile, a series of errors are thrown:
```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
...
```
My Brewfile begins like this:
```
brew "ack"
brew "bash"
brew "bash-completion"
```
and the resulting errors are posted in [this Gist](https://gist.github.com/wlbentley/00e2673f8e4e58b89eea6e6e067c677f).

As I said, the actual install/upgrade seems to be occurring as expected. It's just the pile of errors before and after the packages are installed that the problem occurs.

Thanks for creating this very useful extension to Homebrew.

**Comment by colindean** [comment]
Those all look like errors from a _Python_ process. What's in your Brewfile that would be running a Python subprocess as a part of its installation?

**Comment by wlbentley** [comment]
Nothing that I can see. Pure `brew "<package>"` listing.

Here is the complete [Brewfile-shell](https://gist.github.com/wlbentley/4aa4e822fc9af2d5550c98df9a1330b5) if you want to take a look.

**Comment by MikeMcQuaid** [comment]
Sorry, this is an issue with your personal setup.

**Comment by wlbentley** [comment]
Thank you. That helped me find a bad directory in $PATH that I wasn't aware of.
