### ISSUE TITLE
`brew bundle cleanup` didn't exit

### ISSUE THREAD

**Issue by latipun7** [Homebrew/homebrew-bundle#699]
## Actual Behavior

I run `brew bundle cleanup` but the script didn't exit unless I force exit with CTRL+C, and it's return non-zero exit code.

```bash
❯ brew bundle cleanup
Would uninstall formulae:
cowsay

y
yes

^[
no
exit
q
:q
^C
❯
```

The behavior same as when I run `brew bundle cleanup -f`

```bash
❯ brew bundle cleanup -f
Uninstalling coreutils... (569 files, 19.2MB)
Uninstalling icu4c... (258 files, 76.6MB)
Uninstalling node... (4,658 files, 69.1MB)
Uninstalling patchelf... (8 files, 925.5KB)
Uninstalling yarn... (14 files, 5.1MB)
Uninstalled 5 formulae



^C
❯
```

## Expected Behavior

After listing what cleanup candidate with `brew bundle cleanup`, the script should exit with 0 status. After successfully uninstalled with `brew bundle cleanup -f` the script should exit with 0 status, unless if uninstall found errors the script should exit with non-zero status.

## Environment to Reproduce that Behavior

- Ubuntu 20.04 LTS on Windows 10 x86_64
- Homebrew 2.2.17-20-g731c723
- Homebrew/linuxbrew-core (git revision 8f344; last commit 2020-05-19)
- Homebrew/bundle (git revision: "995b689c4e0fbe3cb79674929b5ed326e647cd29")

Let me know if you need more info. Thanks.

**Comment by MikeMcQuaid** [comment]
> Let me know if you need more info.

What is in your `Brewfile`?

**Comment by latipun7** [comment]
> What is in your `Brewfile`?

`Brewfile`

```
tap "homebrew/bundle"
tap "homebrew/core"
brew "bat"
brew "cmatrix"
brew "fortune"
brew "fzf"
brew "gcc"
brew "htop"
brew "lolcat"
brew "lsd"
brew "midnight-commander"
brew "neofetch"
brew "sl"
brew "zsh"
```
That file initially generated from `brew bundle dump`.

**Comment by MikeMcQuaid** [comment]
Please run `brew bundle --verbose` to figure out what command is blocking.

**Comment by latipun7** [comment]
The command only blocked on `cleanup`. So when I run `brew bundle --verbose` its exit successfully.
```log
❯ brew bundle --verbose
Skipping install of homebrew/bundle tap. It is already installed.
Using homebrew/bundle
Skipping install of homebrew/core tap. It is already installed.
Using homebrew/core
Skipping install of bat formula. It is already up-to-date.
Using bat
Skipping install of cmatrix formula. It is already up-to-date.
Using cmatrix
Skipping install of cowsay formula. It is already up-to-date.
Using cowsay
Skipping install of fortune formula. It is already up-to-date.
Using fortune
Skipping install of fzf formula. It is already up-to-date.
Using fzf
Skipping install of gcc formula. It is already up-to-date.
Using gcc
Skipping install of htop formula. It is already up-to-date.
Using htop
Skipping install of lolcat formula. It is already up-to-date.
Using lolcat
Skipping install of lsd formula. It is already up-to-date.
Using lsd
Skipping install of midnight-commander formula. It is already up-to-date.
Using midnight-commander
Skipping install of neofetch formula. It is already up-to-date.
Using neofetch
Skipping install of sl formula. It is already up-to-date.
Using sl
Skipping install of zsh formula. It is already up-to-date.
Using zsh
Homebrew Bundle complete! 15 Brewfile dependencies now installed.

❯ 
```
I think `--verbose` didn't print something useful on cleanup and the command still blocked. (`brew bundle cleanup --verbose`)

**Comment by MikeMcQuaid** [comment]
You may need to alter the code on your machine to print out debugging information for this. I've never seen anything like this. Closing until we have a reproducible case, sorry!
