### ISSUE TITLE
Skip already installed packages

### ISSUE THREAD

**Issue by nathany** [Homebrew/homebrew-bundle#70]
So I just created a Brewfile with a bunch of casks. If I modify the Brewfile and run `brew bundle` again, it doesn't appear to skip the casks that have already been installed. It's sitting there on each line for a while with "curl" up in the Terminal header.

**Comment by mikemcquaid** [comment]
This specifically only affects Casks. Agreed it should be fixed.

**Comment by nathany** [comment]
Thanks
