### ISSUE TITLE
Dump full tap paths

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-bundle#72]
If I've installed a formula as `brew install homebrew/versions/gcc48` then it should be dumped the same way in the `Brewfile` e.g. `brew 'homebrew/versions/gcc48` rather than the current version which is just `gcc48`. Additionally we could use this to simplify only dumping `tap`s that don't belong to one of these formulae (if necessary).

Adding this so I remember to do it at some stage but if anyone wants to beat me to it: feel free!

**Comment by xu-cheng** [comment]
This requires some change in the core. I plan to add `full_name` variable for `Formula` class, which will also benefit core commands(such as `brew deps`, `brew uses`, `brew outdated`, `brew search`).

I will begin to work on this after Homebrew/homebrew#39524 is merged.

**Comment by xu-cheng** [comment]
Also as a side note, dumping full path requires logic change in `cleanup` as well.

**Comment by mikemcquaid** [comment]
Yup, agreed all round.
