### ISSUE TITLE
Change location of default Brewfile?

### ISSUE THREAD

**Issue by clmay** [Homebrew/homebrew-bundle#721]
Currently, `brew bundle dump` writes the Brewfile to `~/Brewfile`. Is it possible to customize this behavior to read from and write to a different location?

**Comment by issyl0** [comment]
You can use the `--file` argument, eg `--file=Brewfile-test`, or `--file=/tmp/Brewfile`, to customize the location.

**Comment by clmay** [comment]
I should have been more specific. Is there a permanent configuration option that does not rely on passing a flag to the command at runtime?

**Comment by jacobbednarz** [comment]
You can set `HOMEBREW_BUNDLE_FILE` in your shell configuration file if you wish to consistently use one location.

**Comment by clmay** [comment]
Excellent, thank you. I came across some other variable that didn't seem to work. This is different, and seems to work perfectly. Much appreciated!
