### ISSUE TITLE
Error: undefined method `named' for #<OptionParser:0x00007fd371aadce0>

### ISSUE THREAD

**Issue by ni4** [Homebrew/homebrew-bundle#751]
Got the following issue today, while running tests via Github actions workflow.
Part of the log is as following:
```
2020-07-28T09:56:21.0357840Z ==> Tapping homebrew/bundle
2020-07-28T09:56:21.0750650Z Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
2020-07-28T09:56:21.7042000Z Tapped 1 command (199 files, 278.2KB).
2020-07-28T09:56:23.3651740Z Error: undefined method `named' for #<OptionParser:0x00007fd371aadce0>
2020-07-28T09:56:23.3657780Z Please report this bug:
2020-07-28T09:56:23.3658760Z   https://github.com/Homebrew/homebrew-bundle/issues
2020-07-28T09:56:23.3659420Z /usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:88:in `bundle'
2020-07-28T09:56:23.3660760Z /usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
2020-07-28T09:56:23.3700670Z ##[error]Process completed with exit code 1.
```

Environment details:
https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

Any advice?
Thanks.

**Comment by natalia-osa** [comment]
I have the same issue (running on Birtrise CI), was just writing the description of it.

```
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (105 files, 265.9KB).
Error: undefined method `named' for #<OptionParser:0x00007fb41faec268>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:88:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

**Comment by CoffeeFlux** [comment]
We're similarly hitting this in https://github.com/dotnet/runtime with Azure DevOps.
```
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (199 files, 278.2KB).
Error: undefined method `named' for #<OptionParser:0x00007fb901b2ab80>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:88:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
You need to ensure that you're running `brew update` before running `brew bundle`.

**Comment by MikeMcQuaid** [comment]
(as the latest Homebrew/brew tag will avoid this issue)

**Comment by natalia-osa** [comment]
I'm afraid doing brew bundle will increase build time quite a lot. 

However, changing the script to run `brew install` before `brew bundle` fixed the issue.

**Comment by MikeMcQuaid** [comment]
> I'm afraid doing brew bundle will increase build time quite a lot.

You mean `brew update`? Yes but it will fix the issue 😉.

> However, changing the script to run `brew install` before `brew bundle` fixed the issue.

That's just doing `brew update --preinstall` (currently undocumented but I'm going to update it). You can do that instead and it'll be a bit faster.

**Comment by MikeMcQuaid** [comment]
Closing this issue but keeping it pinned for discoverability.

**Comment by Robuske** [comment]
> That's just doing `brew update --preinstall` (currently undocumented but I'm going to update it). You can do that instead and it'll be a bit faster.

@MikeMcQuaid  Out of curiosity, what exactly `--preinstall` does? How is it different to `brew update` + `brew bundle`?

**Comment by natalia-osa** [comment]
@Robuske PS. It does not do `brew bundle.` It is just a faster way to do `brew update`. Why is a good question :-)

**Comment by MikeMcQuaid** [comment]
`brew install` essentially does `brew update --preinstall && brew install`. `brew bundle` will in future start running `brew update --preinstall` before commands but, for now, if you find `brew update` too slow: `brew update --preinstall` will be a bit faster for CI. Note the reason it's faster is because it won't e.g. show you formula versions that were updated.
