### ISSUE TITLE
Improper line breaks processing for formulas with multiline descriptions when use `brew bundle --describe dump`.

### ISSUE THREAD

**Issue by yumitsu** [Homebrew/homebrew-bundle#757]
Hello. I have a formula installed from tap with such description:
```
msoap/tools/shell2http: stable 1.13
Executing shell commands via simple http server

Settings through 2 command line arguments, path and shell command.
```
The formulæ `desc` itself contains line break characters:
```
desc "Executing shell commands via simple http server\n\nSettings through 2 command line arguments, path and shell command.\n\n"
```

And that's what we get in our Brewfile for this formulæ after `brew bundle --describe dump` run:
```
# Executing shell commands via simple http server

Settings through 2 command line arguments, path and shell command.


brew "msoap/tools/shell2http"
```
I know that `desc` must contain an one-line description, but maybe it's better to strip line breaks?

**Comment by colindean** [comment]
Thanks for reporting this problem.

`desc` should be one line and is for all official formulae. It'd be more correct to submit a PR to that repo to fix the non-conformant formula.

I'd entertain a PR that prepended `#` to all lines in the desc as a defensive measure against non-conforming formulae `desc`.

**Comment by colindean** [comment]
I'm wrong. The [formula desc cop](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/rubocops/formula_desc.rb ) lists no such limitation/check, so I'll have at this.
