### ISSUE TITLE
AWS@Apple Brew Configuration

### ISSUE THREAD

**Issue by allan-apple** [Homebrew/homebrew-bundle#771]
== AWS@Apple Brew Configuration ==
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 5064 (delta 3), reused 3 (delta 0), pack-reused 5050
Receiving objects: 100% (5064/5064), 1.12 MiB | 1.22 MiB/s, done.
Resolving deltas: 100% (2972/2972), done.
Tapped (103 files, 1.5MB).
Error: undefined method `named' for #<OptionParser:0x00007f9cddb68b00>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:88:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'

**Comment by MikeMcQuaid** [comment]
`brew update`.
