### ISSUE TITLE
Support for boot-time service registration

### ISSUE THREAD

**Issue by luizberti** [Homebrew/homebrew-bundle#787]
**Currently, the DSL for `brew 'formulae', restart_service: true` does not allow registering a service at boot, which is normally done by `sudo`ing the call to `brew services [re]start`.** Only login services are supported at the moment.

This was [previously brought up](https://github.com/Homebrew/homebrew-bundle/pull/96#issuecomment-123231397) on the PR that originally implemented this feature, and the [reason for not doing so that was given at that time (2015)](https://github.com/Homebrew/homebrew-bundle/pull/96#discussion_r34972600) was that a `sudo`ing mechanic hadn't been worked out for `brew bundle` yet. As time passed and we got `cask` integration on `bundle` however, a `sudo`ing mechanic is already in place, where `cask` will ask for `sudo` when required.

**In light of these changes, and the current state of `bundle`, can we revisit the decision of not supporting `sudo` for service registration in the `bundle` DSL?**

My specific use case is that I use `unbound` listening on `127.0.0.1:53` for all DNS resolution system-wide. It needs `sudo` because it tries binding to a low port number, as well as for registering the service at boot time (otherwise DNS is dead until I login).

Currently this involves nasty workarounds with parsing `brew bundle install` output, and it would be nice if Homebrew supported this directly (quick question if I may since I am already here, is using `system 'sudo brew services restart unbound'` on the current DSL a better workaround for this, or are there caveats to this approach and sub-shelling `brew`?)

**Comment by MikeMcQuaid** [comment]
> As time passed and we got `cask` integration on `bundle` however, a `sudo`ing mechanic is already in place, where `cask` will ask for `sudo` when required.

Cask has always done this whereas we still don't have logic for `brew bundle` to do so



> quick question if I may since I am already here, is using `system 'sudo brew services restart unbound'` on the current DSL a better workaround for this

This seems sensible to me. 

Passing on this for now given there's a workaround. If you're interested in creating a PR to support this a bit more nicely: we'd review it!
