### ISSUE TITLE
Proposal: add a `bundle converge` command that does `bundle cleanup --force` + `bundle`

### ISSUE THREAD

**Issue by aramprice** [Homebrew/homebrew-bundle#793]
Not sure if this would be useful for other folks but I find myself often "converging" my machine to ensure that I have all, and only the things specified in my Brewfile are installed.

Curious if other folks might find this useful. If so happy to work on a PR. No attachment to `converge` as the command's name.

**Comment by issyl0** [comment]
Another idea: run `bundle` automatically at the end of `brew cleanup --force`?

**Comment by MikeMcQuaid** [comment]
I think a separate command would be a bit overkill for this. Either having the two separate commands we have now or a e.g. `brew bundle cleanup --install` (naming could change) makes sense to me.

**Comment by aramprice** [comment]
I agree that adding another subcommand seems crowded maybe. The urge to keep the breadth of subcommands limited.

To me both `install` as part of `cleanup`, or `cleanup --install` feel a little cognitively surprising, though you all probably know the user base better.

If you all are interested can probably cobble something together for a PR over the next few weeks/month if you all are up for making the decision about where to hang this functionality. Here are the options so far, with a few additional ideas thrown in:

1. teach `cleanup --force` to run `install`
1. teach `cleanup` a new `--install` flag
1. teach `install` a new `--cleanup` (or `--converge`, or ??) flag
1. add `converge` command
1. ...?

**Comment by jacobbednarz** [comment]
I feel this _could_ hang off `brew bundle cleanup` but looking a bit broader for use cases, I wonder if a single command would be more viable if it was instead targetted at drift detection and a flag available to that command was a way to resync the desired and actual. It seems like this could be separated and became used in automation much like `bundle check` is now.

**Comment by MikeMcQuaid** [comment]
> * teach `cleanup --force` to run `install`
> * teach `cleanup` a new `--install` flag
> * teach `install` a new `--cleanup` ~(or `--converge`, or ??)~ flag

I'm game for any of these.

Hanging off `cleanup` makes a little more sense to me because `install` gets a lot more usage than `cleanup` and this functionality would be an extension for a greater proportion of existing users of `cleanup` compared to existing users of `install`.

**Comment by aramprice** [comment]
My vote would be for `install --cleanup`. To me running `--cleanup` as part of installation feels more intuitive than running `--install` as part of cleaning up (removing software).

Maybe adding the flag to `install` would help introduce more folks to the idea of `cleanup`? Not sure if that's desirable or not.

**Comment by MikeMcQuaid** [comment]
Makes sense to me @aramprice 👍🏻

**Comment by aramprice** [comment]
I created https://github.com/Homebrew/homebrew-bundle/pull/795. Perhaps we move discussion there?
