### ISSUE TITLE
Pin a formula to a specific version

### ISSUE THREAD

**Issue by adithyabsk** [Homebrew/homebrew-bundle#802]
Hi @MikeMcQuaid, I recently saw that a PR was merged to remove tap pinning. (https://github.com/Homebrew/homebrew-bundle/pull/798) I am still a novice at brew bundle and am trying to understand how I might go about locking a particular installation to a specific version (e.g. `go` to `1.15.2`)

I came across this issue (https://github.com/Homebrew/homebrew-bundle/issues/455) which suggested pinning the tap rather than the formula. Since that will no longer be supported anyway, what's the best way to approach what I am trying to do.

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/homebrew-bundle#note. Sorry!

**Comment by adithyabsk** [comment]
Thanks for the reply. It not as much software I'm writing but my personal machine that this request was for but I understand if this is out of scope for brew bundle. I can totally go down the path of vagrant but I'd prefer to keep things simple (if possible) and stick to `brew` provided utilities.

To give you a sense of my use case, I'm trying to get my machine to a state where I can wipe and restore (to test my backup systems) my mac every 6 months-ish and am currently using a combination of brew, brew cask, and mas to track all of my system dependencies. Only being able to use the latest version of programming languages like golang isn't a huge dealbreaker but definitely would be nice to somehow translate pins to the Brew bundle file.

Is there an approach that I am missing or is vagrant (or another deployment management tool) my only path forward here.

**Comment by MikeMcQuaid** [comment]
> Only being able to use the latest version of programming languages like golang isn't a huge dealbreaker but definitely would be nice to somehow translate pins to the Brew bundle file.

You can use the e.g. `go@1.10` formulae. You don't want to be pinning catch versions and reinstalling every 6 months because you'll stop getting any security updates.

**Comment by adithyabsk** [comment]
@MikeMcQuaid Okay that makes sense, I guess in my case I'm not "really" looking to pin a patch version but rather a minor version so I guess this would work in my case. Thanks for clearing this up 🙂

**Comment by MikeMcQuaid** [comment]
@adithyabsk You're welcome!
