### ISSUE TITLE
dump --describe only works on formulae

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/homebrew-bundle#809]
Looks like `brew bundle dump --describe` outputs the `desc`ription for formulae only, and not Casks. Even though they too now have a `desc` stanza…

**Comment by MikeMcQuaid** [comment]
Good point/idea! Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by danielbayley** [comment]
@MikeMcQuaid See #810
