### ISSUE TITLE
Brewfile doesn't include casks information

### ISSUE THREAD

**Issue by wujekbogdan** [Homebrew/homebrew-bundle#812]
After running `brew bundle dump` I was expecting the `Brewfile` to also contain casks, but casks are not there. Is it a bug or is it how this feature is supposed to work? I didn't find any information about it neither in the docs nor in `--help`.

**Comment by MikeMcQuaid** [comment]
It outputs casks for me. If you can provide more debugging information we may be able to help but closing this as not reproducible for now.
