### ISSUE TITLE
Error: brew bundle --cleanup 

### ISSUE THREAD

**Issue by jechol** [Homebrew/homebrew-bundle#825]
1) brew bundle --cleanup failed.
```
$ brew bundle --cleanup
Error: invalid option: --cask
Warning: Failed to parse `brew info --cask --json`: 767: unexpected token at ''
```
2) But the same thing with 2 separate commands succeeded.
```
$ brew bundle
$ brew cleanup
```

**Comment by MikeMcQuaid** [comment]
Please run `brew update` and try again.

**Comment by fjarlq** [comment]
I'm hitting this error on one of my Macs, but not the other. I've run `brew update` on both Macs repeatedly, and both claim to be "Already up-to-date." But `brew -v` is reporting different version info. I don't know why, these systems should be identical. They're both running macOS 10.14.6 and are using the same bundle file.

On the Mac that is hitting this error, `brew -v` reports:

    Homebrew 2.5.11
    Homebrew/homebrew-core (git revision 94bef; last commit 2020-11-26)
    Homebrew/homebrew-cask (git revision 48027; last commit 2020-11-26)

On the Mac that isn't hitting this error, `brew -v` reports:

    Homebrew 2.5.11-253-g5786a89
    Homebrew/homebrew-core (git revision 94bef; last commit 2020-11-26)
    Homebrew/homebrew-cask (git revision 48027; last commit 2020-11-26)

**Comment by jechol** [comment]
@MikeMcQuaid 
It's still happening.

```console
❯ brew update
Already up-to-date.

❯ brew -v
Homebrew 2.5.11
Homebrew/homebrew-core (git revision 26c04; last commit 2020-11-26)
Homebrew/homebrew-cask (git revision 453d6b; last commit 2020-11-26)

❯ brew bundle --cleanup
....
Using Microsoft PowerPoint
Using Microsoft Word
Using Pages

Homebrew Bundle complete! 54 Brewfile dependencies now installed.
Usage: brew info [options] [formula]

Display brief statistics for your Homebrew installation.

If formula is provided, show summary of information about formula.

      --analytics                  List global Homebrew analytics data or, if
                                   specified, installation and build error
                                   data for formula (provided neither
                                   HOMEBREW_NO_ANALYTICS nor
                                   HOMEBREW_NO_GITHUB_API are set).
......
  -h, --help                       Show this message.
Error: invalid option: --cask
Warning: Failed to parse `brew info --cask --json`: 767: unexpected token at ''
```

**Comment by lonelykid** [comment]
I'm having the same issue. Here is my report https://github.com/Homebrew/brew/issues/9306 . I thought this is a Brew issue because ``brew info --cask`` does not work by itself either.

**Comment by fjarlq** [comment]
@MikeMcQuaid This error is still happening.. I think because HOMEBREW_VERSION is now 2.5.12, which is greater than 2.5.11, so cask_dumper.rb decides to use the 2.6 command format. I wonder if that test should be:
`if HOMEBREW_VERSION >= "2.6"`
