### ISSUE TITLE
`brew bundle cleanup` with `cask 'docker'` prints warning - but, doesn't work

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#831]
Link to my [Brewfile](https://gist.github.com/vraravam/8c9eae91a3750bed86b81e3a4711f842)

As you can see, I use the cask version of `docker`.

Command that I ran: `brew bundle cleanup --file=~/Brewfile`

With the latest version of homebrew, I am getting the following warning:
```
Updating Homebrew...
Warning: Treating docker as a formula. For the cask, use homebrew/cask/docker
Would untap:
homebrew/services
```

`brew --version` output is:
```
Homebrew 2.5.12
Homebrew/homebrew-core (git revision 1d64f7; last commit 2020-11-30)
Homebrew/homebrew-cask (git revision 3b3b6; last commit 2020-11-30)
```

**Comment by MikeMcQuaid** [comment]
This is a known issue that will be fixed when Homebrew/brew 2.6.0 is released. It cannot be fixed before that.

**Comment by vraravam** [comment]
I got the latest version of the `master` branch with this command:
```
git -C /usr/local/Homebrew checkout master && git -C /usr/local/Homebrew pull origin master 
```

And this is still the error I get:
```
Updating Homebrew...
Warning: Treating docker as a formula. For the cask, use homebrew/cask/docker
Untapping homebrew/services...
Untapped 1 command (49 files, 372.7KB).
```

The output of the `brew --version` command is:
```
Homebrew 2.5.12-334-gf496ef6
Homebrew/homebrew-core (git revision 8b469; last commit 2020-11-30)
Homebrew/homebrew-cask (git revision 687c6; last commit 2020-11-30)
```

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/releases/tag/2.6.0
