### ISSUE TITLE
Error: undefined method `exclude?' for "git-lfs":String

### ISSUE THREAD

**Issue by MalinnaLeach** [Homebrew/homebrew-bundle#840]
We have stated seeing this error on our Circle CI builds, and the builds are failing due to this.  I think it is due to this commit: [link](https://github.com/Homebrew/homebrew-bundle/commit/6fa389091d1b7450df0701d6a0d20e862bda6507).  Can this change be reverted, or a different fix put in place please?

Error: undefined method `exclude?' for "git-lfs":String
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:192:in `block in sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:21:in `formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:52:in `formula_names'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:138:in `installed_formulae'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:121:in `formula_installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:166:in `installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:36:in `install_change_state!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'

**Comment by MikeMcQuaid** [comment]
@MalinnaLeach Your Circle CI builds need to run `brew update`. This is done automatically when you run `brew bundle` unless it's been disabled by you, or more likely, Circle CI. If the latter: please complain to them and not us, thanks.

**Comment by kylefleming** [comment]
> @MalinnaLeach Your Circle CI builds need to run `brew update`. This is done automatically when you run `brew bundle` unless it's been disabled by you, or more likely, Circle CI. If the latter: please complain to them and not us, thanks.

@MikeMcQuaid The implication I believe you're making is that Homebrew's API isn't stable and one must be running a recent version of Homebrew in order to use the service. Is this assessment correct?

**Comment by jacobbednarz** [comment]
"Not stable" isn't the correct terminology here. Much of the Homebrew ecosystem (including `brew bundle`) follow the latest upstream changes as opposed to a defined tag or release point. This approach allows the tooling to self-update and keep users on recent versions to avoid the overhead on maintainers to support clients that haven't kept up to date.

**Comment by kylefleming** [comment]
> "Not stable" isn't the correct terminology here. Much of the Homebrew ecosystem (including `brew bundle`) follow the latest upstream changes as opposed to a defined tag or release point. This approach allows the tooling to self-update and keep users on recent versions to avoid the overhead on maintainers to support clients that haven't kept up to date.

I see. Thank you for the clarification.

**Comment by MikeMcQuaid** [comment]
A few things:
- `brew bundle` has, for a good few versions, auto-updated before it is run to avoid these sort of issues
- `brew update` gets you the latest version of both Homebrew/brew and Homebrew/homebrew-bundle
- For a good few versions we don't tell you to "Please report this bug" if you have auto-update disabled. We also tell you if you run `brew doctor` that we do not support running Homebrew (i.e. we will not fix bugs you experience) with auto-update disabled.
