### ISSUE TITLE
Running brew bundle - failure

### ISSUE THREAD

**Issue by welly** [Homebrew/homebrew-bundle#85]
Hello all,

On a completely fresh OSX Mountain Lion install. Homebrew is installed, brew tap homebrew/bundle completed correctly. Running: brew bundle results in the following:

```
Error: /usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:72: odd number list for Hash
        name: f["name"],
             ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:72: syntax error, unexpected ':', expecting '}'
        name: f["name"],
             ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:73: syntax error, unexpected ':', expecting '='
        full_name: f["full_name"],
                  ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:74: syntax error, unexpected ':', expecting '='
        args: args,
             ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:75: syntax error, unexpected ':', expecting '='
        version: keg["version"],
                ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:76: syntax error, unexpected ':', expecting '='
        dependencies: f["dependencies"],
                     ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:77: syntax error, unexpected ':', expecting '='
        requirements: f["requirements"],
                     ^
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:78: syntax error, unexpected '}', expecting '='
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:81: class definition in method body
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:89: syntax error, unexpected $end, expecting kEND
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle.rb:8:in `require'
/usr/local/Library/Taps/homebrew/homebrew-bundle/lib/bundle.rb:8
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:16:in `require'
/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd/brew-bundle.rb:16
/usr/local/Library/brew.rb:67:in `require'
/usr/local/Library/brew.rb:67:in `require?'
/usr/local/Library/brew.rb:155
```

**Comment by xu-cheng** [comment]
Unfortunately, `Homebrew/bundle` uses a few features which doesn't support Ruby 1.8.

@mikemcquaid Should we add Ruby 1.8 for this tool, especially considering OS X El is about to release.

**Comment by mikemcquaid** [comment]
@xu-cheng Up to you. On one hand I think it'd be relatively easy to fix these particular cases and on the other hand, as you say, OS X El Capitan isn't that far away. Regardless I guess a quick fix to detect the Ruby version and error-out would be good.

**Comment by xu-cheng** [comment]
> On one hand I think it'd be relatively easy to fix these particular cases 

The problem in this issue is easy to fix. However, it would require some work to add Ruby 1.8 support for `IO.popen` we used [here](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/utils.rb#L6). And there may be other features I used which don't support for Ruby 1.8.

>  Regardless I guess a quick fix to detect the Ruby version and error-out would be good.

I'm in favor this.

**Comment by mikemcquaid** [comment]
@xu-cheng Oh, one more thought is to make sure we check the Ruby version rather than the OS version and suggest they could `brew install ruby` to make it work (like `brew cask`)
