### ISSUE TITLE
Don't show casks installed by other Homebrew installations

### ISSUE THREAD

**Issue by Tyrubias** [Homebrew/homebrew-bundle#863]
I'm currently running two installations of Homebrew on a M1 machine  with one under `/usr/local` and the other under `/opt/homebrew`. 

When I run `brew bundle dump` (using the Homebrew installed under `/opt/homebrew`) it only outputs casks installed by the other Homebrew installation, but not casks installed under `/opt/homebrew`. Is it possible to only list casks installed under `/opt/homebrew` if the `brew bundle` command was run by the Homebrew installation under `/opt/homebrew`?

I would be happy to contribute this feature if I was given some pointers on where to start.

**Comment by jacobbednarz** [comment]
I don't _think_ so however that premise is based on the knowledge that most (if not all) of the Homebrew ecosystem doesn't really support multiple installations. 

Personally, I'm a 👎 on the feature if it isn't already in place as it sounds pretty easy to get into a situation where unexpected behaviour starts popping up.

**Comment by Tyrubias** [comment]
@jacobbednarz I understand your concern. I brought this up because `brew bundle dump` does only include the formulae installed by the "current" Homebrew. I believe this is because it uses `Formula.installed`, but listing casks just parses the output of `brew list --cask`. Since I don't have the `/opt/homebrew` installation as `brew` in my `$PATH`, none of the casks installed `/opt/homebrew` are listed when I run this command.
