### ISSUE TITLE
brew bundle doesn't handle external taps correctly

### ISSUE THREAD

**Issue by jabenninghoff** [Homebrew/homebrew-bundle#866]
After PR #864 was merged, `brew bundle` doesn't handle external taps correctly, and always wants to install (or uninstall for `cleanup`) external taps.

Steps to reproduce:
```
$ cat Brewfile-test
tap "jabenninghoff/edge"
cask "jabenninghoff/edge/transcriptions"

$ brew bundle --file Brewfile-test install
Installing transcriptions
Homebrew Bundle complete! 1 Brewfile dependency now installed.

$ brew bundle check --file Brewfile-test
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
```

I expected the `brew bundle check` to note that the Brewfile dependencies are satisfied.

This also affects `brew clean` which always wants to remove casks from external taps.

**Comment by Tyrubias** [comment]
This is probably because the original method of listing cask names didn't include the tap, but the new method does. I'll open a PR to fix this.

**Comment by jabenninghoff** [comment]
> This is probably because the original method of listing cask names didn't include the tap, but the new method does. I'll open a PR to fix this.

That seems to be the case. I noted that the new method only includes the tap name for external (ie non-homebrew) taps, consistent with how `brew bundle` handles formulae.
