### ISSUE TITLE
bundle check doesn't seem to work

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-bundle#868]
# Description:
`brew bundle check || brew bundle --cleanup` - the `check` command always returns such that the `||` conditional doesn't get executed even when its supposed to (for eg if I have introduced a new formula into my `~/Brewfile`.

# Steps to reproduce:
1. Create a `Brewfile` with a single entry, eg `git`
2. Run `brew bundle`
3. Edit the `Brewfile` and add 1 more formula
4. Run `brew bundle check || brew bundle --cleanup` - nothing happens.

# Expected behavior
The last step should have triggered a new "bundle install" invocation

# Brew installation info (output of `brew config`:
```
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6874c1e4ca10d79b837bec7d1113f944db835dc8
Core tap last commit: 18 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.8
macOS: 11.2-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
```

**Comment by jacobbednarz** [comment]
@vraravam I'm unable to replicate this issue using the following steps:

- `echo 'brew "pidof"' > /tmp/Brewfile`
- `brew bundle --file=/tmp/Brewfile`
  ```
  Updating Homebrew...
  Installing pidof
  Homebrew Bundle complete! 1 Brewfile dependency now installed.
  ```
- `brew bundle check --file=/tmp/Brewfile; echo $status`
  ```
  Updating Homebrew...
  The Brewfile's dependencies are satisfied.
  0 
  ```
- `echo 'brew "unrar"' >> /tmp/Brewfile`
- `brew bundle check --file=/tmp/Brewfile; echo $status`
  ```
  Updating Homebrew...
  brew bundle can't satisfy your Brewfile's dependencies.
  Satisfy missing dependencies with `brew bundle install`.
  1
  ```

**Comment by vraravam** [comment]
@jacobbednarz - Not sure why, but, im able to reproduce on my machine. The alias I use is this: `alias bupc='brew upgrade; brew upgrade --cask; brew bundle check || brew bundle --cleanup; brew cleanup prune; brew cleanup --prune 1'`. I have this env var setup: `HOMEBREW_BUNDLE_FILE=~/Brewfile`

If there's a different alias that can be useful, please do advice.

**Comment by vraravam** [comment]
On a tangential note, why not have the `check` be done transparently among the first steps in `bundle install`? That way, the end user does not need to run the extra short-circuiting step

**Comment by jacobbednarz** [comment]
> Not sure why, but, im able to reproduce on my machine.

Can you try each of these steps individually on your machine and confirm they are working as expected? This doesn't look like a bug but an issue with how you're using it.

> On a tangential note, why not have the check be done transparently among the first steps in bundle install? That way, the end user does not need to run the extra short-circuiting step

This step takes too long for some installations so it's on the user to opt-in to use it.

**Comment by vraravam** [comment]
PFA the screenshots 
<img width="1251" alt="Screenshot 2021-01-04 at 7 22 37 AM" src="https://user-images.githubusercontent.com/69629/103494622-b88b6400-4e5d-11eb-9138-74fdb38b647c.png">
<img width="1255" alt="Screenshot 2021-01-04 at 7 22 50 AM" src="https://user-images.githubusercontent.com/69629/103494634-c0e39f00-4e5d-11eb-9df1-21e4a54df3c9.png">

**Comment by vraravam** [comment]
I have a `Brewfile` - but, I installed a formula that doesn't exist in the `Brewfile` - in this case, I tried `libpng`. The command with the `||` (or conditional) didn't do anything ie diddn't cleanup. Whereas, the 2 commands separately did do the cleanup

**Comment by MikeMcQuaid** [comment]
Please provide a minimally reproducible `Brewfile` for this and, if we can reproduce we'll reopen. Thanks!
