### ISSUE TITLE
bundle cleanup cask always cleans up macOS services

### ISSUE THREAD

**Issue by josh** [Homebrew/homebrew-bundle#869]
A `Brewfile` may contain and will correctly install macOS services on `brew bundle install`. But `brew bundle cleanup` will always attempt to remove them even if they are listed in the `Brewfile`.

```ruby
# Brewfile
cask "markdown-service-tools"
```

https://github.com/Homebrew/homebrew-cask/blob/3f07f816a5d8919e14c43fced157684cbf2b0ff7/Casks/markdown-service-tools.rb

It appears to be a regression of 54bedfff7fe913119d37499f95010a20ede126fd. I'm guessing that `brew list` prints out these services but maybe they aren't present in `Cask::Caskroom.casks`? I haven't investigated much further yet.

```
$ brew list --cask
markdown-service-tools
```

Thanks!

--- 

CC @Tyrubias @jacobbednarz @MikeMcQuaid 
References 54bedfff7fe913119d37499f95010a20ede126fd, https://github.com/Homebrew/homebrew-bundle/pull/864

**Comment by Tyrubias** [comment]
Just to clarify, does running `brew bundle cleanup` uninstall the cask as well? Or just the services?

**Comment by josh** [comment]
Eh, sorry, was initially a bad diagnosis on my part. Just looking into debugging the output of the new API. It seems to be specific to casks within custom taps

```ruby
@casks ||= `brew list --cask 2>/dev/null`.split("\n")
```

Looks like it would output the unqualified `foo`.

```ruby
Cask::Caskroom.casks.map(&:full_name)
```

But gives you the fully qualified `username/repo/foo`. A simple fix might just be use that short name instead of `full_name` but I wonder if the deeper issue is that it's diffing a list of unqualified vs qualified formulas somewhere else.

Still investigating, thanks for your patience.

**Comment by josh** [comment]
Ah, @Tyrubias you've already got a PR for this https://github.com/Homebrew/homebrew-bundle/pull/867. Nice, I can confirm that fixes this issue.
