### ISSUE TITLE
Add DSL for conditional installation

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-bundle#87]
I might have a `Brewfile` with `cask 'java'`. Problem is, I want to be able to use this on systems which may already have Java installed from somewhere other than `brew cask`.

Perhaps it'd be nice to have an API like:
```ruby
cask 'java', unless: "/usr/libexec/java_home --failfast"
```
that will only install Java if that command fails. If the `cask` is already installed it should still upgrade it.

**Comment by xu-cheng** [comment]
If we remove the `$SAFE` setting in `DSL#process`, then this is already supported. In that case, you can just do:
```ruby
cask 'java' unless system "/usr/libexec/java_home --failfast"
```

Personally I'm fine to remove `$SAFE` . It doesn't guarantee safety and seems to restrict the function in Brewfile as shown in your case.

**Comment by mikemcquaid** [comment]
Yeh, good idea. I'll have a look/think.
