### ISSUE TITLE
'brew bundle install' should launch 'brew update' before processing Brewfile

### ISSUE THREAD

**Issue by Fs00** [Homebrew/homebrew-bundle#872]
Today I've launched `brew bundle` to install packages from a Brewfile. When Brew Bundle tried to tap 'homebrew/cask', several cryptic errors like `Cask X is unreadable` occurred (something very similar as seen in [this issue](https://github.com/Homebrew/homebrew-cask/issues/63117)) and the operation failed.

In the end it turned out that I just needed to run `brew update` before launching Brew Bundle. brew command does it automatically every time (presumably to avoid this kind of issues among other things), shouldn't Brew Bundle do the same?

**Comment by MikeMcQuaid** [comment]
> brew command does it automatically every time (presumably to avoid this kind of issues among other things), shouldn't Brew Bundle do the same?

It does.

**Comment by Fs00** [comment]
Apparently it didn't on my end, because I had to do that manually.
Maybe that's because `brew update` is run only before installing formulae/casks and not taps?

**Comment by MikeMcQuaid** [comment]
> Apparently it didn't on my end, because I had to do that manually.

That's because your Homebrew version was too old. We cannot change past versions in this way.
