### ISSUE TITLE
Feature Request: Create Brewfile with minimal set of formulae/casks

### ISSUE THREAD

**Issue by jaymody** [Homebrew/homebrew-bundle#880]
A growing trend in package managers (like `pipenv` or `npm`) is to produce a specification with both the **minimal set of packages** (ones that were installed explicitily), as well as a **complete set of packages** that also include dependencies (for a deterministic build).

Bringing this feature to `brew` has been discussed before in issues #246 and #236 , and there was a [desire to implement it at some point when possible/feasible](https://github.com/Homebrew/homebrew-bundle/issues/236#issuecomment-259642740). I was wondering if this is still something that is of interest to bring to brew?

As a sidenote, I must admit, the use cases are definitely niche. For example, adding a `Brewfile` to your [`dotfiles`](https://dotfiles.github.io/) repo, but in those use cases, it would be nice to have a minimal specification of required packages instead of one that includes everything. Currently, the workaround is to either maintain your own set of packages (in some script or file), or to parse the output `brew leaves` and `brew list --casks` to produce your own `Brewfile`. Both workarounds are hacky, and the [latter is unreliable](https://github.com/Homebrew/homebrew-bundle/issues/246#issuecomment-262952993).

**Comment by jacobbednarz** [comment]
I don't think anything as changed in this space since those issues were closed and I'm still onboard with @MikeMcQuaid's comments around only keeping the top level packages in the Brewfile for the problems mentioned. 

As it stands, Homebrew doesn't guarantee a deterministic run in any form so if that is a goal, you're looking at the wrong tool.

**Comment by MikeMcQuaid** [comment]
> as well as a **complete set of packages** that also include dependencies (for a deterministic build).

The closest thing we have to a deterministic build is the `Brewfile.lock.json` file that's output.

> For example, adding a `Brewfile` to your [`dotfiles`](https://dotfiles.github.io/) repo, but in those use cases, it would be nice to have a minimal specification of required packages instead of one that includes everything.

It doesn't include everything. `brew bundle dump --force` doesn't install packages that were just installed as dependencies.

As a result: this is all pretty much implemented as much as it can be.

**Comment by wren** [comment]
> I don't think anything as changed in this space since those issues were closed 

> It doesn't include everything. `brew bundle dump --force` doesn't install packages that were just installed as dependencies.

@jacobbednarz @MikeMcQuaid Are y'all sure about this? Did something recently change?

I recently started seeing dependencies I didn't install in my brewfile (even though I'm using `brew bundle dump --force`). I don't know if maybe I did something, but I came here to file this same request (not knowing the history of it).

**Comment by wren** [comment]
I'm not very familiar with bundle, so please forgive me if this is the wrong approach, but when I run `git bisect` and `brew bundle dump`, it looks to me like [this commit](https://github.com/Homebrew/homebrew-bundle/commit/b1aa4ad3b5d7986b0ad1d3b1674650364e577d44) might have introduced a regression.

Before that commit, running `brew bundle dump` does not show dependencies. But starting with that commit (running on the same system), I get the dependencies in my brewfile.

**Comment by wren** [comment]
Actually, that might be a red herring above. The change below fixes the behavior for me, so my guess is there's an upstream problem in homebrew where everything has `installed_on_request` as true.

```diff
diff --git a/lib/bundle/brew_dumper.rb b/lib/bundle/brew_dumper.rb
index e07bfe1..97754e4 100644
--- a/lib/bundle/brew_dumper.rb
+++ b/lib/bundle/brew_dumper.rb
@@ -24,7 +24,7 @@ module Bundle

     def dump(describe: false, no_restart: false)
       requested_formula = formulae.select do |f|
-        f[:installed_on_request?] || !f[:installed_as_dependency?]
+        !f[:installed_as_dependency?]
       end
       requested_formula.map do |f|
         brewline = ""
```

Anyway, I'm not a ruby dev, so I don't have time to stumble through the homebrew code to continue hunting this down. Hope this has been useful!

**Comment by MikeMcQuaid** [comment]
> Are y'all sure about this?

Yes.

> Did something recently change?

No.

**Comment by wren** [comment]
> > Are y'all sure about this?
> 
> Yes.
> 
> > Did something recently change?
> 
> No.

Cool.

Anything about the other stuff I said?

**Comment by MikeMcQuaid** [comment]
@wren If you have a reproducible bug report: we can investigate it. Otherwise: nothing to add really, sorry.

**Comment by MikeMcQuaid** [comment]
@jaymody @wren I just noticed an edge case (I have on idea how long it's been there) where dependencies could be incorrectly marked as "installed on request" in their `Tab` (which is what `brew bundle` reads from). This should be fixed by https://github.com/Homebrew/brew/pull/10681 (but would require reinstalling everything not listed in `brew leaves` after it's merged).
