### ISSUE TITLE
not listing python in the brewfile intentionally ?  

### ISSUE THREAD

**Issue by joergister** [Homebrew/homebrew-bundle#887]
i noticed that although I ran `brew install python3` one day (and when I do` brew list --formula | grep python` today, it actually appears, python@3.8 and python@3.9 to be precise) `python3` does not appear in the `Brewfile` if I create one.
Is this intentionally or is this unexpected (unwanted) behaviour ?

**Comment by Rylan12** [comment]
`python3` is an alias for the `python@3.9` formula, so it will show up in the Brewfile under the official name (which is `python@3.9`). Does the Brewfile show `python@3.9` or `python@3.8`?

**Comment by joergister** [comment]
sorry, I must have miss-configured something. After I cleaned up the mess the tool worked as expected.
Sorry for the inconvenience
