### ISSUE TITLE
Recommended way to have previously installed (outside of bundle) cask applications treated as installed?

### ISSUE THREAD

**Issue by simensen** [Homebrew/homebrew-bundle#893]
My use case is running a Brewfile on a machine that already has some of the cask dependencies installed. Running `brew bundle install` several times results in output like the following every time:

```
==> Downloading https://downloads.slack-edge.com/releases/macos/4.12.2/prod/x64/Slack-4.12.2-macOS.dmg
Already downloaded: /Users/simensen/Library/Caches/Homebrew/downloads/427b2130fb060c1fb365430410d4f02271976427a444f21289213a0713894ee9--Slack-4.12.2-macOS.dmg
==> Installing Cask slack
Error: It seems there is already an App at '/Applications/Slack.app'.
==> Purging files for version 4.12.2 of Cask slack
Installing slack has failed!
```

I get that it is deciding to not overwrite the app. That makes sense. However, it would be nice to have either of the two options at this point:

 * Somehow inform `brew bundle` that this dependency was already installed
 * Somehow inform `brew bundle install` to install it anyway, likely with something like `--force`?

I tried `brew bundle install --force` but that did not seem to do what I'd expect. It seems like in #258, `brew cask install slack --force` would "fix" this in that it would actually replace the already existing installed application. I'd actually be fine with that behavior. However, it doesn't seem like `brew bundle install --force` is doing that. I'm... not exactly sure what `--force` means in this context, either, since the help docs are hard for me to understand. It *looks* like `--force` isn't actually doing anything at all for `brew bundle install` but I could be reading it incorrectly.

**Comment by MikeMcQuaid** [comment]
> It _looks_ like `--force` isn't actually doing anything at all for `brew bundle install` but I could be reading it incorrectly.

Correct. This isn't something that's currently supported (as you've noticed) and given there's a workaround (run the `brew install --force` command or manually delete it) I'm going to close this out. If you're interested, this does feel like something that would be a nice PR, though!
