### ISSUE TITLE
Brewfile from STDIN

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/homebrew-bundle#90]
It would be helpful to pipe the Brewfile into ```brew bundle```. This can allow for small modular Brewfiles without littering the filesystem.

**Comment by mikemcquaid** [comment]
Probably the best way would be for `--file` to take `-` as an argument to read from `STDIN`.

**Comment by xu-cheng** [comment]
This is already supported. You can do thing like:

```bash
echo "..." | brew bundle --file=/dev/stdin
```

**Comment by AlJohri** [comment]
:+1:
