### ISSUE TITLE
Make `brew bundle cleanup` safer

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-bundle#91]
I wonder if it makes sense to make `brew bundle cleanup` not do anything without either e.g. `--dry-run`, `--global` or `--force`. A coworker was just trying out `brew bundle` and managed to blow away almost all his installed formulae by mistake. I've personally never used `cleanup` without `--global` and I can see why it would be dangerous.

**Comment by xu-cheng** [comment]
Maybe make `--dry-run` as the default. And let `brew bundle cleanup -y` to do the actual cleanup.

**Comment by mikemcquaid** [comment]
Do you think `--global` needs that too?

**Comment by xu-cheng** [comment]
Yes.

**Comment by mikemcquaid** [comment]
Cool. Makes sense to me to make `--dry-run` the default and require `--force` for cleanup.

**Comment by technicalpickles** [comment]
> A coworker was just trying out brew bundle and managed to blow away almost all his installed formulae by mistake

That was me, so :+1: to this :grin:
