### ISSUE TITLE
Error: undefined method `named' for #<OptionParser:0x00007f9e1216acd0> in init.sh

### ISSUE THREAD

**Issue by balabababa666** [Homebrew/homebrew-bundle#935]
~/development/uc-frontend (master ✔) ᐅ ./scripts/init.sh

The _auth field already exists in /Users/trish.jin/.npmrc, skipping .npmrc generation
Setting origin to github

To use github for code review, run git push origin from your local branch
To create a new Pull Request for the new branch, run hub pull-request

Installing git hooks
Installed 17 git hooks
dev.local.compass.com already exists :
127.0.0.1	dev.local.compass.com
Installing root CA for dev.local.compass.com
The root CA was successfully added to the system keychain
Performing brew bundle...
Error: undefined method `named' for #<OptionParser:0x00007f9e1216acd0>
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:92:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'

**Comment by MikeMcQuaid** [comment]
`brew update`.
