### ISSUE TITLE
Add mas purchase support

### ISSUE THREAD

**Issue by michaelw85** [Homebrew/homebrew-bundle#938]
Hi,

I'm setting up a brewfile to use as a general setup for machines at the office.
I just added some apps from the app store using `mas` and got an error for an app I haven't installed yet.
For this purpose mas introduced the `purchase` command since version 1.7.
It would be nice if this could be added to a brew file. Like a fallback to use the purchase command for free apps.

**Comment by MikeMcQuaid** [comment]
Makes sense (if we can programmatically identify if apps are free). We'll review a PR.

**Comment by michaelw85** [comment]
> Makes sense (if we can programmatically identify if apps are free). We'll review a PR.

Not sure if that could be identified, an alternative would be to allow the "purchase" option then it's up to the brewfile creator to add it where needed. If the app is already purchased it will be installed. If it's installed it will throw a warning it was already purchased which can be ignored.

My current workaround will be to move the mas install command out of the brewfile into a bash script

**Comment by MikeMcQuaid** [comment]
> Not sure if that could be identified

If it cannot: is this not going to end up spending money with a `brew bundle` run? That's very 👎🏻

**Comment by michaelw85** [comment]
> > Not sure if that could be identified
> 
> If it cannot: is this not going to end up spending money with a `brew bundle` run? That's very 👎🏻

I just got an error on something that actually costs money. I don't think you can really purchase an app via this command. As far as I'm aware it's only to "purchase" free apps

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry. I'd be game on making `brew bundle` output telling the user to run `mas purchase` but I don't have faith that this command won't change behaviour in future.
