### ISSUE TITLE
Allow `--no-require-sha` and Brewfile `require_sha:false`

### ISSUE THREAD

**Issue by ppo** [Homebrew/homebrew-bundle#939]
> Cross-issue on [`homebrew-cask`](https://github.com/Homebrew/homebrew-cask/issues/102602)

### Provide a detailed description of the proposed feature

Allow to activate `require-sha` by default/globally via `HOMEBREW_CASK_OPTS="--require-sha"` and to deactivate when necessary using `--no-require-sha` or in a Brewfile `cask "name", args: { require_sha: false }`.

### What is the motivation for the feature?

I want to require all casks to have a checksum by default, globally.  
But as some formulae doesn't have one, I need a way to selectively deactivate it.

And of course I don't want to do the opposite; i.e. manually requiring only when available.

### Example use case

```
HOMEBREW_CASK_OPTS="--require-sha"
```

```
brew install --cask --no-require-sha font-roboto
```

Brewfile:
```
cask "font-roboto", args: { require_sha: false }
```

**Comment by jacobbednarz** [comment]
Let's leave the discussion in the linked issue until we have an outcome there as this repository will be dependant on that.

**Comment by jacobbednarz** [comment]
I've also just realised, this is already an example in the README :/
