### ISSUE TITLE
Cask args not accepting "no-gatekeeper"

### ISSUE THREAD

**Issue by wickles** [Homebrew/homebrew-bundle#940]
I am trying to make my Brewfile install some casks with the "no-gatekeeper" arg like was suggested here previously https://github.com/Homebrew/homebrew-bundle/issues/474. 

The response in that thread suggests that this is a missing feature that would need to be added. My understanding from the readme however is that I should be able to use a line like this. 
```
cask "betterzip", args: ["no-quarantine"]
```
However that results in an error. 
```
> % brew bundle check
Error: Invalid Brewfile: no implicit conversion of Array into Hash
```

What am I missing here? Are some args supported and some are not?

**Comment by EricFromCanada** [comment]
For formulae in a Brewfile, options are specified in an array, because they don't take arguments. For casks, though, they need to be specified as a map of keys and values, _and_ any hyphens need to be underscores (a fact the docs don't yet make clear).

So, this will work:
```
cask "betterzip", args: { no_quarantine: true }
```

Note that because this argument isn't a global cask option, it isn't saved in the installed cask's config (at `/usr/local/Caskroom/bdinfo/.metadata/config.json`) and so isn't included with `brew bundle dump`.

**Comment by wickles** [comment]
Interesting. I tried that before and it did not work. 

```
> % brew bundle check --debug 
Error: Invalid Brewfile: (eval):92: syntax error, unexpected ':', expecting =>
...terzip", args: { no-quarantine: true }
...                              ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:36:in `instance_eval'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:36:in `process'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:27:in `initialize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:69:in `new'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/checker.rb:69:in `check'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/check.rb:14:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:126:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

After playing with it some more I was able to get it working like this.
```
cask "betterzip", args: { quarantine: false }
```
I guess that makes sense then. Thanks for your help.

**Comment by EricFromCanada** [comment]
`quarantine: false` won't actually install with quarantine disabled, but `no_quarantine: true` will (note the underscore).

**Comment by wickles** [comment]
Shoot. Thanks. That works.
