### ISSUE TITLE
MikeMcQuaid thinks "Its generally A Bad Idea." to pin dependencies to version. please explain.

### ISSUE THREAD

**Issue by airtonix** [Homebrew/homebrew-bundle#946]
```
@figroc I can't see how that would work? We don't want to make it extremely easy to sit on old outdated versions because it's generally A Bad Idea.
```
_Originally posted by @MikeMcQuaid in https://github.com/Homebrew/homebrew-bundle/issues/547#issuecomment-561127997_

This is really inconvenient and goes against the principles of literally every other package manager.

**Comment by jacobbednarz** [comment]
The explaination is at https://github.com/Homebrew/homebrew-bundle#note as to why this isn't the case.

**Comment by MikeMcQuaid** [comment]
> This is really inconvenient and goes against the principles of literally every other package manager.

No, it doesn't.

You really don't want things like `mysql` that are network-accessible servers to not receive security updates just because your team forgets to bump them in a `Brewfile.lock`.
