### ISSUE TITLE
How to specify brew with condition and arg

### ISSUE THREAD

**Issue by dephiros** [Homebrew/homebrew-bundle#947]
I am trying to do something like this in `Brewfile`
```
brew "emacs-plus" if OS.mac?, args: ["with-ctags"]
```
but this is not working. Is this supported?

**Comment by mistydemeo** [comment]
The syntax needs to be valid Ruby syntax. You've placed the `if OS.mac?` in the wrong place in the line, and a comma can't go there. Try this:

```ruby
brew "emacs-plus", args: ["with-ctags"] if OS.mac?
```

**Comment by dephiros** [comment]
> The syntax needs to be valid Ruby syntax. You've placed the `if OS.mac?` in the wrong place in the line, and a comma can't go there. Try this:
> 
> ```ruby
> brew "emacs-plus", args: ["with-ctags"] if OS.mac?
> ```

Thank you for that. I am not familiar with `Ruby` but it is good to know that it follows Ruby syntax.
