### ISSUE TITLE
`brew bundle dump` needs updating for new `mas list` format

### ISSUE THREAD

**Issue by emilazy** [Homebrew/homebrew-bundle#952]
As of https://github.com/mas-cli/mas/pull/339, `mas list` gives a formatted list:

```
emily@yuyuko ~> mas list
1440147259  AdGuard for Safari       (1.9.13)
497799835   Xcode                    (12.5)
425424353   The Unarchiver           (4.3.1)
```

This confuses `brew bundle dump`, which is expecting a format without all the whitespace padding and includes it in the output. This will affect people who use `brew`'s `mas` integration once a new `mas` release is cut, which will likely be soon as it fixes the unnecessary upgrade problems [many people were having](https://github.com/mas-cli/mas/pull/346#event-4648375488) (indeed, I discovered this after building and installing the latest source from HEAD to fix this issue on my system).

```
emily@yuyuko ~> brew bundle dump --file=- | rg '^mas'
mas "1Password 7             ", id: 1333542190
mas "AdGuard for Safari      ", id: 1440147259
mas "Affinity Photo          ", id: 824183456
…
```

**Comment by jacobbednarz** [comment]
makes sense! are you interested in submitting a PR for this? I _think_ it should be pretty straight forward by adding a `.strip` onto the list before it is later used by the formatter.

**Comment by emilazy** [comment]
yep, moved this here after I found the responsible bit of code and started working on a patch :)
