### ISSUE TITLE
Saving `--no-quarantine`  to Brewfile with `brew bundle dump`

### ISSUE THREAD

**Issue by h0adp0re** [Homebrew/homebrew-bundle#962]
Hello! I've created a ticket over on https://github.com/Homebrew/homebrew-cask/issues/105635 which would add support for saving `--no-quarantine` to `Brewfile` with `brew bundle dump`.

The same thing was requested in #474 and #940 and it's mentioned in the latter that:
> Note that because this argument isn't a global cask option, it isn't saved in the installed cask's config (at `/usr/local/Caskroom/bdinfo/.metadata/config.json`) and so isn't included with brew bundle dump.

I myself can't write ruby so I plead anyone else to take this up whenever the ticket in homebrew-cask gets addressed.

**Comment by aahm-ami** [comment]
https://github.com/Homebrew/homebrew-bundle/issues/962#issue-890202292

**Comment by aahm-ami** [comment]
https://github.com/Homebrew/homebrew-bundle/issues/962#issue-890202292

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-bundle/issues/940#issuecomment-808334576 allows you to add this to the `Brewfile`. Are you requesting that `brew bundle dump` outputs this?

**Comment by R0LA1mRifcF8yAkk** [comment]
Yes, saving it with `brew bundle dump` was my idea. Currently I have to manually revert the lines I've added the flag to whenever I update my `Brewfile`. I can manage it well thanks to git but it is still tedious and prone to errors.

**Comment by MikeMcQuaid** [comment]
Out of interest: do you disable it because you find it annoying or because it's actually broken? It's a security feature so I'm tempted to say we shouldn't make it too easy to "set and forget" it.

**Comment by h0adp0re** [comment]
Some security apps make the feature annoying, for example anything that [Objective See](objective-see.com/) makes. Others need the old "right click -> open" while I know the app is legit and I would've run it anyway.

**Comment by MikeMcQuaid** [comment]
Hmm, sorry, passing on this. I think it should have slight friction like this when disabling a security feature.

**Comment by h0adp0re** [comment]
Ok, bummer. I'll close the accompanying cask issue as well then.
