### ISSUE TITLE
How can I install app with --HEAD

### ISSUE THREAD

**Issue by WitzHsiao** [Homebrew/homebrew-bundle#98]
Hi 
I would like to install rbenv-build. And the command I run is ```brew install --HEAD ruby-build```.
How can I handle it with Brewfile?
Thanks!

**Comment by dunn** [comment]
I think `brew 'ruby-build', args: ['HEAD']` is what you want!

**Comment by justmytwospence** [comment]
This doesn't actually work for me, for example:

```
brew 'mu', args: ['HEAD', 'with-emacs']
```

results in this:

```
Built from source on 2016-05-06 at 10:20:17 with: --with-emacs
```

after running brew bundle.
