### ISSUE TITLE
Add DSL for homebrew/aliases

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-bundle#99]
Maybe it's a good idea to support `homebrew/aliases` inside bundle (install & dump). DSL may look like:

```ruby
alias "up" => "update"
alias "status" => "!git status"
```

cc @mikemcquaid @bfontaine

**Comment by bfontaine** [comment]
I agree it would be great to have a way to dump aliases in a file then load it later (like a `~/.bash_aliases` for Homebrew) but I don’t know if bundle is the best place to do so, as I see bundle more as a reusable formulae list that one can share; and aliases are something more personal you often want to keep for yourself.
TL;DR: I don’t have a strong opinion on this.

**Comment by mikemcquaid** [comment]
I'm OK with having aliases but probably they make the most sense in `--global`. Seems fine for them to work whenever though. I like the idea of adding (optional) support for more Homebrew ecosystem stuff.

**Comment by mikemcquaid** [comment]
@xu-cheng Is thit something you think you'll personally implement? If not: mind closing it out?

**Comment by xu-cheng** [comment]
I want to implement this but haven't found time to do so. Will close it for now.
