### ISSUE TITLE
Testing brew bundle CLI with bats

### ISSUE THREAD

**Issue by colindean** [Homebrew/homebrew-bundle#995]
#993 gave me an idea for even more tests. I've been using [bats](https://github.com/bats-core/bats-core) for a lot of stuff at work and wouldn't mind flexing that a little more along with digging into GitHub Actions (haven't touched it yet!). I could do up some public API tests that treat the `brew bundle` command as an opaque box. This has worked well for me for some CLI apps I've done through the years regardless of their implementation language.

Thoughts? Worth having, even as a smoke test of sorts?

**Comment by MikeMcQuaid** [comment]
I'd rather we take the approach more like https://github.com/Homebrew/homebrew-bundle/pull/993 than using bats, sorry.
